/* Glossary — every term the course uses, in plain English.
   Shape: {t: term, d: definition, k: category}. Powers the dotted-underline
   tooltips in lessons (first occurrence per term) and the Glossary page. */
window.GLOSSARY = [
/* ---------- Foundations ---------- */
{t:"LLM",d:"Large Language Model — an AI trained on vast text to predict the next token; Claude is one. It generates language by repeatedly predicting what comes next.",k:"foundations"},
{t:"large language model",d:"An AI system trained on huge amounts of text that produces language by predicting the next token, one at a time.",k:"foundations"},
{t:"token",d:"The chunk of text Claude reads and writes in — roughly 3/4 of a word. Prices and limits are all counted in tokens, not words.",k:"foundations"},
{t:"tokenization",d:"The process of splitting text into tokens before the model processes it. Common words are one token; rare words split into several.",k:"foundations"},
{t:"context window",d:"The maximum number of tokens Claude can consider at once — its working memory for a single conversation or request.",k:"foundations"},
{t:"context",d:"Everything Claude can currently see: your messages, its replies, system prompt, files, and tool results — all held in the context window.",k:"foundations"},
{t:"prompt",d:"The input you give Claude — your instruction, question, and any context. The quality of the prompt largely determines the quality of the output.",k:"foundations"},
{t:"completion",d:"The text Claude generates in response to a prompt. Also called the output or response.",k:"foundations"},
{t:"inference",d:"The act of running the model to produce output from an input. Each API call or message is one inference.",k:"foundations"},
{t:"parameters",d:"The billions of numbers learned during training that encode what the model knows. More parameters roughly means more capability and cost.",k:"foundations"},
{t:"training",d:"The process of teaching a model by showing it enormous amounts of text so it learns to predict tokens. Done once, ahead of time, by the lab.",k:"foundations"},
{t:"pretraining",d:"The first, largest training phase where the model learns language and knowledge from broad text before any fine-tuning.",k:"foundations"},
{t:"fine-tuning",d:"Additional training on narrower data to shape a model's behavior or specialize it after pretraining.",k:"foundations"},
{t:"knowledge cutoff",d:"The date after which a model has no built-in knowledge, because its training data ended there. Newer facts require search or tools.",k:"foundations"},
{t:"hallucination",d:"When a model states something false with confidence — an invented fact, citation, or detail. The core reason verification matters.",k:"foundations"},
{t:"weights",d:"Another name for the model's learned parameters — the numbers that define what it has learned.",k:"foundations"},
{t:"temperature",d:"A setting from 0 to 1 that controls randomness: low is focused and consistent, high is varied and creative.",k:"foundations"},
{t:"sampling",d:"How the model picks the next token from its probability distribution. Temperature and top-p tune this choice.",k:"foundations"},
{t:"top-p",d:"Nucleus sampling — the model considers only the most probable tokens whose combined probability reaches p, adding controlled variety.",k:"foundations"},
{t:"frontier model",d:"One of the most capable models available at a given time. Claude Opus is Anthropic's frontier-class model.",k:"foundations"},
{t:"model family",d:"A set of models at different capability and cost tiers — for Claude: Haiku (fast, cheap), Sonnet (balanced), Opus (most capable).",k:"foundations"},
{t:"Haiku",d:"Anthropic's fastest, cheapest Claude tier — ideal for high-volume, simpler tasks where speed and cost matter most.",k:"foundations"},
{t:"Sonnet",d:"Anthropic's balanced Claude tier — strong capability at moderate cost and speed; the default workhorse for most tasks.",k:"foundations"},
{t:"Opus",d:"Anthropic's most capable Claude tier — best for the hardest reasoning, at higher cost and slower speed.",k:"foundations"},
{t:"multimodal",d:"Able to work with more than text — Claude can also read images, PDFs, and other visual inputs.",k:"foundations"},
{t:"reasoning",d:"A model working through a problem in steps rather than answering instantly. Often improves accuracy on hard tasks.",k:"foundations"},
{t:"extended thinking",d:"A mode where Claude reasons at length before answering, spending extra tokens to think — better for complex problems.",k:"foundations"},
{t:"chain of thought",d:"Prompting a model to reason step by step, which usually improves accuracy on multi-step problems.",k:"foundations"},
{t:"grounding",d:"Tying a model's answer to provided sources (documents, search results) so it stays factual rather than inventing.",k:"foundations"},
{t:"verification",d:"The discipline of checking a model's output for accuracy before trusting it — the habit that separates pros from tourists.",k:"foundations"},
{t:"Anthropic",d:"The AI safety company that builds Claude, founded with a focus on developing reliable, interpretable, steerable AI.",k:"foundations"},
{t:"Constitutional AI",d:"Anthropic's training method that uses a set of principles (a constitution) to guide a model toward helpful, harmless behavior.",k:"foundations"},
{t:"alignment",d:"The effort to make AI systems pursue what humans actually intend — behaving helpfully, honestly, and harmlessly.",k:"foundations"},
{t:"prompt engineering",d:"The craft of writing prompts that reliably get great results — the highest-leverage skill for using AI well.",k:"prompting"},

/* ---------- Prompting ---------- */
{t:"system prompt",d:"Instructions that set Claude's role, rules, and context for a whole conversation, separate from your individual messages.",k:"prompting"},
{t:"few-shot",d:"Giving a model a few examples of the task in the prompt so it matches the pattern. Powerful for shaping format and style.",k:"prompting"},
{t:"zero-shot",d:"Asking a model to do a task with no examples — just an instruction. Works when the task is clear and common.",k:"prompting"},
{t:"one-shot",d:"Giving exactly one example in the prompt to guide the model's output.",k:"prompting"},
{t:"example",d:"A demonstration of the input-output you want. Showing examples usually beats describing rules ('show, do not tell').",k:"prompting"},
{t:"role prompting",d:"Telling Claude to act as a specific expert or persona so its tone and expertise fit the task.",k:"prompting"},
{t:"XML tags",d:"Angle-bracket labels used to structure a prompt — separating instructions, context, and examples so Claude parses them cleanly.",k:"prompting"},
{t:"delimiters",d:"Markers (like XML tags, quotes, or dashes) that separate parts of a prompt so the model knows where each section begins and ends.",k:"prompting"},
{t:"output format",d:"The structure you ask the response to take — JSON, a table, bullet points, a specific template — controlled by clear instructions.",k:"prompting"},
{t:"prefilling",d:"Starting Claude's response for it (putting words in its mouth) to steer the format or force a particular beginning.",k:"prompting"},
{t:"prompt chaining",d:"Breaking a complex task into a sequence of prompts, each handling one step and feeding the next — divide and conquer.",k:"prompting"},
{t:"prompt template",d:"A reusable prompt with fill-in slots, so you run the same reliable structure repeatedly with different inputs.",k:"prompting"},
{t:"structured extraction",d:"Pulling specific fields (names, dates, amounts) out of messy text into a clean, structured form like JSON.",k:"prompting"},
{t:"iteration",d:"Refining a prompt or output through a back-and-forth conversation — the conversation itself is part of the prompt.",k:"prompting"},
{t:"eval",d:"A test that measures how well a prompt or system performs on real examples — how engineers know a prompt actually works.",k:"prompting"},
{t:"evaluation",d:"Systematically measuring output quality against expected results, so improvements are proven rather than guessed.",k:"prompting"},
{t:"golden set",d:"A curated set of example inputs with known-good outputs, used to test whether a prompt or system performs correctly.",k:"prompting"},
{t:"long context",d:"Working with very large inputs (up to hundreds of thousands of tokens) — whole books or codebases — in one request.",k:"prompting"},
{t:"instruction following",d:"How well a model does exactly what it is told. Clear, direct instructions get better instruction following.",k:"prompting"},

/* ---------- Power User: app, Cowork, tools ---------- */
{t:"Claude app",d:"Anthropic's chat application (web, desktop, mobile) — the most common way people use Claude.",k:"power-user"},
{t:"Project",d:"A workspace in the Claude app that bundles instructions, files, and knowledge so Claude acts as a specialist for a recurring purpose.",k:"power-user"},
{t:"Projects",d:"Reusable Claude-app workspaces, each with their own instructions and knowledge — like a team of specialists you configure once.",k:"power-user"},
{t:"memory",d:"Claude's ability to remember information across conversations (where enabled), so you do not repeat context every time.",k:"power-user"},
{t:"artifact",d:"A standalone piece of content — a document, app, or diagram — that Claude creates in its own panel you can edit, preview, and reuse.",k:"power-user"},
{t:"artifacts",d:"Self-contained outputs (code, documents, visuals) rendered in a dedicated panel in the Claude app, from a sentence to working software.",k:"power-user"},
{t:"Research",d:"A Claude mode that searches many sources and returns a cited, synthesized report on a question.",k:"power-user"},
{t:"connector",d:"An integration that lets Claude reach into another tool or service (like Google Drive or Slack) to read or act on your data.",k:"power-user"},
{t:"connectors",d:"Integrations that plug Claude into your existing tools and data sources so it can work where your information already lives.",k:"power-user"},
{t:"Skill",d:"A packaged set of instructions and resources that teaches Claude to perform a task your specific way, consistently, every time.",k:"power-user"},
{t:"Skills",d:"Reusable capability packages (instructions plus resources) that make Claude perform specialized tasks reliably and repeatably.",k:"power-user"},
{t:"Cowork",d:"Anthropic's agentic workspace where you give Claude folders, permissions, and an outcome, and it returns finished work.",k:"power-user"},
{t:"agentic",d:"Describing AI that takes multiple actions toward a goal on its own — planning, using tools, and iterating — rather than just replying once.",k:"power-user"},
{t:"scheduled task",d:"An automation that runs on a schedule (like a Monday report) so work happens without you starting it each time.",k:"power-user"},
{t:"sub-agent",d:"A separate Claude instance spun up to handle a focused sub-task, keeping the main context clean and work parallel.",k:"power-user"},
{t:"permissions",d:"The controls that decide what Claude is allowed to access or do — which folders, tools, or actions. Central to using agents safely.",k:"power-user"},
{t:"Claude for Chrome",d:"Claude embedded in the Chrome browser, able to see and act on web pages to do tasks for you.",k:"power-user"},
{t:"Claude for Excel",d:"Claude embedded in Excel, able to read, analyze, and build spreadsheets with understanding of your data.",k:"power-user"},
{t:"surface",d:"A place Claude lives and works — the app, Cowork, Chrome, Excel, Slack, the API. Choosing the right surface for a job is a real skill.",k:"power-user"},

/* ---------- Builder: Claude Code, MCP, API, agents ---------- */
{t:"Claude Code",d:"Anthropic's agentic coding tool that works in your terminal, desktop, or web — planning, editing files, running commands, and shipping work.",k:"builder"},
{t:"CLAUDE.md",d:"A file that tells Claude Code about your project — its conventions, structure, and rules — so it works your way.",k:"builder"},
{t:"slash command",d:"A shortcut typed with a leading slash (like /review) that triggers a predefined action or workflow in Claude Code.",k:"builder"},
{t:"checkpoint",d:"A saved state in Claude Code you can roll back to, so you can experiment freely and undo if needed.",k:"builder"},
{t:"hook",d:"A script that runs automatically at a defined point in Claude Code's workflow (like before a commit) to enforce your rules.",k:"builder"},
{t:"hooks",d:"Automated scripts that fire at set moments in the Claude Code workflow to check, format, or gate actions.",k:"builder"},
{t:"MCP",d:"Model Context Protocol — the open standard that lets Claude connect to any data source or tool, like a USB-C port for AI.",k:"builder"},
{t:"Model Context Protocol",d:"The open standard (MCP) for connecting AI models to external tools and data through a common interface.",k:"builder"},
{t:"MCP server",d:"A program that exposes tools or data to an AI through MCP — you can use existing ones or build your own.",k:"builder"},
{t:"MCP client",d:"The application (like Claude Code or the desktop app) that connects to MCP servers and calls their tools.",k:"builder"},
{t:"tool",d:"A function Claude can call to do something beyond generating text — fetch data, run code, or take an action in the world.",k:"builder"},
{t:"tool use",d:"When Claude calls a defined function to get information or take an action, then uses the result to continue — giving it hands.",k:"builder"},
{t:"function calling",d:"Another name for tool use — the model outputs a structured request to run a function with specific arguments.",k:"builder"},
{t:"tool description",d:"The text explaining what a tool does and when to use it. Claude decides how to call a tool based on this, so precision matters.",k:"builder"},
{t:"transport",d:"How an MCP client and server communicate — locally (stdio) for a server on your machine, or remotely over the network.",k:"builder"},
{t:"stdio",d:"Standard input/output — the simple local transport MCP uses when the server runs on the same machine as the client.",k:"builder"},
{t:"remote MCP",d:"An MCP server hosted over the network so it can be shared and used by many clients, rather than running locally.",k:"builder"},
{t:"registry",d:"A directory where MCP servers or plugins are listed so people can discover and install them.",k:"builder"},
{t:"API",d:"Application Programming Interface — the way your own code sends requests to Claude and gets responses, turning you from user into builder.",k:"builder"},
{t:"Claude API",d:"Anthropic's programmatic interface for sending messages to Claude from your own software and building products on it.",k:"builder"},
{t:"Messages API",d:"The core Claude API endpoint for multi-turn conversations — you send a list of messages and get Claude's reply.",k:"builder"},
{t:"endpoint",d:"A specific URL in an API that accepts requests for one purpose, like the Messages endpoint for chat.",k:"builder"},
{t:"API key",d:"A secret credential that authenticates your API requests and ties usage to your account. Keep it private.",k:"builder"},
{t:"streaming",d:"Receiving a response token by token as it is generated, rather than waiting for the whole thing — feels faster and enables live UIs.",k:"builder"},
{t:"vision",d:"Claude's ability to see and interpret images and PDFs passed to it — reading charts, screenshots, documents, and photos.",k:"builder"},
{t:"structured output",d:"Forcing the API response into a defined shape (like validated JSON) so your code can rely on it every time.",k:"builder"},
{t:"JSON",d:"A simple, structured data format of keys and values — the common way APIs exchange machine-readable data.",k:"builder"},
{t:"schema",d:"A definition of the exact structure data must follow — field names, types, and rules — used to validate structured output.",k:"builder"},
{t:"prompt caching",d:"Reusing a stored, unchanging part of a prompt across requests so you are not billed full price for it each time — a large discount.",k:"builder"},
{t:"cache",d:"Stored data kept for fast reuse. In the API, cached prompt prefixes cut cost and latency on repeated context.",k:"builder"},
{t:"batch",d:"Submitting many requests together for asynchronous processing at a large discount, when you do not need instant answers.",k:"builder"},
{t:"batch processing",d:"Running a large set of API requests as one asynchronous job, trading immediacy for a significant price cut.",k:"builder"},
{t:"latency",d:"How long a request takes to respond. Lower latency feels snappier; streaming and smaller models reduce perceived latency.",k:"builder"},
{t:"throughput",d:"How much work a system handles per unit time — how many requests or tokens it can process.",k:"builder"},
{t:"rate limit",d:"A cap on how many requests or tokens you can send in a period, to keep the service stable. Handle it with retries and backoff.",k:"builder"},
{t:"token budget",d:"A deliberate limit on tokens per request or task, set to control cost and keep responses focused.",k:"builder"},
{t:"cost engineering",d:"Designing an AI product to be economical — choosing the right model, caching, batching, and trimming tokens so unit costs work.",k:"builder"},
{t:"model mix",d:"Using different model tiers for different steps — cheap models for easy parts, capable ones for hard parts — to balance cost and quality.",k:"builder"},
{t:"SDK",d:"Software Development Kit — a library that makes calling an API from your language easy, handling the plumbing for you.",k:"builder"},
{t:"Agent SDK",d:"Anthropic's toolkit for building agents, exposing the same engine that powers Claude Code as a library for your own systems.",k:"builder"},
{t:"agent",d:"An AI system that pursues a goal by looping — deciding, acting with tools, observing results, and repeating until done.",k:"builder"},
{t:"agent loop",d:"The core cycle of an agent: think, act (use a tool), observe the result, and decide the next step, repeating toward the goal.",k:"builder"},
{t:"orchestration",d:"Coordinating multiple steps, tools, or agents into a reliable workflow that accomplishes a larger task.",k:"builder"},
{t:"workflow",d:"A defined sequence of steps (prompts, tools, checks) that reliably accomplishes a task — more predictable than a free-form agent.",k:"builder"},
{t:"routing",d:"Directing each input to the right handler, model, or path based on its type — a common workflow pattern.",k:"builder"},
{t:"Managed Agents",d:"Anthropic-hosted agents that run in a managed sandbox, so you build agentic behavior without operating servers yourself.",k:"builder"},
{t:"guardrails",d:"Rules and checks that constrain an AI system's behavior to keep it safe, on-task, and within bounds.",k:"builder"},
{t:"human-in-the-loop",d:"Designing a system so a person approves or reviews key actions, catching errors before they cause harm.",k:"builder"},
{t:"reliability",d:"How dependably a system produces correct results across real inputs and edge cases — the line between a demo and a product.",k:"builder"},
{t:"sandbox",d:"An isolated environment where code or an agent can run without access to the rest of your system, limiting damage if something goes wrong.",k:"builder"},
{t:"least privilege",d:"Giving a system only the minimum access it needs and no more, so any compromise or mistake causes limited harm.",k:"builder"},
{t:"prompt injection",d:"An attack where malicious instructions hidden in content trick an AI into doing something unintended, like leaking data.",k:"builder"},
{t:"lethal trifecta",d:"The dangerous combination of private-data access, exposure to untrusted content, and an outbound channel — together enabling data theft via injection.",k:"builder"},
{t:"exfiltration",d:"The unauthorized removal of data from a system — what an attacker aims for when exploiting prompt injection.",k:"builder"},
{t:"deployment",d:"Putting a product live where real users can reach it — the step that turns code on your machine into an actual product.",k:"builder"},
{t:"serverless",d:"A hosting model where your code runs on demand without you managing servers — a simple way to deploy small products.",k:"builder"},
{t:"plugin",d:"An installable bundle of tools, skills, or MCP servers that extends Claude Code or Cowork with new capabilities.",k:"builder"},
{t:"context engineering",d:"Deliberately managing what goes into the context window — the right files, instructions, and results — so the model has what it needs and no clutter.",k:"builder"},

/* ---------- Operator: money & business ---------- */
{t:"freelancing",d:"Selling your skills as independent services to clients — often the fastest path to first income with Claude.",k:"operator"},
{t:"productized service",d:"A service packaged as a fixed, named offer with a set scope and price — easier to sell than custom, open-ended work.",k:"operator"},
{t:"retainer",d:"A recurring fee a client pays for ongoing work or availability — the basis of stable, predictable freelance income.",k:"operator"},
{t:"value-based pricing",d:"Pricing on the value your work delivers to the client, not the hours it takes you — the key to healthy margins with fast AI-assisted work.",k:"operator"},
{t:"scope",d:"The exact boundaries of what a piece of work includes. Clear scope prevents disputes and scope creep.",k:"operator"},
{t:"scope creep",d:"When a project's requirements gradually expand beyond the agreed work, eroding your margin. Controlled by clear scope.",k:"operator"},
{t:"portfolio",d:"A collection of your real, shipped work that proves your ability — your strongest asset for landing clients and jobs.",k:"operator"},
{t:"proof of work",d:"Demonstrable evidence you can do the thing — a portfolio of real builds — which beats credentials in a proof-gated field.",k:"operator"},
{t:"micro-SaaS",d:"A small software product, often built by one person on the API, serving a focused need with recurring revenue.",k:"operator"},
{t:"SaaS",d:"Software as a Service — software sold by subscription and delivered over the internet rather than installed and owned.",k:"operator"},
{t:"unit economics",d:"The cost and revenue of a single use or customer. If cost per use is below price, the product can be profitable.",k:"operator"},
{t:"COGS",d:"Cost of Goods Sold — what it costs to deliver one unit. For an AI product, largely the API tokens each use consumes.",k:"operator"},
{t:"margin",d:"The gap between what something costs you and what you charge. AI's speed and low token cost can make margins high.",k:"operator"},
{t:"MRR",d:"Monthly Recurring Revenue — the predictable subscription income a product earns each month.",k:"operator"},
{t:"churn",d:"The rate at which customers stop paying. Low churn is essential for a subscription product to grow.",k:"operator"},
{t:"validation",d:"Confirming that people actually want and will pay for an idea before building it fully — the antidote to wasted effort.",k:"operator"},
{t:"MVP",d:"Minimum Viable Product — the smallest version that delivers real value, built to test an idea quickly with real users.",k:"operator"},
{t:"lean",d:"A build approach that ships small, learns from real feedback, and iterates — avoiding big bets on unvalidated ideas.",k:"operator"},
{t:"content leverage",d:"Using content (posts, videos, writing) to reach many people and attract clients or customers at scale.",k:"operator"},
{t:"positioning",d:"How you present what you offer and to whom, so the right buyers instantly understand its value and choose you.",k:"operator"},
{t:"niche",d:"A focused market segment you specialize in. A clear niche makes you the obvious choice for that specific buyer.",k:"operator"},
{t:"disclosure",d:"Being honest with clients about AI-assisted work where it matters — part of the trust that sustains a service business.",k:"operator"},
{t:"AI-native",d:"Describing roles, people, or companies built around fluent AI use — a premium skill set in the 2026 job market.",k:"operator"},
{t:"AI engineer",d:"A role building AI-powered products and systems (API, agents, integrations) — high demand and strong pay in 2026.",k:"operator"},
{t:"certification",d:"A credential validating your knowledge (like Anthropic's Claude certifications) — a useful complement to a portfolio, never a replacement.",k:"operator"},
{t:"anti-hype",d:"The honest, grounded view of what AI money-making actually takes — real work and realistic expectations, not overnight riches.",k:"operator"},
{t:"flywheel",d:"A self-reinforcing loop where early wins (first income, testimonials) generate more opportunities, compounding growth over time.",k:"operator"},
{t:"testimonial",d:"A client's endorsement of your work — social proof that helps win the next client, and a reason to deliver excellently.",k:"operator"},
{t:"discovery call",d:"An early conversation with a prospect to understand their needs and show your fit before proposing work.",k:"operator"},
{t:"capstone",d:"A substantial project that consolidates everything learned into portfolio-grade proof of capability.",k:"operator"},

/* ---------- More foundations & mechanics ---------- */
{t:"generative AI",d:"AI that creates new content — text, images, code — rather than only classifying or predicting labels.",k:"foundations"},
{t:"neural network",d:"The layered mathematical structure, loosely inspired by the brain, that underlies models like Claude.",k:"foundations"},
{t:"transformer",d:"The neural-network architecture behind modern language models, using attention to weigh how tokens relate.",k:"foundations"},
{t:"attention",d:"The mechanism that lets a transformer focus on the most relevant tokens when predicting the next one.",k:"foundations"},
{t:"embedding",d:"A numeric representation of text that captures meaning, letting models compare and search by similarity.",k:"foundations"},
{t:"probability distribution",d:"The set of odds a model assigns to each possible next token before one is chosen by sampling.",k:"foundations"},
{t:"deterministic",d:"Producing the same output every time for the same input — what temperature 0 approximates.",k:"foundations"},
{t:"stochastic",d:"Involving randomness — why higher temperature yields varied outputs from the same prompt.",k:"foundations"},
{t:"input tokens",d:"The tokens in what you send Claude (prompt, context, files). Usually priced lower than output tokens.",k:"foundations"},
{t:"output tokens",d:"The tokens Claude generates in its reply. Usually the more expensive side of a request.",k:"foundations"},
{t:"max tokens",d:"A cap you set on how many tokens Claude may generate in one response, controlling length and cost.",k:"foundations"},
{t:"stop sequence",d:"A string that tells the API to stop generating when it appears, letting you bound the output cleanly.",k:"foundations"},
{t:"benchmark",d:"A standardized test used to compare models' capabilities on tasks like reasoning, coding, or math.",k:"foundations"},
{t:"context rot",d:"The quality drop that can occur when a context window is stuffed with too much irrelevant material.",k:"foundations"},

/* ---------- More plans & product surface ---------- */
{t:"desktop app",d:"The installable Claude application for Mac and Windows, which also hosts Cowork and can bridge to your local files.",k:"power-user"},
{t:"Pro plan",d:"A paid Claude subscription tier for individuals, offering more usage and features than the free tier.",k:"power-user"},
{t:"Max plan",d:"A higher-usage paid Claude subscription for heavy individual users who need more capacity than Pro.",k:"power-user"},
{t:"Team plan",d:"A Claude subscription for groups, adding collaboration and administration features for a workspace.",k:"power-user"},
{t:"Enterprise",d:"Claude's plan for large organizations, adding security, administration, and network controls.",k:"power-user"},
{t:"usage limits",d:"Caps on how much you can use Claude in a period on a given plan, which reset over time.",k:"power-user"},
{t:"marketplace",d:"A place to browse and install plugins — bundles of skills, tools, and MCP servers — for Cowork or Claude Code.",k:"power-user"},
{t:"read-aloud",d:"A feature that speaks text out loud so you can listen to content instead of reading it.",k:"power-user"},
{t:"canvas",d:"A visual editing surface for iterating on a document or artifact alongside the chat.",k:"power-user"},

/* ---------- More builder mechanics ---------- */
{t:"terminal",d:"The text-based command-line interface where tools like Claude Code can run and interact with your system.",k:"builder"},
{t:"CLI",d:"Command-Line Interface — a program you drive by typing commands, as opposed to clicking a graphical interface.",k:"builder"},
{t:"repository",d:"A project's folder of code and its version history, usually managed with git.",k:"builder"},
{t:"repo",d:"Short for repository — the tracked folder that holds a project's files and change history.",k:"builder"},
{t:"commit",d:"A saved snapshot of changes in version control, with a message describing what changed.",k:"builder"},
{t:"git",d:"The version-control system that tracks changes to files over time and lets you branch, merge, and roll back.",k:"builder"},
{t:"pull request",d:"A proposed set of changes submitted for review before merging into a shared codebase.",k:"builder"},
{t:"environment variable",d:"A setting stored outside your code (like an API key) that a program reads at run time, keeping secrets out of source.",k:"builder"},
{t:"webhook",d:"An automated message a service sends to a URL when an event happens, used to trigger workflows.",k:"builder"},
{t:"JSON mode",d:"An API setting that constrains output to valid JSON, making structured results dependable.",k:"builder"},
{t:"idempotent",d:"An operation that has the same effect whether run once or many times — important for safe retries.",k:"builder"},
{t:"retry",d:"Automatically re-attempting a failed request, often with a delay, to handle transient errors and rate limits.",k:"builder"},
{t:"backoff",d:"Waiting progressively longer between retries so a struggling service can recover — exponential backoff is common.",k:"builder"},
{t:"citation",d:"A reference to the source a claim came from. Claude's Research mode and grounded answers provide citations.",k:"builder"},
{t:"RAG",d:"Retrieval-Augmented Generation — fetching relevant documents and feeding them to the model so answers are grounded in real sources.",k:"builder"},
{t:"vector database",d:"A store that indexes embeddings so you can retrieve text by meaning — a common backbone of RAG systems.",k:"builder"},
{t:"parallel sessions",d:"Running multiple Claude Code or agent sessions at once to work on independent tasks simultaneously.",k:"builder"},
{t:"observability",d:"The ability to see what an AI system is doing through logs and traces, so you can debug and improve it.",k:"builder"},

/* ---------- More operator terms ---------- */
{t:"lead",d:"A potential client or customer who has shown interest — the top of your sales pipeline.",k:"operator"},
{t:"pipeline",d:"Your set of prospects at various stages from first contact to closed deal; also a repeatable processing workflow.",k:"operator"},
{t:"conversion",d:"Turning a prospect into a paying client or a visitor into a customer — the goal of your offer and pitch.",k:"operator"},
{t:"upsell",d:"Offering an existing client additional or higher-value work, growing revenue from a relationship you already have.",k:"operator"},
{t:"case study",d:"A written account of a real project and its results, used as proof to win similar clients.",k:"operator"},
{t:"cold outreach",d:"Contacting prospects who do not yet know you, with a relevant, personalized pitch.",k:"operator"},
{t:"landing page",d:"A focused web page that explains one offer and drives visitors to a single action, like signing up or buying.",k:"operator"},
{t:"pricing tier",d:"One of several packaged price levels for a product or service, letting buyers self-select by need and budget.",k:"operator"},
{t:"freemium",d:"A model offering a free tier to attract users, with paid tiers that unlock more — common for micro-SaaS.",k:"operator"},
{t:"runway",d:"How long you can sustain yourself financially while building — the time your savings buy before income must arrive.",k:"operator"},
{t:"ROI",d:"Return on Investment — the value gained relative to the cost or effort spent. Employers prize AI work that delivers measurable ROI.",k:"operator"},
{t:"agency",d:"A business that delivers services with a team, scaling beyond what one freelancer can do alone.",k:"operator"},
{t:"contract",d:"A written agreement defining scope, price, timelines, and terms — protecting both you and the client.",k:"operator"},
{t:"portfolio piece",d:"A single showcased project in your portfolio that demonstrates a specific capability to clients or employers.",k:"operator"}
];
