/* Interview Bank — real-world questions across the whole course.
   Shape: {d: "easy"|"med"|"hard", q: question, a: answer HTML}.
   The kind asked in AI-native job interviews and by paying clients. */
window.INTERVIEW = [

/* ---------------- EASY ---------------- */
{d:"easy", q:"What is a token, and why does it matter?",
 a:"<p>A token is the chunk of text a language model reads and writes in — roughly three-quarters of a word. It matters because everything is measured in tokens: the context window (how much Claude can see), pricing (you pay per input and output token), and limits. Thinking in tokens rather than words is how you reason about cost, capacity, and speed.</p>"},

{d:"easy", q:"Explain the difference between Haiku, Sonnet, and Opus.",
 a:"<p>They are tiers of the Claude model family trading capability against cost and speed. Haiku is the fastest and cheapest, best for high-volume or simpler tasks. Sonnet is the balanced workhorse — strong capability at moderate cost. Opus is the most capable for the hardest reasoning, at higher cost and slower speed. The skill is matching the tier to the task rather than defaulting to the biggest model.</p>"},

{d:"easy", q:"What is a hallucination, and how do you guard against it?",
 a:"<p>A hallucination is when a model states something false with confidence — an invented fact, citation, or detail. It happens because the model predicts plausible text, not verified truth. You guard against it by grounding answers in provided sources, allowing the model to say it does not know, asking for quotes and citations you can check, and above all verifying any factual output before relying on it. Verification is the core professional discipline.</p>"},

{d:"easy", q:"What makes a good prompt?",
 a:"<p>Clarity, context, and structure. State exactly what you want, provide the context the model cannot infer (audience, purpose, constraints), show examples where format matters, and specify the output format. A complete prompt is task plus context plus examples plus format plus constraints. Ambiguity is the number-one cause of poor output, so being clear and direct beats being clever.</p>"},

{d:"easy", q:"What is the context window?",
 a:"<p>It is the maximum number of tokens Claude can consider at once — its working memory for a single request or conversation. Everything it can see (your messages, its replies, the system prompt, files, tool results) lives there. It is large but finite, and stuffing it with irrelevant material can dilute focus, so managing what goes into it (context engineering) is a real skill.</p>"},

{d:"easy", q:"What is the Claude API, and how is it different from the app?",
 a:"<p>The app is the chat interface people use directly. The API is the programmatic interface: your own code sends messages to Claude and gets responses back, so you can build Claude into products and automations. The app makes you a user; the API makes you a builder. The same model powers both.</p>"},

{d:"easy", q:"What is MCP in one sentence?",
 a:"<p>The Model Context Protocol is an open standard that lets Claude connect to any tool or data source through a common interface — think of it as a USB-C port for AI. You can use existing MCP servers or build your own to give Claude new capabilities.</p>"},

{d:"easy", q:"What is Cowork?",
 a:"<p>Cowork is Anthropic's agentic workspace. Instead of chatting one message at a time, you give Claude folders, permissions, and an outcome, and it plans, acts, checks, and returns finished work. It is the biggest leverage jump for non-coders because it turns stated outcomes into completed tasks rather than just answers.</p>"},

{d:"easy", q:"Why is prompt engineering considered a valuable skill?",
 a:"<p>Because the quality of what you get from an AI depends heavily on how you ask, and small improvements in prompting produce large improvements in output across every task. It is the highest-leverage general skill for using AI well — a multiplier on everything else you do with the model — and it transfers across tools and model versions.</p>"},

{d:"easy", q:"What does 'show, do not tell' mean in prompting?",
 a:"<p>It means giving examples of the input and output you want (few-shot prompting) rather than only describing rules in words. A couple of concrete examples usually shape format, tone, and structure far more reliably than paragraphs of instructions, because the model matches the demonstrated pattern.</p>"},

/* ---------------- MEDIUM ---------------- */
{d:"med", q:"When would you use prompt caching and batch processing, and why?",
 a:"<p>Both are cost levers on the API. Prompt caching stores an unchanging prompt prefix (a long system prompt, a big reference document) so you are not billed full price for it on every request — ideal when many requests share the same large context. Batch processing submits many requests together for asynchronous handling at a large discount, ideal when you do not need instant answers (overnight jobs, bulk processing). Together they can cut costs dramatically, which is often the difference between a product whose unit economics work and one that loses money per use.</p>"},

{d:"med", q:"Walk me through the agent loop.",
 a:"<p>An agent pursues a goal by looping: it thinks about what to do next, acts by calling a tool, observes the result, and decides the next step — repeating until the goal is met or a stop condition triggers. The loop is what separates an agent from a single prompt-response: it can gather information, take actions, react to what it finds, and self-correct. The engineering challenge is making that loop reliable and safe — bounding it, verifying results, and gating consequential actions.</p>"},

{d:"med", q:"How do you decide between a fixed workflow and an autonomous agent?",
 a:"<p>Prefer the simplest design that solves the problem. A fixed workflow (a defined sequence of steps, routing, or chaining) is predictable, testable, and cheaper — use it when the steps are known in advance. An autonomous agent (a free-running loop) is more flexible but less predictable and harder to make reliable — reserve it for tasks where the path genuinely cannot be pre-determined. Adding autonomy is a cost in reliability and control, so you add it only when a simpler structure cannot do the job.</p>"},

{d:"med", q:"A client wants a service that turns meeting transcripts into summaries. How would you build it reliably?",
 a:"<p>As a templated pipeline with a quality gate. Break it into verifiable stages: extract decisions and action items tied to where they appear, structure them (owners, due dates, discussion), draft in a professional template, then verify the output against the transcript so nothing is invented or missed. Save the chain as a reusable Skill and the output as a formatted template so every run is consistent. The verification stage is essential — it protects accuracy, which is what the client is actually paying for. Then productize it: a named outcome, a turnaround, and value-based pricing.</p>"},

{d:"med", q:"What is the lethal trifecta, and how do you design around it?",
 a:"<p>It is the dangerous combination of three capabilities in one system: access to private data, exposure to untrusted content, and an outbound channel to send data out. Together they enable prompt injection to exfiltrate data — malicious instructions hidden in untrusted content can direct the AI to leak private information through the outbound channel. You design around it by breaking the chain: remove any one leg. Isolate untrusted content from private-data workflows, gate or remove outbound actions in sensitive contexts, or scope the system so it does not expose the sensitive data where risk exists. Recognizing and breaking this trifecta is the defining AI security skill.</p>"},

{d:"med", q:"How would you approach cost engineering for an AI product?",
 a:"<p>Start by measuring the real per-use cost: input plus output tokens times the model's price. Then optimize with the main levers — use a model mix (cheap models for easy steps, capable ones only where needed), apply prompt caching for repeated context, use batching for non-urgent bulk work, and trim tokens (tighter prompts, bounded outputs). The goal is honest unit economics: cost per use comfortably below price, with a healthy margin. Knowing your exact numbers and that the margin works is the maturity signal that separates a real product from a demo.</p>"},

{d:"med", q:"Why do tool descriptions matter so much in an MCP server?",
 a:"<p>Because Claude decides when and how to call a tool based entirely on its description. The description is the real interface, not the code. A powerful tool with a vague description gets misused or ignored; a simple tool with a precise description (what it does, when to use it, what each parameter means) gets used correctly. So when building a server, the highest-leverage work is writing clear, accurate tool descriptions — they matter more than clever implementation.</p>"},

{d:"med", q:"What is structured output, and when do you need it?",
 a:"<p>Structured output forces the model's response into a defined shape — typically validated JSON matching a schema — so your code can rely on it every time. You need it whenever the output feeds another program rather than a human: extraction pipelines, integrations, anything where an unexpected format would break downstream logic. It turns 'usually the right shape' into 'always the right shape', which is the difference between a fragile script and a dependable product.</p>"},

{d:"med", q:"How do Projects and Skills in the Claude app increase leverage?",
 a:"<p>Projects bundle instructions, files, and knowledge into a reusable specialist, so Claude starts every related chat already configured for that purpose — no re-explaining. Skills package a specific way of performing a task so Claude does it consistently, every time, across inputs. Together they turn one-off prompting into reusable infrastructure: you set up the context and capability once and get consistent, specialized results repeatedly, which is the operator's core move.</p>"},

{d:"med", q:"What separates a demo from a real AI product?",
 a:"<p>The engineering around the model call, not the call itself. A demo works in the happy path; a product handles messy real input, errors, and edge cases gracefully (reliability), has unit economics that work (cost engineering), is secure against injection and misuse (security), returns trustworthy structured data where needed, and is actually deployed where users can reach it. Anyone can call the API; far fewer can build the reliable, economical, secure, deployed system around it — and that surrounding engineering is where the value and scarcity live.</p>"},

{d:"med", q:"How should a freelancer price AI-assisted work, and why?",
 a:"<p>On the value of the outcome to the client, not on the time it takes. AI makes delivery fast, so hourly pricing on short work gives away the value. If a polished proposal helps win a deal, it is worth what it delivers regardless of the minutes spent. Your speed is your margin — the reason the work is profitable — not a reason to charge less. Productize a specific outcome with a set price, and price it against the result it produces for the client.</p>"},

{d:"med", q:"What is the honest picture of making money with content or products using AI?",
 a:"<p>It is real but not easy, and not fast. Building has become cheap and quick, which means the hard part has shifted to distribution — getting users and attention in a crowded space. Content can attract buyers but is slow and uncertain, with no guaranteed virality. Products need validation before building and a real distribution plan, not just a clever idea. The grounded expectation is real work, real iteration, and modest early results that compound — anyone promising overnight riches is selling hype.</p>"},

/* ---------------- HARD ---------------- */
{d:"hard", q:"Design a reliable customer-support agent. What are the main failure modes and how do you mitigate each?",
 a:"<p>Structure it as a mostly-workflow system with bounded agency. Core design: retrieve grounded answers from a trusted knowledge base (RAG) so responses are factual, use tools for defined actions (look up an order, create a ticket), and gate any consequential action (refunds, account changes) behind human approval or strict rules. Main failure modes and mitigations: <em>Hallucination</em> — ground every answer in retrieved sources and allow 'I do not know' with escalation. <em>Prompt injection</em> from user messages or ticket content — treat all user content as untrusted data, never as instructions, and apply least privilege so the agent cannot exceed its remit. <em>Wrong actions</em> — human-in-the-loop for high-stakes operations, idempotent tool calls, and confirmation steps. <em>Silent errors</em> — evals on real conversations, guardrails, logging and observability so you can see what it did. <em>Runaway loops or cost</em> — bound the loop and set token budgets. The theme: constrain autonomy to what is needed, ground for truth, gate for safety, and measure for reliability. Reliability engineering, not raw capability, is what makes it deployable.</p>"},

{d:"hard", q:"Explain how you would take a prompt from prototype to production-grade.",
 a:"<p>Treat the prompt as an engineered component, not a magic spell. First, build a golden set — a fixed collection of representative inputs with known-good outputs. Write an eval that scores the prompt against them so quality is measured, not guessed. Iterate the prompt with the techniques that fit (clear instructions, examples, XML structure, chain-of-thought for hard reasoning, prefilling for format), re-running the eval to confirm each change is a real improvement and does not regress other cases. Add hallucination defenses (grounding, allow 'I do not know', citations) and, if output feeds code, structured output with schema validation. Version the prompt and template it so it is reusable. In production, monitor real outputs, feed failures back into the golden set, and keep improving. The discipline — measure, iterate against tests, version, monitor — is exactly how software is engineered, applied to prompts.</p>"},

{d:"hard", q:"Your API product's costs are too high to be profitable. Walk through how you would fix the unit economics.",
 a:"<p>First, measure precisely: break down input versus output tokens per use and multiply by the model price to find the real per-use cost and where it concentrates. Then apply the levers in order of impact. <em>Model mix</em>: use a cheaper tier (Haiku or Sonnet) for the parts that do not need the strongest model, reserving Opus only for genuinely hard steps — often the single biggest saving. <em>Prompt caching</em>: cache large unchanging context (system prompt, reference documents) so you are not paying full price for it on every call. <em>Token trimming</em>: tighten prompts, remove unnecessary context, and bound output length with max tokens. <em>Batching</em>: move any non-urgent work to batch for a large discount. <em>Architecture</em>: avoid redundant calls, reuse results, and only invoke the model where it adds value. Re-measure after each change. If economics still do not work, reconsider the price (value-based, possibly higher) or the product scope. The goal is a per-use cost comfortably below price with a healthy margin — and knowing the exact numbers is itself the sign of a real builder.</p>"},

{d:"hard", q:"How would you build and secure an MCP server that gives Claude access to a company's internal database?",
 a:"<p>Design for capability and safety together. <em>Build</em>: expose narrow, well-described tools (for example, a scoped query tool and specific lookups) rather than raw database access, each with precise descriptions so Claude uses them correctly, and typed inputs and outputs. <em>Least privilege</em>: give the server read-only access if it only reads, scoped to the specific tables and rows needed — never broad or write access it does not require, so any compromise or misuse is contained. <em>Injection defense</em>: treat any content flowing through (user questions, returned data) as untrusted, never letting it act as instructions; parameterize queries so inputs cannot alter their structure. <em>Lethal trifecta</em>: the server exposes private data, so if a workflow also ingests untrusted content and has an outbound channel, you have exfiltration risk — break the chain by isolating such workflows, gating outbound actions, or scoping access. <em>Human-in-the-loop</em> for anything consequential. <em>Observability</em>: log every tool call for audit. <em>Verification</em>: check that results are correct and that tools were called with sensible arguments. The principle throughout is minimum necessary access, untrusted-by-default handling of content, and gates on anything with real consequences — capability delivered safely.</p>"},

{d:"hard", q:"Position yourself for an AI engineer role when you do not have a traditional ML background. What is your strategy?",
 a:"<p>Compete on applied ability and proof, which is what most AI-native roles actually want. The market has two common candidate types: theory-heavy people who have not shipped reliable products, and enthusiasts with hype but no depth. The scarce and valued profile is the applied builder-operator who can ship real, reliable, secure, economical AI systems — and you can demonstrate exactly that. Strategy: build a strong <em>portfolio</em> of shipped work (a deployed API micro-product with honest unit economics, an MCP server built and secured, real automations) — proof beats credentials in a proof-gated field. Emphasize the judgment employers struggle to find: reliability engineering, security awareness (injection, least privilege), and delivering measurable business ROI, not just demos. If you have domain expertise, position as 'AI-native [your field]' — domain plus AI is a scarce, premium combination. Add a relevant Anthropic certification as a credential signal that complements (never replaces) the portfolio. Target roles honestly at the level your proof supports, then deliver and grow. The core message: you are the applied builder with judgment who can ship trustworthy AI systems — the exact gap most candidates cannot fill.</p>"},

{d:"hard", q:"A stakeholder wants to automate a high-stakes decision entirely with an AI agent. How do you respond?",
 a:"<p>Push back constructively and redesign toward appropriate autonomy. High-stakes decisions are exactly where full automation is riskiest, because errors carry real consequences and models can fail confidently. Rather than refuse or comply blindly, I would map the workflow and separate the steps the AI can safely handle (gathering information, drafting options, surfacing analysis, flagging issues) from the decision itself, which should stay human — the AI informs and accelerates, a person decides and is accountable. This human-in-the-loop design captures most of the efficiency while keeping a check on the consequential act. I would add guardrails, grounding for factual accuracy, evals to measure reliability on real cases, logging for auditability, and least-privilege access so the agent cannot exceed its role. I would also set expectations honestly: the value is augmenting the decision-maker, not replacing them, and reliability must be proven before trust is extended. As confidence grows through measured performance, autonomy can be increased deliberately. The principle: match autonomy to stakes, keep humans accountable for consequential decisions, and earn trust through evidence rather than assuming it.</p>"},

{d:"hard", q:"Explain why applied AI skills may be a more durable career bet than AI research for most people.",
 a:"<p>Because the AI job market has bifurcated in a way that favors application. AI research — building and training the models — is a rarefied, specialized field concentrated at a few labs, requiring deep ML expertise, employing relatively few people, and increasingly capital-intensive. Applied AI — building products, systems, and value with the models — is where the vast majority of jobs, growth, and opportunity are, and it does not require becoming a researcher: you need to use the models expertly, not train them, just as a great software engineer need not design semiconductors. This favors applied skills durably: as models improve and commoditize, relative value shifts even more toward the application layer (using the improving models well) rather than research (building them, done by fewer). And within applied AI, the scarce premium subset is the builder-operator with judgment — reliability, security, economics — because that is the difference between building a demo (common) and shipping a trustworthy system (scarce), which the increasingly consequential application era needs more of. So betting on applied skills is not settling; it is targeting the large, growing, durable side of AI work, with the judgment-heavy specialization that stays valuable as the models themselves become commodities.</p>"}

];
