/* Track 6 — Claude in Your Tools (L2) */
(function(){
var L = window.LESSONS;

/* ------------------------------------------------ 6.1 */
L["6.1"] = {
  sub: "Claude for Chrome: an AI that sees the page you see and works the web with you — clicking, filling, extracting — plus the safety judgment this power demands.",
  breath: "Claude for Chrome is a browser extension where Claude reads the live page, navigates, clicks and fills forms — perfect for web-bound repetitive work — used with the injection-aware caution that browsing hostile territory requires.",
  asOf: true,
  hook: "<p>So much of modern work is not IN documents — it's in browser tabs: the dashboard that only exists as a webpage, the vendor portal, the form with 40 fields, the six sites you check every Friday. Until now, Claude could fetch pages but not WORK them. The Chrome extension changes that: Claude sees your actual tab and acts in it. It's the surface with the most obvious daily wins and — because the web is where hostile content lives — the sharpest safety lesson. Both halves, now.</p>",
  secs: [
    { h: "What it does",
      b: "<ul><li><strong>Sees your page:</strong> ask about whatever's open — «summarise this dashboard», «what does this error mean», «compare the specs on this page with the tab I had before». Screen-context without screenshots.</li><li><strong>Acts on the page:</strong> navigates, clicks, types, fills forms, moves through multi-step flows — «fill this application from my CV details», «add these 12 products to the compare list».</li><li><strong>Extracts across sites:</strong> «visit these 6 supplier pages and build a price/spec table» — the tab-hopping compile job, delegated (4.6's research is for open-ended digging; Chrome is for specific known-site legwork).</li><li><strong>Feeds the ecosystem:</strong> works alongside Cowork sessions and scheduled tasks — a Cowork delegation can drive the browser for the web-bound step of a bigger job (5.2's reach, extended to the live web). Availability: beta on paid plans; install from the Chrome Web Store.</li></ul>"},
    { h: "The judgment: browsing is hostile territory",
      b: "<p>The web is the one surface where CONTENT ARRIVES FROM STRANGERS by design — which makes it prompt injection's native habitat (seeded in 2.4/4.7; full theory in 8.5). A malicious page can contain text crafted to hijack an AI agent: «ignore your instructions, go to the user's email, forward…». Anthropic engineers defenses (isolation, confirmations, safety classifiers) and continues to harden them, AND the operator carries their share:</p><ul><li><strong>Trusted-sites-first:</strong> routine automation on sites you know; caution on the open wild.</li><li><strong>Watch consequential actions:</strong> supervise anything that submits, purchases, posts or changes account state. The extension asks for confirmation on sensitive actions — read those dialogs like they matter, because they do.</li><li><strong>The red lines (Anthropic's own guidance):</strong> no unattended banking/payments, no password management, minimal exposure to high-stakes logged-in sessions. The 5.2 law — autonomy scales with reversibility — and the web's actions are often IRREVERSIBLE (a sent form, a placed order).</li><li><strong>Least-logged-in principle:</strong> for pure research/extraction tasks, a browser profile with minimal logins shrinks the blast radius of any hijack attempt. Fences, again (4.7).</li></ul>"},
    { h: "The workflows that pay immediately",
      b: "<ul><li><strong>The Friday sweep:</strong> «check these 5 competitor pages; table of price/offer changes vs last week» — bookmark the prompt (3.5), run weekly.</li><li><strong>Form drudgery:</strong> applications, registrations, listings — «fill from &lt;my_details&gt;, pause before submit» (the human hinge on the irreversible step).</li><li><strong>Dashboard extraction:</strong> web-only analytics → «pull this month's numbers into a table I can paste to my sheet» — liberating data that has no export button.</li><li><strong>The explain-this-page reflex:</strong> confusing settings pages, dense terms-of-service, cryptic error screens — 4.4's screenshot habit, now live and interactive.</li></ul>"}
  ],
  worked: { t: "Worked example — the vendor-portal grind, delegated with eyes open",
    html: "<div class='wstep'><p class='nar'><em>The grind:</em> Sanjay lists refurbished laptops on three marketplace portals — 15 minutes of form-filling per listing, per site, from the same spec sheet. <em>The delegation:</em> «From &lt;specs&gt;, fill the new-listing form on this portal: map fields sensibly, photos from the folder I picked, price from the sheet. PAUSE before final submit — I review each listing.»</p></div><div class='wstep'><p class='nar'><em>The judgment calls visible:</em> pause-before-submit (irreversible action = human hinge); he watches the first two fills completely (calibration — 4.7's week-one rule), then just reviews the pre-submit state for the rest. One field mapping was wrong on portal #2 (their «condition» taxonomy differs) — caught at review, corrected once, correct forever after («keep/change/because» on a running browser task — 2.7 lives everywhere).</p></div><div class='wstep'><p class='nar'><em>Accounting:</em> 45 minutes of grind per batch → 8 minutes of review. And the safety posture cost him nothing: the pauses land exactly where his attention was needed anyway. <em>Power used precisely; caution placed exactly where irreversibility lives. That's the whole surface in one story.</em></p></div>"},
  lab: { where: "Chrome + Claude extension (paid plans, beta)",
    html: "<p>Install the extension, then run the two-sided drill. Side one — reading (zero risk): open any dense page (a pricing page, a dashboard, terms of service) and ask:</p>" + PB("prompt — page reading", "Look at this page. (1) Summarise what it's actually saying in 3 bullets. (2) What's the catch, limitation, or fine-print item most people would miss? (3) What question should I ask before acting on this page?", "prompt") + "<p>Side two — acting (low stakes): pick a harmless multi-step task (a comparison across 3 known sites, a form on a site you trust — stopping before submit):</p>" + PB("prompt — page acting", "Visit [SITES/PAGES] and build me a comparison table of [FIELDS]. Then: [IF A FORM] fill the form at [PAGE] from these details: <details>[YOURS]</details> — map fields sensibly, and PAUSE before any submit so I can review.", "prompt"),
    expect: "Reading side: instant comprehension of pages you'd have skimmed badly. Acting side: real clicks, real fills, and the pause landing before anything irreversible. Notice where the confirmation dialogs appear — that's the safety architecture showing itself." },
  mistakes: [
    "<b>Unattended consequential actions.</b> Purchases, posts, submissions without review — the exact category every guidance document red-lines. Hinge the irreversible.",
    "<b>Treating all pages as friendly.</b> Web content is stranger-content; the injection threat is real enough that Anthropic engineers against it. Trusted sites for automation; alertness elsewhere.",
    "<b>Using Chrome for what Research does better.</b> Open-ended «find out about X» → Research mode (4.6). Chrome wins for KNOWN sites and INTERACTIVE steps.",
    "<b>Full-login-everything profiles for research tasks.</b> Blast radius is a choice — least-logged-in browsing for extraction work.",
    "<b>Skipping calibration.</b> Watch the first runs fully (the 4.7 week-one rule); browsers have quirks per site, and one field-mapping check saves a hundred wrong listings."
  ],
  quiz: [
    { q: "Chrome vs Research mode — the right split:",
      opts: ["They're identical", "Chrome for known-site legwork and interactive steps (click, fill, extract); Research for open-ended multi-source investigation", "Chrome is always better", "Research replaced Chrome"],
      a: 1,
      why: ["Different tools: one works pages, one investigates questions.", "Correct — «walk these 6 known portals» = Chrome; «what's the market for X» = Research. Interactivity and specificity decide.", "Not for open investigation — Research reads far more, faster, with citations.", "They compose: research findings often become Chrome checklists."] },
    { q: "Why is the browser THE prompt-injection habitat?",
      opts: ["Browsers are old software", "Web content arrives from strangers by design — any page can contain text crafted to hijack an agent reading it", "It isn't a risk", "Only social media is risky"],
      a: 1,
      why: ["Age isn't the issue; provenance is.", "Correct — the agent reads what the page says, and pages say what strangers wrote. Hence confirmations, red lines, and least-logged-in habits. Full defense theory: 8.5.", "Anthropic's own docs name it explicitly and engineer against it — real enough to respect.", "ANY stranger-authored content qualifies — including a comment field on a trusted site."] },
    { q: "«Pause before submit» earns its place because:",
      opts: ["Submits are slow anyway", "Submission is the irreversible moment — the human hinge belongs exactly where undo stops existing", "It's required by law", "Forms are unimportant"],
      a: 1,
      why: ["Speed isn't the axis.", "Correct — 5.2's principle (autonomy scales with reversibility) applied at the web's point of no return. Sanjay's whole safety posture was one well-placed pause.", "It's judgment, not statute.", "Forms are consequential — that's precisely why the pause."] }
  ],
  prac: [
    { tag: "warm", q: "Sort into Chrome / Research / Cowork-with-browser: (a) «what are 2026's best CRM tools for small firms?», (b) «pull this week's numbers from our web-only analytics into a table», (c) «every Monday, check these 4 portals and file a price-change report».",
      sol: "(a) Research — open investigation (b) Chrome — known site, interactive extraction (c) <b>Cowork-with-browser on a schedule</b> — recurring web-bound pipeline (5.5 + 6.1 composed). The composition answer is the operator answer." },
    { tag: "transfer", q: "Find YOUR web grind (a recurring tab-hopping or form-filling ritual). Spec it with calibration and hinges, run it twice, log the minutes.",
      sol: "<b>Spec test:</b> does it name the sites, the fields, the pause-points, and what you review? First run watched fully, second run reviewed-at-hinges. The minutes go in the ledger — web grinds are often the biggest single line item people find." },
    { tag: "stretch", q: "Design the browser-automation policy for a small e-commerce team (3 people, marketplace listings, competitor watching, order dashboards): allowed unattended, allowed-with-review, banned — and the one profile-hygiene rule.",
      sol: "<b>One sound policy:</b> unattended — read-only extraction on their own dashboards and known competitor pages (scheduled, receipts filed). With-review — listing creation/edits (pause-before-submit), bulk anything. Banned — payments, account-setting changes, anything on the storefront's admin while logged in as owner-role. Profile hygiene: automation runs in a dedicated profile with the minimum logins the tasks need. You've just written 8.5's lessons as operations policy — before formally taking 8.5. That's the course compounding." }
  ],
  recap: "Chrome gives Claude eyes and hands on the live web — spend it on known-site legwork and form drudgery, hinge every irreversible action, browse hostile territory least-logged-in, and calibrate before you trust.",
  review: "From Lesson 5.2: «autonomy scales with reversibility» — the web adds the sharpest version: submits and purchases don't undo. Same law, higher stakes.",
  bridge: "From the browser to the grid: Claude for Excel — where the workbook stays a workbook and every change carries a cell-level citation.",
  deep: "<p><strong>Computer use: the general case behind the extension.</strong> Chrome-driving is the consumer face of a deeper capability Anthropic ships on the API as <em>computer use</em> — a model operating a screen: looking at pixels, moving a cursor, typing (Track 9's tool catalogue includes it). The engineering realities explain the beta labels everywhere: screen-grounding (mapping intent to the right pixel on shifting layouts) is genuinely hard; latency per action is high (screenshot → reason → act, repeated); and safety multiplies because EVERYTHING on screen is input, trusted or not — which is why serious deployments run in isolated VMs with the narrow permissions you practised. Strategic read: browser/computer agency is the capability with the steepest current improvement slope — sites are also adapting TOWARD agents (cleaner semantics, agent-friendly flows, emerging standards for agent-site interaction), so expect this surface to feel dramatically smoother year over year. The judgment you built today — hinge irreversibles, scope logins, calibrate first — is the part that transfers unchanged into that future; the friction is the part that melts.</p>"
};

/* ------------------------------------------------ 6.2 */
L["6.2"] = {
  sub: "Claude for Excel: the analyst add-in — explains formulas, finds errors, builds models — with cell-level citations, inside the workbook where finance actually lives.",
  breath: "Claude for Excel works inside your spreadsheet — answering questions with cell citations, tracing formulas, fixing errors, building and editing models with change tracking — for the world where the .xlsx IS the deliverable.",
  asOf: true,
  hook: "<p>Somewhere in your organisation is a workbook everyone fears: 14 tabs, formulas nobody wrote, one cell that turns red for reasons lost to history. Spreadsheets run more of the world's finance than any «real» software — and they're where errors hide best (whole hedge funds have stumbled on one bad cell). Claude for Excel puts the analyst INSIDE the grid: ask it what the workbook does, and it answers with citations to the exact cells. For anyone whose work lives in Excel, this is the difference between using AI and having a colleague.</p>",
  secs: [
    { h: "What it does inside the grid",
      b: "<ul><li><strong>Answers with cell citations:</strong> «why is Q3 margin down?» → an explanation citing B14, the driver cells behind it, and the tab where the assumption lives. Claims you can click — 3.4's provenance discipline, shipped as a product feature.</li><li><strong>Traces and explains formulas:</strong> the 90-character nested monster → plain-English what-it-does, what feeds it, what it feeds. Inherited-workbook archaeology, solved.</li><li><strong>Finds breakage:</strong> errors, circular references, inconsistent formulas across a range (the row where someone hard-coded over the formula in 2023 — the classic silent killer).</li><li><strong>Builds and edits Excel-natively:</strong> models from scratch or into your template — sorting, filtering, pivots, conditional formatting, data validation — with <strong>change tracking and explanatory comments</strong>, so every edit is visible and reviewable (the receipts principle, 5.3, built in).</li><li><strong>Boundaries as of July 2026:</strong> .xlsx/.xlsm on Excel web, Windows, Mac, iPad; no VBA/macros authoring, and treat it — per Anthropic's own guidance — as a colleague whose work you review, not an auto-signer of final deliverables.</li></ul>"},
    { h: "The three jobs it transforms",
      b: "<ul><li><strong>Archaeology</strong> (inherited workbooks): «map this workbook — every tab's purpose, the calculation flow between tabs, and the top 5 cells everything depends on.» The fear-workbook becomes a documented system in minutes.</li><li><strong>Audit</strong> (before the meeting): «check this model for: formula inconsistencies within ranges, hard-coded values where formulas should be, circular refs, and cells that disagree with their column's pattern — list with locations.» Your 5.4 sign-off ritual gains an instrument.</li><li><strong>Build</strong> (5.4's specs, in-grid): assumptions block + live formulas + reconciliation checks — same architecture, now executed where the file lives, with change-tracking as the built-in receipt. Cowork builds workbooks FROM sources at folder scale; the add-in refines and interrogates IN the workbook. They compose.</li></ul>"},
    { h: "The operator's Excel discipline",
      b: "<ul><li><strong>Citations get clicked</strong> (the 3.4 reflex): the answer says B14 — you look at B14. Ten seconds; the whole trust model.</li><li><strong>Changes get reviewed via tracking:</strong> the add-in's edits arrive visible — review them like a colleague's, especially on models that move money.</li><li><strong>Injection awareness, spreadsheet edition:</strong> a spreadsheet from outside is stranger-content (a vendor's «template» can carry hostile text in cells — same theory as 6.1's pages). Anthropic's guidance: trusted documents; caution with external files. Your least-privilege instincts apply to workbooks too.</li><li><strong>The final-deliverable rule:</strong> AI-assisted, human-signed. Audit-critical calculations get YOUR verification pass — the tool accelerates the analyst; the analyst still signs (5.4's byline law, now in the grid where it was always most needed).</li></ul>"}
  ],
  worked: { t: "Worked example — the inherited pricing model, defused",
    html: "<div class='wstep'><p class='nar'><em>The workbook:</em> Farah inherits the agency's pricing model — 11 tabs, built by someone who left, feared by everyone. Quotes come out of it; nobody knows how. <em>Move 1 — archaeology:</em> «map this workbook: each tab's role, the flow between them, the cells everything depends on.» Out comes the system diagram in prose: Inputs → Rates → three service calculators → Quote. Plus a flag: two tabs appear disconnected from everything (dead legacy — confirmed and archived later).</p></div><div class='wstep'><p class='nar'><em>Move 2 — audit:</em> the inconsistency sweep finds the classic: in Rates, one row's formula was overwritten with a hard-coded number in some forgotten emergency — every quote using that service tier has been slightly wrong since. Cell cited; she clicks; there it is. <em>The error a human eyeball had passed over for two years, caught by pattern-checking the range.</em></p></div><div class='wstep'><p class='nar'><em>Move 3 — repair, reviewed:</em> the fix goes in with change-tracking on; she reviews the tracked change, re-runs the reconciliation row (which her predecessor never built — she adds one, per 5.4), and documents the model with a generated «how this workbook works» tab. <em>The fear-workbook is now an asset with a manual. Time: one afternoon. The error's two-year cost: unknown and better left uncalculated.</em></p></div>"},
  lab: { where: "Excel + Claude add-in (Pro+; Microsoft Marketplace)",
    html: "<p>Install the add-in (Microsoft Marketplace → Claude for Excel), open a real workbook — ideally one you didn't build — and run the three jobs:</p>" + PB("prompt — archaeology + audit", "(1) Map this workbook: each tab's purpose, how data flows between tabs, and the 5 cells the results most depend on — cite cells for everything. (2) Audit it: formula inconsistencies within ranges, hard-coded values where neighbours have formulas, circular references, and any cell that breaks its column's pattern — list each with its location and why it's suspicious.", "prompt") + "<p>Click three of the cited cells to verify. If anything was flagged, fix it with change-tracking on, review the tracked change, then ask for a reconciliation check to add.</p>",
    expect: "A prose map of a workbook you feared, at least one genuine finding on most real-world files (hard-coded overwrites are epidemic), and the experience of citation-click verification in the grid. If the audit found nothing — congratulations, rare — the map alone is worth the lesson." },
  mistakes: [
    "<b>Citations admired, never clicked.</b> The cell reference is the product's honesty; the click is yours. (3.4's law reaches its ancestral home.)",
    "<b>Untracked edits on money models.</b> Change tracking exists — leaving it off on consequential workbooks discards the receipt for no gain.",
    "<b>External templates trusted blind.</b> Vendor workbooks are stranger-content — the 6.1 caution applies to grids, not just pages.",
    "<b>Auto-signing final deliverables.</b> Audit-critical numbers get the human pass — «the AI checked it» is not a signature (5.4's byline).",
    "<b>Using the add-in for folder-scale jobs.</b> Forty workbooks → one dataset is Cowork's extract pattern (5.3); the add-in shines IN a workbook, not across a directory."
  ],
  quiz: [
    { q: "Cell-level citations matter because:",
      opts: ["They look precise", "Every claim about the workbook becomes click-verifiable at its source — provenance (3.4) as a product feature in the domain where errors hide best", "Excel requires them", "They speed up formulas"],
      a: 1,
      why: ["Looking precise and being checkable are different things — this is the second.", "Correct — «margin fell because of B14» is auditable in ten seconds. In spreadsheet-land, that's the entire trust model.", "No — it's Anthropic's design choice, and the right one.", "Performance is unaffected; verifiability is transformed."] },
    { q: "The audit sweep's most famous catch — «hard-coded value where neighbours have formulas» — is dangerous because:",
      opts: ["It's ugly", "It silently freezes one cell out of the model — every downstream result is subtly wrong while LOOKING formula-driven", "It slows recalculation", "It's not dangerous"],
      a: 1,
      why: ["Aesthetics are the least of it.", "Correct — the emergency-overwrite that outlives the emergency. Farah's two-year error; the pattern-check exists because human eyes pass over it indefinitely.", "Performance is irrelevant next to correctness.", "Ask anyone who's re-quoted two years of clients."] },
    { q: "A supplier emails you their «cost calculator» workbook. Before letting the add-in work on it deeply, you:",
      opts: ["Nothing — spreadsheets are safe", "Treat it as stranger-content: it's from outside, and cells can carry hostile text — trusted-documents caution applies (6.1's theory, grid edition)", "Delete Excel", "Print it first"],
      a: 1,
      why: ["External files are exactly where the guidance draws the caution line.", "Correct — injection theory doesn't care about file extensions. Anthropic's own docs flag untrusted spreadsheets specifically.", "Excessive.", "Charming, unhelpful."] }
  ],
  prac: [
    { tag: "warm", q: "Which tool for which job: (a) 60 expense workbooks → one master sheet, (b) «why does this quote come out ₹4k higher than last month?», (c) build a hiring-cost model from scratch in your template, (d) «document how this inherited model works».",
      sol: "(a) Cowork extract (5.3) (b) add-in — in-grid tracing with citations (c) either, but add-in if the template lives in Excel and you'll iterate in-place (d) add-in archaeology. The split: ACROSS files = Cowork; WITHIN a workbook = add-in." },
    { tag: "transfer", q: "Run the archaeology + audit on the scariest workbook you have access to. Fix one finding with tracking on, add one reconciliation check, and write the 3-line «what this model actually does» note.",
      sol: "<b>Deliverables check:</b> a map, ≥1 audited finding (or a clean bill), a tracked fix, a check row, a note. That bundle — performed on a client's fear-workbook — is a sellable engagement whole and entire (11.2 will name it «the model health-check», and it prices at real money because the fear is real)." },
    { tag: "stretch", q: "A finance manager asks: «If Claude edits our models, how do I maintain audit-compliance?» Give the mechanism-based answer.",
      sol: "<b>The mechanisms:</b> (1) change tracking on all AI edits — reviewable diffs, named reviewer; (2) citations clicked and logged for load-bearing answers; (3) reconciliation rows as permanent tripwires; (4) the human-signs rule on final deliverables, in writing; (5) external workbooks quarantined until reviewed (stranger-content rule). Note the shape — identical to 5.4/5.5's policies: audit trails + human dispatch + tripwires. One discipline, every surface. That consistency IS your professional story when clients ask «can we trust this?»" }
  ],
  recap: "The analyst in the grid: archaeology, audit, and reviewed builds — click the citations, track the changes, quarantine stranger-workbooks, and sign the final numbers yourself.",
  review: "From Lesson 5.4: the assumptions-block-and-reconciliation architecture you learned for BUILDING sheets is exactly what the add-in helps you AUDIT in inherited ones. Build-standards are audit-standards.",
  bridge: "From the grid to the group chat: Claude in Slack and Microsoft 365 — the assistant your whole team shares, and what changes when AI enters the room where decisions happen.",
  deep: "<p><strong>Spreadsheet risk is a documented epidemic — which is why this surface matters more than it looks.</strong> Research on spreadsheet errors (a real academic field — EuSpRIG keeps the horror catalogue) consistently finds error rates of ~1% or more per cell in operational workbooks, with celebrated disasters to match: the London Whale's copy-paste modelling error (billions), Reinhart–Rogoff's austerity-shaping range mistake, pandemic case-counts lost to a row limit. The structural causes: spreadsheets mix data, logic and presentation in one editable surface, with no tests, no types, and no review culture — software's worst practices, running the world's finance. Now note what the add-in actually imports: <em>software engineering's immune system</em> — pattern-checking (linting), change tracking (version control diffs), citations (traceability), reconciliation rows (assertions). The 2026 significance isn't «AI in Excel»; it's the arrival of review discipline into the tool that never had one. For your career: «I audit and document spreadsheet models with AI-grade thoroughness» is a service with decades of accumulated demand behind it — every firm has fear-workbooks, and now you're the person who defuses them (11.2, service catalogue, entry three).</p>"
};

/* ------------------------------------------------ 6.3 */
L["6.3"] = {
  sub: "Claude in Slack and Microsoft 365: the assistant becomes a colleague-in-common — thread summaries, drafted replies, meeting prep — and the etiquette of AI in shared rooms.",
  breath: "Claude integrates into Slack and the Microsoft 365 world — summarising threads, drafting in-context, answering against team knowledge — turning private leverage into shared leverage, with team norms doing the safety work permissions can't.",
  asOf: true,
  hook: "<p>Everything so far was YOUR leverage: your prompts, your rooms, your operation. But work happens in shared spaces — the Slack channel where decisions form, the 80-message thread you were added to at message 60, the meeting that produced five action items nobody wrote down. When Claude enters the team's rooms, a new kind of value appears (shared context, instantly queryable) and a new kind of judgment (what does AI change about how a TEAM talks?). Both, briefly and usefully, now.</p>",
  secs: [
    { h: "What team-surface Claude does",
      b: "<ul><li><strong>Thread catch-up:</strong> «summarise this thread — decisions, open questions, who owes what» — the 60-message archaeology, solved in the room where it lives.</li><li><strong>Drafts in context:</strong> replies that have READ the thread — tone-matched, history-aware (4.7's draft-in-context, team edition; the human hinge still applies: you post, not it).</li><li><strong>Team knowledge answers:</strong> connected to the workspace's docs and channels, it answers «what did we decide about X?» from where the deciding actually happened — institutional memory, queryable.</li><li><strong>Meeting-adjacent work:</strong> agendas from threads, minutes from transcripts (your 4.8 minutes-skill firing in shared context), action-item extraction with owners — the 5.4 artifacts, sourced from group conversation.</li><li><strong>Where it lives:</strong> Slack integration (add Claude to the workspace; @-mention it in threads) and Microsoft 365 (Outlook/Teams/OneDrive-world connections per plan — Pro+ for the M365 connector; Team/Enterprise for the full workspace story). Exact capabilities move fast — the release-notes habit (4.1) applies double on team surfaces.</li></ul>"},
    { h: "What changes when AI enters shared rooms",
      b: "<ul><li><strong>Visibility of queries:</strong> in a channel, your @Claude question may be visible to the room — clarity is now a public good (and your 2.2 skills are on display; teams learn prompting from each other's visible prompts, which is genuinely how adoption spreads).</li><li><strong>Shared context ≠ shared permissions:</strong> what Claude can read in a workspace follows the workspace's access rules — but NORMS must cover what permissions can't: is it okay to AI-summarise a sensitive HR thread? To draft-reply on someone's behalf? Teams that never discuss this discover disagreements at the worst moment.</li><li><strong>The minutes-and-memory shift:</strong> when any thread is summarisable on demand, «I'll catch up later» becomes real, meetings need less recap, and WRITING THINGS DOWN WHERE CLAUDE CAN SEE THEM becomes the team's highest-leverage habit — ambient documentation, finally incentivised.</li><li><strong>Etiquette floor (propose these to any team):</strong> AI drafts are labelled as drafts until a human owns them; summaries of people-sensitive threads need the thread's consent; the bot answers questions — humans make announcements. Small norms, most of the safety.</li></ul>"}
  ],
  worked: { t: "Worked example — the project channel that stopped losing decisions",
    html: "<div class='wstep'><p class='nar'><em>The team:</em> a 7-person product squad, decisions scattered across a 4,000-message channel. New joiner asks «why did we drop the referral feature?» — 40 minutes of scroll-archaeology, twice a week, someone. <em>Claude joins the workspace.</em> Same question, @-mentioned: the answer cites the March thread — decision, reasoning, who made the call, link.</p></div><div class='wstep'><p class='nar'><em>The habits that grew around it (this is the real story):</em> Fridays, someone runs «this week's decisions + open items by owner» and pins it (a 5.5-style ritual, shared). Meeting minutes moved from someone's reluctant notebook to «paste transcript, extract decisions/actions/owners» — the 4.8 skill, now team property. And a subtle culture shift: people started WRITING decisions in the channel instead of deciding in DMs — because written-where-Claude-sees-it means retrievable-forever. <em>The tool didn't just answer questions; it changed where knowledge lives.</em></p></div><div class='wstep'><p class='nar'><em>The norm that mattered:</em> after one awkward moment (an AI-drafted reply posted verbatim that didn't sound like its «author»), the team adopted the label rule — drafts marked as drafts until a human edits and owns them. <em>Five minutes of norm-setting; permanent removal of the uncanny. Teams that skip this conversation have it later, worse.</em></p></div>"},
  lab: { where: "Slack (workspace with Claude) or M365 — or simulate in the app",
    html: "<p>If your workspace has Claude: @-mention it on a real thread with the catch-up prompt below. If not: paste a real (shareable) thread export into the app and run the same — the skill is identical; the plumbing differs.</p>" + PB("prompt — thread catch-up", "Summarise this thread for someone joining late: (1) DECISIONS made — each with who made it and the message where; (2) OPEN questions, each with who it's waiting on; (3) ACTION items — owner, deadline if stated, UNOWNED flagged loudly; (4) the one thing a new joiner would misunderstand without context. Cite messages for every claim.", "prompt") + "<p>Then draft — but don't send — one in-context reply, and note what you edited before it sounded like you.</p>",
    expect: "A catch-up that would've cost 30 minutes of scrolling, with claims traceable to messages (provenance in team-land), UNOWNED items surfaced (they're always the killers), and a felt sense of the draft-vs-voice gap — which is exactly why the label-your-drafts norm exists." },
  mistakes: [
    "<b>Posting AI drafts verbatim as yourself.</b> The uncanny-voice moment that sours teams on the whole idea. Edit until you own it; label until you have.",
    "<b>Summarising people-sensitive threads without thinking.</b> Permissions allow it; norms should govern it. HR-adjacent content deserves the consent reflex.",
    "<b>Letting the bot make announcements.</b> Answers from AI, announcements from humans — authority and accountability stay with people.",
    "<b>Treating team adoption as a tooling problem.</b> It's a norms problem wearing a tooling costume — the five-minute etiquette conversation IS the deployment.",
    "<b>Forgetting the writing-it-down dividend.</b> The surface rewards documented decisions; teams that keep deciding in DMs get an assistant that knows nothing."
  ],
  quiz: [
    { q: "The deepest change AI-in-team-chat brings:",
      opts: ["Fewer emojis", "Institutional memory becomes queryable — and writing decisions where the AI can see them becomes the team's highest-leverage habit", "Meetings are banned", "Slack gets slower"],
      a: 1,
      why: ["Emoji culture survives intact.", "Correct — retrieval changes incentives: documentation finally pays off same-day. The channel becomes the org's memory, and behaviour follows.", "Meetings shrink and sharpen; they don't vanish.", "Performance is fine; archaeology time collapses."] },
    { q: "«Drafts are labelled until a human owns them» exists because:",
      opts: ["AI drafts are always bad", "Voice and accountability: verbatim-posted AI text creates uncanny authorship, and the room deserves to know who stands behind words", "Labels are fun", "It's a legal requirement everywhere"],
      a: 1,
      why: ["The drafts are often excellent — that's not the issue.", "Correct — teams run on knowing who said what and meant it. The edit-until-you-own-it pass keeps human authorship real; the label covers the gap.", "They're governance, not decoration.", "It's a norm — ahead of most law, which is exactly when norms matter."] },
    { q: "A teammate wants Claude to auto-post weekly status announcements. Per this lesson:",
      opts: ["Great — full automation", "Compile the draft on schedule (5.5), but a human reviews, owns and POSTS it — answers from AI, announcements from humans", "Ban all automation", "Post it anonymously"],
      a: 1,
      why: ["Unattended posting to the whole team crosses the announcement line AND the 5.5 no-unattended-sends law simultaneously.", "Correct — the scheduled-draft + human-dispatch pattern, team edition. All your automation law composes cleanly here.", "The compile step is pure win; only the dispatch needs the human.", "Anonymous announcements are worse, not better."] }
  ],
  prac: [
    { tag: "warm", q: "Draft the 5-line AI etiquette proposal you'd post to your team channel tomorrow.",
      sol: "<b>Example:</b> «Proposing our AI ground rules: (1) @Claude freely for catch-ups and answers; (2) AI drafts labelled until edited-and-owned; (3) people-sensitive threads: ask the thread before summarising; (4) announcements come from humans; (5) decisions get WRITTEN in-channel — if it's not written, our assistant (and future-us) can't find it.» Five lines; most teams adopt them on sight." },
    { tag: "transfer", q: "Run the thread catch-up on your messiest real thread this week, share the summary (labelled!), and note what the UNOWNED-items flag surfaces.",
      sol: "<b>Prediction:</b> at least one action item everyone assumed someone else owned. That surfacing — awkward for a second, valuable forever — is the feature selling itself to your team. The share-with-label move also quietly demos the etiquette." },
    { tag: "stretch", q: "You're advising a 30-person company on rolling Claude into Slack + M365. Sketch the 3-phase rollout: what unlocks when, and the metric per phase.",
      sol: "<b>One sound rollout:</b> Phase 1 — read-and-summarise in two pilot channels + the etiquette norms; metric: catch-up minutes saved (survey). Phase 2 — team knowledge answers + meeting-minutes ritual; metric: «where was that decided?» questions answered by citation. Phase 3 — scheduled compilations (weekly digests, drafted announcements with human dispatch); metric: adoption breadth + one prevented-miscommunication story. Norms travel with each phase. This slide IS a consulting deliverable — 11.2's team-enablement service, and you just designed it." }
  ],
  recap: "Team Claude turns channels into queryable memory — catch up with citations, draft with a human hinge, label until owned, keep announcements human, and set the five norms before you need them.",
  review: "From Lesson 5.5: scheduled-draft-plus-human-dispatch was automation law; today it became social law too. Same hinge, two reasons.",
  bridge: "You've seen all the embedded surfaces. Last stop in Phase C: the decision framework — one page that routes any task to its right surface, and the graduation into the builder phase.",
  deep: "<p><strong>AI as team infrastructure — the organisational-behaviour angle.</strong> Research on transactive memory (who-knows-what systems in teams) says groups perform by maintaining a shared index of expertise and history; the cost of that index — documentation, recaps, onboarding — is why it decays. Queryable channels collapse the maintenance cost: the index builds itself from ambient conversation, IF conversation happens where the system can see it. Predictable second-order effects (already visible in 2026 adopters): decisions migrate toward written channels (the worked example's culture shift); meeting time shifts from recap to genuine deliberation; onboarding compresses (new joiners query the past instead of interviewing it); and a new failure mode appears — <em>false completeness</em>, where «Claude couldn't find it» is mistaken for «it never happened» (DM-decisions become invisible history — norm #5 exists for this). The etiquette floor you drafted isn't politeness; it's governance for a new organ of organisational memory. Teams that name these norms early get the dividends; teams that don't, get the incidents. Being the person who brings the norms — that's a role, and it's hireable (13.1 lists it).</p>"
};

/* ------------------------------------------------ 6.4 */
L["6.4"] = {
  sub: "The surface picker: one decision framework that routes any task to the right Claude — and the graduation exam for the whole power-user phase.",
  breath: "Route by four questions — where does the work live, is it conversation or delegation, is it one-off or recurring, what's the blast radius — and compose surfaces freely: the operator's answer is usually a pipeline, not a place.",
  hook: "<p>You now own seven surfaces, each with its own superpower. Which means you own a new failure mode: the RIGHT tool used in the WRONG place — pasting spreadsheets into chat while the Excel add-in sits installed; running Research when three known sites needed walking; scheduling what needed supervising. This closing lesson compresses Phase C into one routing framework, then examines you on it. Pass, and you're done being a user of Claude. What starts next track is building with it.</p>",
  secs: [
    { h: "The four routing questions",
      b: "<ul><li><strong>1. Where does the work LIVE?</strong> The container decides the surface: repository → Claude Code · workbook → Excel add-in · live web pages → Chrome · your folders → Cowork · team channels → Slack/M365 · your head/one document → the app. (1.4's map, now with reflexes.)</li><li><strong>2. Conversation or delegation?</strong> Am I thinking WITH Claude (iterative, judgment-heavy → chat/app) or handing over an OUTCOME (specifiable, receipt-checkable → Cowork/scheduled)? The 5.1 shift, as a fork.</li><li><strong>3. One-off or recurring?</strong> One-off → do it on the spot. Recurring → template it (3.5) → skill it (4.8) → schedule it (5.5). The staircase IS the routing for anything that repeats.</li><li><strong>4. What's the blast radius?</strong> Reversible → autonomy welcome. Irreversible (sends, deletes, payments, publishes) → human hinge, whatever the surface. The one law that overrides all convenience (5.2, 6.1, 6.3 — thrice-learned, once-stated).</li></ul>"},
    { h: "Composition: the operator's real answer",
      b: "<p>Real tasks route through PIPELINES of surfaces — and you've already seen every pattern:</p><ul><li><strong>Research → app → Cowork:</strong> investigate (4.6) → decide the structure in chat → delegate the document-set build (5.4).</li><li><strong>Chrome → Excel → Slack:</strong> extract the web dashboard (6.1) → model it in the workbook (6.2) → post the summary with citations (6.3).</li><li><strong>Cowork → schedule → team:</strong> prove the report delegation (5.4) → put it on the clock (5.5) → human-dispatch to the channel (6.3).</li><li><strong>Everything → skills:</strong> your procedures (4.8) fire on every surface — the connective tissue that makes seven tools feel like one system.</li></ul><p>The composition habit: <strong>name the pipeline before starting</strong> («this is Chrome-extract → sheet-model → channel-post») — one sentence that prevents the mid-task surface-shuffle where files and context get lost between tools.</p>"},
    { h: "The Phase C exit checklist",
      b: "<p>Honest self-audit — you should now be able to:</p><ul><li>Run the app like an operator: rooms with law (4.2), memory dials set (4.3), files computed-not-eyeballed (4.4), artifacts shipped (4.5), research briefed-and-audited (4.6), connectors scoped (4.7), procedures installed (4.8).</li><li>Manage delegation: outcome specs with quarantines and receipts (5.1–5.3), office artifacts you sign (5.4), automation with honest failure (5.5), an operation with law and rooms (5.6).</li><li>Work embedded: browser with hinges (6.1), grids with citations (6.2), teams with norms (6.3).</li><li>Route and compose all of it on reflex (this lesson).</li></ul><p>Anything unchecked: that lesson's lab is your homework before Track 7. The builder phase assumes ALL of it — Claude Code will feel like Cowork with the guardrails moved, BECAUSE it is.</p>"}
  ],
  worked: { t: "Worked example — one messy Monday, routed end to end",
    html: "<div class='wstep'><p class='nar'><em>The inbox at 9am:</em> (a) boss wants competitive pricing intel by 2pm; (b) the quarterly board workbook needs updating with new actuals; (c) a 70-message thread awaits your opinion; (d) 200 receipts from the conference need expensing; (e) you keep re-explaining your report format to Claude. <em>Watch the routing questions run:</em></p></div><div class='wstep'><p class='nar'>(a) Known competitor sites + deadline → <strong>Chrome extraction</strong> into a table, 30 min, hinges irrelevant (read-only). (b) Lives in a workbook, consequential → <strong>Excel add-in</strong>: update, audit sweep, reconciliation check, YOUR sign-off (blast radius says human signs). (c) Lives in the channel → <strong>thread catch-up</strong> with citations, then a human-owned reply. (d) Folder of files, specifiable outcome, recurring every conference → <strong>Cowork extract</strong> with the 3.3 contract — and note-to-self: template it. (e) Re-explaining twice = the staircase's bell → make it a <strong>skill</strong> tonight, ten minutes.</p></div><div class='wstep'><p class='nar'><em>By 2pm:</em> all five moving or done, and — the real point — <strong>zero surface-fights:</strong> nothing pasted where it shouldn't be, no automation where supervision belonged, every irreversible step behind a human hinge. <em>That's Phase C, complete: not knowing the tools — knowing instantly which tool, composed how, with which safeguards. It looks like calm. It bills like expertise.</em></p></div>"},
  lab: { where: "Everywhere — this is the exam",
    html: "<p>The graduation drill: take your ACTUAL task list for this week (5+ items). For each, write the one-line route: surface(s), conversation-vs-delegation, one-off-vs-staircase, and where the human hinge sits. Then run the two most valuable routes for real. Grade yourself with:</p>" + PB("prompt — the examiner", "Here are this week's tasks and how I routed each across Claude's surfaces (app / Projects / Cowork / scheduled / Chrome / Excel / Slack / skills): [YOUR LIST WITH ROUTES]. Examine my routing like a Claude operations expert: (1) any task on the wrong surface, and why; (2) any missed composition (pipelines I should have chained); (3) any recurring task I failed to push up the template→skill→schedule staircase; (4) any blast-radius/hinge mistakes; (5) my overall grade A–D with the one habit to fix.", "prompt"),
    expect: "A graded audit of your real week. Most first-timers get a B: one wrong-surface call and one staircase miss. Fix those two, and the framework has moved from this page into your hands — which was Phase C's entire purpose." },
  mistakes: [
    "<b>Right tool, wrong place.</b> The Phase C signature error — chat doing what the add-in, extension, or Cowork does natively. The container question exists to kill it.",
    "<b>Delegating judgment; conversing through drudgery.</b> Both misroutes of question 2 — handing Cowork what needed your thinking, or hand-cranking what needed a spec.",
    "<b>Staircase blindness.</b> Doing the same task manually a fourth time. Recurring = climb: template, skill, schedule.",
    "<b>Convenience overriding blast radius.</b> The hinge law bends for nothing — not deadlines, not confidence, not «it worked last time».",
    "<b>Surface-shuffling mid-task.</b> Files and context lost between tools because the pipeline was never named. One sentence upfront; zero orphaned work."
  ],
  quiz: [
    { q: "«Update the client's budget workbook with this month's actuals and flag anomalies» routes to:",
      opts: ["Chat, pasting the numbers", "The Excel add-in — the work lives in a workbook, with citations and change-tracking for the consequential bits, and your sign-off", "Chrome", "A scheduled task immediately"],
      a: 1,
      why: ["Container mismatch — the .xlsx is the deliverable.", "Correct — question 1 (lives in a grid) + question 4 (money = tracked changes + human sign-off). Textbook route.", "No live web pages involved.", "Schedules are earned by proven manual runs (5.5) — prove it first."] },
    { q: "The four routing questions, in essence:",
      opts: ["Price, speed, colour, mood", "Where does it live · conversation or delegation · one-off or recurring · what's the blast radius", "Model, tokens, plan, theme", "There are no questions, just vibes"],
      a: 1,
      why: ["No.", "Correct — container, mode, cadence, consequence. Four questions, every task, forever.", "Those matter downstream; routing comes first.", "Vibes were Phase A you. You've changed."] },
    { q: "You've manually run the same Friday compilation three weeks straight. The framework says:",
      opts: ["Keep going — consistency!", "The staircase: template it now, skill it if it's procedure, schedule it once proven — recurring work climbs or it costs forever", "Stop doing the task", "Complain"],
      a: 1,
      why: ["Consistency of waste is still waste.", "Correct — question 3's whole purpose. Third repetition is the bell; the 2.7→3.5→4.8→5.5 staircase is the answer.", "The task's needed — its manual-ness isn't.", "Understandable; unbillable."] }
  ],
  prac: [
    { tag: "warm", q: "Route these in one line each: (a) «make sense of this 90-page RFP by tomorrow», (b) «our prices vs 4 rivals' sites, weekly», (c) «I think better out loud about this career decision», (d) «60 interview recordings → themed findings doc».",
      sol: "(a) app, long-context canon (3.2) — conversation, one-off, no hinge needed. (b) Chrome extract → proven → scheduled with receipts — recurring, read-only. (c) app conversation, maybe voice — pure thinking-with. (d) Cowork: transform (transcripts) → extract (themes) → 5.4 doc — delegation, receipts, your sign-off. Four tasks, four different shapes: that's the framework working." },
    { tag: "transfer", q: "Run the full lab exam on your real week and implement the examiner's #1 fix. Report the grade honestly somewhere you'll see it next month.",
      sol: "<b>The follow-through:</b> next month, re-run the exam. The A-grade isn't the point — the DELTA is: wrong-surface calls should approach zero, and the staircase should be reflexive. Two exams a month apart is how you verify the framework became a habit rather than a page you read." },
    { tag: "stretch", q: "Write your «Phase C in one page» — the routing framework, the staircase, the hinge law, and your operation's structure — as the brief you'd hand a smart colleague who wants what you now have.",
      sol: "<b>The test of the page:</b> could they route the worked example's Monday correctly using only your page? If yes, you've compressed five tracks into a transferable artifact — which is (a) the best possible revision, (b) proof you own it, and (c) literally a teaching asset: «I onboard teams onto AI operations» starts with this page as the handout (11.2/12.5 will monetise it; 13.3 will portfolio it). Teaching-grade understanding is the exit bar of Phase C — and you just met it." }
  ],
  recap: "Container, mode, cadence, consequence — route every task in one breath, compose pipelines by name, climb the staircase on repetition, and let the hinge law override everything. Phase C: complete.",
  review: "From Lesson 1.4: the map that started as seven unfamiliar names is now seven reflexes and a routing framework. Same territory; you're a different traveller.",
  bridge: "Phase D begins: the builder tracks. First, Claude Code — the agentic workhorse where everything you learned about delegation meets a terminal, a repository, and real engineering power. Non-coders welcome; operators required.",
  deep: "<p><strong>Why routing is the durable skill (a systems argument).</strong> Individual surfaces WILL churn — features migrate (chat grows agentic powers; Cowork grows chat's immediacy), new surfaces appear, boundaries blur. What survives churn is the DECISION STRUCTURE, because its axes are properties of WORK, not of products: where information lives, whether judgment or execution dominates, whether repetition exists, what breaks if it goes wrong. Those four axes predate AI (they're how good managers have always assigned work) and will outlive every current product name — which is why this course taught tools through principles rather than principles through tools. There's also a market read: as AI surfaces multiply across every vendor (2026's explosion is not slowing), the scarce skill visibly shifts from «can use tool X» to «can architect WHICH tools, composed HOW, governed by WHAT» — the routing-and-composition layer. That layer has a job title forming around it (AI operations, AI enablement — 13.1 tracks the listings), a consulting market (11.2), and a teaching market (12.5). You just spent five tracks becoming that layer. Phase D now hands you the power tools; Phase E sends the invoice.</p>"
};

})();
