/* Track 4 — Claude App Mastery (L1→L2) */
(function(){
var L = window.LESSONS;

/* ------------------------------------------------ 4.1 */
L["4.1"] = {
  sub: "Web, desktop, mobile — same Claude, different superpowers. The fifteen-minute tour that most users never take, and the settings that quietly matter.",
  breath: "The Claude app runs on web, desktop and mobile with the same brain but different powers per platform — and ten minutes in Settings (styles, keyboard habits, chat organisation) permanently upgrades every future session.",
  asOf: true,
  hook: "<p>People buy a Swiss Army knife and use the big blade for everything, never discovering the saw, the scissors, or the corkscrew. The Claude app is exactly this. You've been using «the big blade» — the message box — for three tracks. Today we open the rest of the tool: where each platform shines, which settings compound, and the small habits that make daily driving feel telepathic.</p>",
  secs: [
    { h: "Three platforms, three personalities",
      b: "<table><tr><th>Platform</th><th>Where it shines</th><th>Unique powers</th></tr><tr><td><strong>Web (claude.ai)</strong></td><td>The full-featured home</td><td>Everything renders best here: Artifacts, Projects, Research, file previews. Zero install; works on any machine.</td></tr><tr><td><strong>Desktop app</strong> (Mac/Windows)</td><td>Deep work & local reach</td><td>The gateway to Cowork's local-file powers (Track 5), local MCP servers (Track 8), global shortcut to summon Claude, and it keeps sessions a keystroke away all day.</td></tr><tr><td><strong>Mobile (iOS/Android)</strong></td><td>Capture & continue</td><td>Camera as an input device (snap a document, a whiteboard, a broken appliance), voice conversations, and continuing the same chats you started at your desk.</td></tr></table><p>The operator pattern is <strong>continuity</strong>: start research on your phone in a queue, refine it on the web at your desk, hand the files to Cowork via desktop. One account, one history, three entry points.</p>"},
    { h: "The settings ten minutes that pay forever",
      b: "<ul><li><strong>Styles:</strong> the app can apply response styles (concise, explanatory, formal — or custom ones you create from a writing sample). A custom style is a standing system prompt (2.6) wearing a friendly UI — set one up for your default voice.</li><li><strong>Model picker:</strong> now that you speak fluent 1.3, actually use it per task instead of living on the default.</li><li><strong>Feature toggles:</strong> check what's enabled — web search, analysis tool, artifacts. A surprising number of «Claude can't do X» complaints are a toggle someone never opened.</li><li><strong>Keyboard habits (web/desktop):</strong> new chat in one stroke, Shift+Enter for newlines (write multi-paragraph prompts — your 2.1 skeletons deserve line breaks), Edit on your last message to fork a better version instead of appending «no wait, I meant…» (cleaner context — 1.2).</li><li><strong>Chat hygiene:</strong> rename important chats, delete dead ones, use search to resurrect old work. Your history is a knowledge base if you keep it findable — and its best contents should graduate into Projects (next lesson).</li></ul>"},
    { h: "Inputs people forget exist",
      b: "<ul><li><strong>Paste is powerful:</strong> screenshots paste directly into the box (an error dialog, a chart, a WhatsApp thread) — Claude reads images natively (more in 4.4).</li><li><strong>Voice on mobile:</strong> dictation for prompts-while-walking, and full voice conversations where available — thinking out loud with a colleague who never tires.</li><li><strong>Camera as scanner:</strong> a photo of a menu, contract page, or handwritten notes is a legitimate document input. The habit: <em>if your eyes can read it, Claude probably can too.</em></li><li><strong>Edit-and-fork:</strong> editing an earlier message re-runs the conversation from that point — your iteration tool (2.7) for fixing the prompt instead of arguing downstream.</li></ul>"}
  ],
  worked: { t: "Worked example — one errand, three devices",
    html: "<div class='wstep'><p class='nar'><em>The errand:</em> Dev is buying a used car. At the dealer (mobile): photographs the service history booklet page by page, asks «list every service date and what was done; flag gaps longer than a year.» Two gaps found — negotiating ammunition, on the spot.</p></div><div class='wstep'><p class='nar'><em>At home (web):</em> opens the same chat, adds the insurance quote PDF and asks for a total-cost-of-ownership comparison vs a competing car, formatted as a table (2.4). Renames the chat «Car purchase — March» so it's findable.</p></div><div class='wstep'><p class='nar'><em>The habit that made it smooth:</em> nothing clever — just knowing the camera IS a scanner, chats travel across devices, and a renamed chat beats «New conversation (47)». <em>Platform fluency isn't a feature; it's friction removed a hundred times a week.</em></p></div>"},
  lab: { where: "Claude app — all your devices",
    html: "<p>The fifteen-minute tour, for real: (1) Open Settings on your main platform — enable/inspect web search, artifacts, analysis; set or create a Style from a sample of your writing. (2) On mobile: photograph any document near you and ask three questions about it. (3) On web: find that same chat, continue it, then rename it. (4) Practice the fork: edit your earlier message to sharpen the prompt and watch the thread re-run.</p>" + PB("prompt — style test (after setting a custom style)", "Explain compound interest to me in two short paragraphs.", "prompt"),
    expect: "The style test should come back sounding like YOUR default register without you asking. And the camera→web→rename→fork loop should feel effortless — that loop is daily driving." },
  mistakes: [
    "<b>Living on one platform.</b> Web-only users miss local reach and capture; mobile-only users miss Artifacts, Projects and Research depth.",
    "<b>The eternal unnamed chat pile.</b> Six months of «New conversation» is a landfill, not a history. Rename what matters; delete what doesn't.",
    "<b>Appending corrections instead of forking.</b> «No wait, I meant…» ×5 builds sludge (2.7). Edit the original message; keep the desk clean.",
    "<b>Never opening Settings.</b> Half the «missing features» people complain about are toggles, and Styles is a free standing-prompt slot going unused."
  ],
  quiz: [
    { q: "Which platform is the gateway to Cowork's local-file powers and local MCP servers?",
      opts: ["Web only", "The desktop app", "Mobile", "None — those need the API"],
      a: 1,
      why: ["Web runs Cowork sessions in the cloud, but local folder access rides through desktop.", "Correct — desktop is where Claude meets your actual machine: local folders for Cowork (Track 5) and local MCP servers (Track 8).", "Mobile is capture-and-continue, not local reach.", "No API needed — the desktop app is the bridge."] },
    { q: "A custom Style in the app is functionally:",
      opts: ["A font setting", "A standing system prompt (2.6) applied through a friendly UI", "A different model", "A paid add-on"],
      a: 1,
      why: ["It shapes the writing, not the typography.", "Correct — persistent voice/format direction without retyping. Your 2.6 skills, productised by Anthropic.", "Same model; different standing instructions.", "Styles ship with the app."] },
    { q: "You realise your third message asked the wrong thing and the chat has drifted for six turns. The cleanest fix:",
      opts: ["Keep appending corrections", "Edit that third message and fork the conversation from there", "Start screaming in caps", "Delete your account"],
      a: 1,
      why: ["Appending fights sludge with more sludge (2.7).", "Correct — edit-and-fork re-runs from the fixed prompt with a clean downstream context. Iteration surgery, not iteration argument.", "Volume isn't steering (2.2).", "Dramatic."] }
  ],
  prac: [
    { tag: "warm", q: "Name one unique power per platform (web / desktop / mobile) from memory.",
      sol: "Web: full-featured rendering home (Artifacts/Projects/Research). Desktop: local reach (Cowork folders, local MCP, global shortcut). Mobile: capture (camera/voice) + continuity. If you named others that are real — also fine; the point is knowing each door exists." },
    { tag: "transfer", q: "Design your personal «capture pipeline»: what kinds of paper/screens cross your week, and which will you now photograph into Claude instead of retyping?",
      sol: "<b>Common winners:</b> receipts (→ 3.3's extraction contract!), whiteboards after meetings, book pages worth remembering, error screens, business cards, handwritten notes. Pick your top two and do them this week — the camera-as-scanner habit is the single fastest daily-life upgrade in this track." },
    { tag: "stretch", q: "Your chat history has 400 conversations. Design a findability system using only the app's own affordances (rename, delete, search, Projects) — no external tools.",
      sol: "<b>One sound system:</b> rename anything worth keeping with a prefix convention («CLIENT-x…», «LEARN-…», «TEMPLATE-…»); delete disposables weekly; anything referenced twice graduates into a Project (4.2) where it lives with its context; search handles the rest. The deep principle: your history is a knowledge base ONLY if curation is a habit, not an archaeology project." }
  ],
  recap: "Web is the full home, desktop is local reach, mobile is capture — set a Style, fork instead of arguing, rename what matters, and let chats travel with you.",
  review: "From Lesson 2.6: Styles are your standing system prompt wearing product clothes — one more altitude for the same craft.",
  bridge: "The tour showed you the rooms. Now the power feature that changes how you work: Projects — persistent workspaces with their own instructions and knowledge.",
  deep: "<p><strong>Why «the app» is quietly the hardest surface to build.</strong> Chat looks simple, but the 2026 app juggles: model routing, tool orchestration (search, analysis, artifacts firing mid-response), file pipelines, cross-device sync, and safety layers — all behind one text box. Two consequences for you. First, features ship CONSTANTLY; the release-notes habit (support.claude.com keeps them) is how operators stay ahead of «wait, when could it do that?». Second, the app is Anthropic's testbed: capabilities often land here before the API (and vice versa for builder features), so fluency in the app doubles as a preview of what you'll soon automate. The meta-skill of this whole phase: treat the product as a moving frontier you patrol, not a fixed tool you learned once.</p>"
};

/* ------------------------------------------------ 4.2 */
L["4.2"] = {
  sub: "Projects: separate workspaces with their own standing instructions and their own library of knowledge. This is where your craft stops being retyped.",
  breath: "A Project bundles custom instructions (a standing system prompt) with uploaded knowledge (documents Claude consults in every chat inside it) — build one per client, per domain, per recurring job, and your context stops evaporating.",
  hook: "<p>Imagine hiring a brilliant assistant who forgets your company, your voice, and your files every single morning. That's Claude without Projects — and it's how most people use it forever, re-explaining themselves in every chat like a time-loop movie. Projects break the loop: rooms where the briefing is done ONCE, the reference shelf stays stocked, and every conversation starts already-briefed. If Track 2 taught you what to say, Projects make sure you never say it twice.</p>",
  secs: [
    { h: "The two organs of a Project",
      b: "<ul><li><strong>Custom instructions</strong> — the Project's standing system prompt (2.6, now with a permanent home): who Claude is here, the voice, the rules, the formats. Written once, governing every chat inside.</li><li><strong>Knowledge</strong> — files you upload to the Project itself: brand guides, price lists, past work, templates (3.5!), policies. Claude consults them across all the Project's chats — your reference shelf, always in reach.</li></ul><p>Together they create <strong>compounding context</strong>: each chat starts where your best-briefed chat would have started. And chats inside stay organised under the Project — findability solved for free (4.1's landfill problem, structurally fixed).</p>"},
    { h: "What deserves a Project (and what doesn't)",
      b: "<p>The admission test: <strong>will I have five or more conversations sharing the same context?</strong></p><ul><li><strong>Per client</strong> — instructions carry their voice and boundaries; knowledge carries their briefs, past deliverables, price list. (The Track 11 freelancer's backbone.)</li><li><strong>Per recurring job</strong> — «Weekly report», «Hiring», «Content pipeline»: instructions carry the format contracts (2.4), knowledge carries the templates and examples.</li><li><strong>Per domain of life</strong> — «My finances», «Kid's school», «Learning Claude» (yes, make one for this course — knowledge: your notes; instructions: your level and goals).</li><li><strong>The Prompt Library Project</strong> (3.5's endgame): knowledge = your template file; instructions = «when I name a template, fetch it from knowledge, ask for the slot values, then run it.» Your toolchest, self-serving.</li></ul><p><strong>Not</strong> Project-worthy: one-off questions, disposable tasks — a Project per errand is bureaucracy. And know the escalation path: when a Project's instructions grow procedural («always do X then Y with files like this»), that's a Skill trying to be born (4.8).</p>"},
    { h: "Writing instructions that age well",
      b: "<ul><li><strong>Stable facts only.</strong> Instructions are the constitution; today's task never goes in it (2.6's law). If you edit instructions weekly, something belongs in knowledge or in chats instead.</li><li><strong>Reference the knowledge explicitly:</strong> «pricing questions: answer ONLY from pricelist.pdf; if absent, say so» — grounding rules (3.4) pointed at the shelf.</li><li><strong>Carry your truth rules:</strong> the three standing truth-rules you wrote in 3.4's practice belong in every serious Project's instructions.</li><li><strong>Maintain like a template:</strong> when you correct Claude the same way twice inside a Project, the correction graduates into the instructions (2.7's post-mortem, aimed at the room)."+"</li></ul>"}
  ],
  worked: { t: "Worked example — the freelancer's three-room setup",
    html: "<div class='wstep'><p class='nar'><em>Priya, freelance content marketer, three retainer clients.</em> Before Projects: every draft began with five minutes of re-pasting brand voice notes, and one near-disaster — client A's casual tone in client B's formal newsletter. <em>The fix: one room per client.</em></p></div><div class='wstep'><p class='nar'><em>Room «Client A — D2C skincare»:</em> instructions — voice rules (playful, no medical claims — a compliance line her contract requires), formats for their three deliverable types, the truth rule «product claims only from ingredients.pdf». Knowledge — brand guide, five best past posts (few-shot by shelf — 2.3 at the room level), the ingredients sheet, the content calendar.</p></div><div class='wstep'><p class='nar'><em>The payoff, measured:</em> drafts start on-voice (no re-briefing), the wrong-client-tone accident is structurally impossible (rooms don't leak), and onboarding her new subcontractor took one sentence: «work inside the client's Project.» <em>The room IS the briefing.</em> Note the ladder she climbed: 2.6 wrote the prompt, 3.5 templated it, 4.2 gave it a house.</p></div>"},
  lab: { where: "claude.ai — Projects (paid feature; free tier may limit)",
    html: "<p>Build your highest-value Project right now. Pick the context you re-explain most often (a client, your business, this course). Create the Project, then draft its constitution with Claude's help:</p>" + PB("prompt — inside the new Project's first chat", "Help me write this Project's custom instructions. The Project is for: [PURPOSE]. Interview me briefly: (1) what should Claude know that never changes here, (2) voice/format rules, (3) what documents I should upload as knowledge and what each is FOR, (4) my standing truth rules. Then output instructions under 250 words with sections: ROLE / CONTEXT / RULES / KNOWLEDGE MAP — where KNOWLEDGE MAP says which uploaded file answers which kind of question.", "prompt") + "<p>Paste the result into the Project's custom instructions, upload the 2–4 files it named, then test: ask a typical question in a fresh Project chat with zero extra context.</p>",
    expect: "The test answer should arrive pre-briefed — right voice, right facts, citing the right knowledge file. If it missed something, that something belongs in the instructions or the shelf: patch, don't re-explain." },
  mistakes: [
    "<b>One mega-Project for everything.</b> «My stuff» with 40 unrelated files re-creates the crowded desk (1.2) with extra steps. Rooms work because they're SEPARATE.",
    "<b>Instructions that are really tasks.</b> «Write this week's newsletter» in the constitution means editing it every week. Stable facts up top; work in the chats.",
    "<b>A stale shelf.</b> Last year's price list in knowledge is worse than none — wrong answers with confident grounding. Date your files; refresh on a schedule.",
    "<b>Shelf-stuffing.</b> Knowledge is curated reference, not a dumping ground — irrelevant files dilute retrieval exactly like irrelevant context (1.2, 3.2).",
    "<b>Never graduating corrections.</b> Fixing the same mistake in six chats while the instructions stay unchanged — the room should learn (2.7's principle, structural edition)."
  ],
  quiz: [
    { q: "The two organs of a Project are:",
      opts: ["Themes and fonts", "Custom instructions (standing system prompt) and knowledge (a persistent reference shelf of files)", "Bookmarks and history", "Models and styles"],
      a: 1,
      why: ["Cosmetics live elsewhere.", "Correct — the constitution plus the shelf: briefing once, reference always. Everything else about Projects follows from these two.", "Organisation is a side benefit; the organs are instructions + knowledge.", "You can pick models per chat anywhere; the Project's essence is persistent context."] },
    { q: "Which is Project-worthy by the admission test?",
      opts: ["«What's the capital of Mongolia?»", "A client you'll serve weekly for a year", "Renaming one file", "A joke you want to hear once"],
      a: 1,
      why: ["One-off — just ask.", "Correct — dozens of future conversations sharing voice, files and rules: the exact shape Projects exist for.", "Disposable.", "Enjoy it Project-free."] },
    { q: "Your Project keeps answering pricing questions from memory instead of the uploaded price list. The professional fix:",
      opts: ["Upload the price list five more times", "Add a grounding rule to the instructions: «pricing answers ONLY from pricelist.pdf, quote the line; if absent, say so»", "Stop using Projects", "Ask more politely"],
      a: 1,
      why: ["Duplication isn't direction.", "Correct — 3.4's grounding layer, installed in the constitution: name the file, demand the quote, allow the honest gap.", "The feature is fine; the instructions were silent on sourcing.", "Politeness isn't provenance (2.2)."] }
  ],
  prac: [
    { tag: "warm", q: "List the 3 Projects YOUR life most obviously wants, and for each: two lines of instructions-worthy facts + the 3 knowledge files.",
      sol: "<b>Match against the archetypes:</b> per-client / per-recurring-job / per-domain. Each instruction line should be STABLE (true next month); each file should answer a category of question. If a «file» you listed changes weekly, plan its refresh ritual now." },
    { tag: "transfer", q: "Build the Prompt Library Project from 3.5's endgame: upload your template file as knowledge, write the fetch-and-fill instructions, and run one template through it by name.",
      sol: "<b>Success bar:</b> saying «run my minutes template on this transcript» fetches the right template, asks for missing slot values, and executes — no pasting. You've turned your library from a place you visit into a service you invoke. (In 4.8, Skills make even the invoking automatic.)" },
    { tag: "stretch", q: "A 6-person team wants shared Projects for their agency's five clients. Design the governance: who edits instructions, how knowledge stays fresh, and what NEVER goes in a shared room.",
      sol: "<b>One workable design:</b> each client-room has an owner (edits instructions, bumps a version line at the top); knowledge refresh is a named weekly ritual (stale files deleted, not buried); corrections graduate via the owner (3.5's library governance, roomified). NEVER in shared rooms: credentials/secrets, one member's personal drafts, and anything the client hasn't cleared for team visibility. Shared context is leverage; shared sloppiness is contamination at team scale." }
  ],
  recap: "One room per recurring context: constitution (stable instructions + truth rules) plus shelf (curated, dated knowledge) — brief once, compound forever, and graduate repeated corrections into the room itself.",
  review: "From Lesson 3.5: templates wanted a home with a librarian — the Prompt Library Project is that home, and 4.8's Skills will be the librarian.",
  bridge: "Projects remember by design. Next: what Claude remembers on its own — the memory features, their controls, and the operator's stance on letting an AI keep notes about you.",
  deep: "<p><strong>How does Project knowledge actually reach the model?</strong> Two mechanisms, blended by size. Small shelves ride directly in context — your files are simply THERE (the 1.2 desk, pre-loaded). Larger shelves get retrieved: the app searches your knowledge for chunks relevant to the current message and surfaces those — which is RAG (retrieval-augmented generation) quietly running under a consumer feature, the same architecture you'll meet as an engineering pattern in Track 9. Practical consequences you can feel: retrieval favours well-titled, well-structured documents (headings help the search the way they help humans); one 400-page dump retrieves worse than eight focused files (curation IS retrieval engineering); and grounding rules in instructions («answer from X, quote it») sharpen what retrieval returns into what answers cite. When a client later asks you «should we build RAG or just use big context?», you'll realise you've been A/B testing the answer inside your own Projects all along.</p>"
};

/* ------------------------------------------------ 4.3 */
L["4.3"] = {
  sub: "Claude can now remember you between chats. That's genuinely useful and worth understanding precisely — what's kept, where it lives, and which dials are yours.",
  breath: "Memory lets Claude carry facts and preferences across conversations — separate from Projects' curated context — with user controls to view, edit, disable, or go incognito; operators treat it as a convenience layer, never the system of record.",
  asOf: true,
  hook: "<p>For years, «Claude forgets everything between chats» was the rule — annoying, but wonderfully predictable. Modern Claude remembers: your preferences, your ongoing work, facts you've shared. Handy — and worth a moment of adult thought: an assistant that remembers is an assistant with a file on you. This lesson is the precise tour: what memory is, what it is NOT (Projects, context), and how operators set the dials deliberately instead of by default.</p>",
  secs: [
    { h: "The three layers people confuse",
      b: "<table><tr><th>Layer</th><th>Lifespan</th><th>You met it in</th></tr><tr><td><strong>Context window</strong></td><td>One conversation — the desk, wiped between chats</td><td>1.2</td></tr><tr><td><strong>Project knowledge + instructions</strong></td><td>Curated by YOU, per room, until you change it</td><td>4.2</td></tr><tr><td><strong>Memory</strong></td><td>Accumulated by CLAUDE across chats — preferences, recurring facts, ongoing projects</td><td>this lesson</td></tr></table><p>The critical distinction: Projects are <em>deliberate</em> context (you chose every file); memory is <em>gathered</em> context (noticed along the way). Both useful; different trust levels. As of July 2026, memory can also be scoped per-Project on paid plans — client A's remembered details staying inside client A's room is exactly the leak-prevention you'd hope for (4.2's rooms extend to remembered facts).</p>"},
    { h: "The dials you own",
      b: "<ul><li><strong>See it:</strong> Settings exposes what Claude has remembered — as editable summaries. Read yours; it's an odd and useful mirror.</li><li><strong>Edit/delete:</strong> remove single memories or wipe all. Wrong remembered facts are worse than none (a stale «user prefers formal tone» quietly mis-steers every chat — 4.2's stale-shelf problem, auto-generated).</li><li><strong>Steer it in-chat:</strong> «Remember that I…» and «Forget what I said about…» work as first-class commands. Memory takes dictation.</li><li><strong>Go incognito:</strong> chats that don't read or write memory — for sensitive topics, one-off weirdness, or testing how Claude behaves un-briefed (useful for your 3.6 evals: memory OFF for reproducibility).</li><li><strong>Kill switch:</strong> disable memory entirely and live on context + Projects alone — a legitimate professional configuration, not paranoia.</li></ul>"},
    { h: "The operator's memory policy",
      b: "<ul><li><strong>Convenience layer, not system of record.</strong> Anything that MUST be right (client facts, prices, policies) lives in Project knowledge where you version it — memory is for greases-the-wheels preferences («metric units», «I'm in Hyderabad», «bullet-point summaries»).</li><li><strong>Deliberate deposits:</strong> end useful sessions with «remember these two things: …» — curated memory beats ambient memory.</li><li><strong>Quarterly audit:</strong> skim the memory page, delete the stale, correct the wrong. Five minutes; prevents a drip of subtle mis-steering.</li><li><strong>Sensitive-by-default rule:</strong> health, finances, other people's private details — incognito unless you have a reason. Not because anything's wrong; because «minimum necessary» is what professional data-handling looks like, and YOU are now a professional (clients will one day ask you their version of this question — Track 11.7)."+"</li></ul>"}
  ],
  worked: { t: "Worked example — the memory audit that explained a mystery",
    html: "<div class='wstep'><p class='nar'><em>The mystery:</em> Arjun notices Claude keeps making his drafts oddly formal, chat after chat, despite his casual style requests. <em>Old habit would be:</em> grumble and re-correct forever. Operator habit: check the layers — context is fresh (new chats), no Project active… so, memory.</p></div><div class='wstep'><p class='nar'><em>The audit:</em> Settings → memory. There it is: months ago, while drafting legal replies for a dispute, he'd said «always keep my drafts formal» — and memory faithfully kept it. One stale deposit, quietly mis-steering everything since. He deletes it, adds a deliberate one: «default tone casual-professional; formal only when I say so.»</p></div><div class='wstep'><p class='nar'><em>The takeaway he wrote down:</em> memory failures look exactly like model failures — check the file before blaming the brain. And the flip side the same week: «remember my daughter's school schedule» now saves him re-typing it into every planning chat. <em>Same feature; the dials made it an asset.</em></p></div>"},
  lab: { where: "Claude app — Settings → Memory",
    html: "<p>Run your first memory audit + deliberate deposit: (1) Open memory settings and READ what's there. Delete anything stale or wrong. (2) In a chat, make two deliberate deposits:</p>" + PB("prompt", "Remember these two things about me: (1) [A STABLE PREFERENCE — e.g., 'I prefer answers with concrete numbers over general advice']. (2) [A STABLE FACT — e.g., 'I'm building a freelance business around Claude skills']. Confirm what you've stored, in your words.", "prompt") + "<p>(3) Open a FRESH chat and ask for advice on something related — watch the deposits steer it. (4) Try one incognito chat and feel the difference.</p>",
    expect: "The fresh chat should reflect your deposits without you restating them; the incognito chat should not. You now know exactly where the remember/forget dials live — most users never find them." },
  mistakes: [
    "<b>Confusing memory with Projects.</b> Putting must-be-right facts in ambient memory instead of versioned knowledge — then wondering why an old preference overrode a new price list.",
    "<b>Never reading the memory page.</b> Stale deposits mis-steer silently for months (formal-tone ghosts, old jobs, finished projects).",
    "<b>Blaming the model for memory artifacts.</b> Persistent odd behaviour across fresh chats = check the file first.",
    "<b>All-or-nothing thinking.</b> The choice isn't «memory on and forget about it» vs «off forever» — incognito, per-memory deletion and deliberate deposits are the professional middle.",
    "<b>Sensitive material by default.</b> Other people's private details in ambient memory is a habit to consciously decline — minimum necessary, always."
  ],
  quiz: [
    { q: "The essential difference between Project knowledge and memory:",
      opts: ["Knowledge is free, memory is paid", "Knowledge is deliberately curated by you per room; memory is gathered by Claude across chats — different trust levels, different jobs", "They're identical", "Memory is larger"],
      a: 1,
      why: ["Plan details vary; that's not the distinction.", "Correct — chosen-and-versioned vs noticed-along-the-way. Must-be-right facts go where YOU control the file.", "Confusing them is this lesson's #1 named mistake.", "Size isn't the axis; provenance and control are."] },
    { q: "Claude behaves oddly the same way across multiple FRESH chats. First diagnostic stop:",
      opts: ["The model is broken", "Your memory page — a stale or wrong deposit steers every chat", "Your internet connection", "The moon phase"],
      a: 1,
      why: ["Cross-chat persistence with fresh contexts points at the persistent layer.", "Correct — memory failures impersonate model failures; audit the file before blaming the brain.", "Connectivity doesn't shape tone.", "Tempting some weeks, but no."] },
    { q: "The operator's rule for what belongs in memory vs Project knowledge:",
      opts: ["Everything in memory — it's automatic", "Preferences and greases-the-wheels facts in memory; must-be-right, versioned material in Project knowledge", "Nothing anywhere — write it all fresh daily", "Only jokes"],
      a: 1,
      why: ["Automatic is exactly why it's the wrong home for critical facts.", "Correct — convenience layer vs system of record. One sentence, whole lesson.", "That's pre-4.2 living; you've graduated.", "Claude does remember good jokes, but no."] }
  ],
  prac: [
    { tag: "warm", q: "Sort into memory / Project knowledge / neither: (a) «prefers concise answers», (b) client's current price list, (c) your one-off question about visa rules, (d) «works in IST timezone», (e) brand voice guide.",
      sol: "(a) memory (b) <b>knowledge</b> — must-be-right, versioned (c) neither — disposable (d) memory (e) <b>knowledge</b> — it's the constitution's reference material. The sorting reflex is the lesson." },
    { tag: "transfer", q: "Write your personal memory policy in 4 lines: what you deposit deliberately, what stays incognito, audit cadence, and the one rule about other people's information.",
      sol: "<b>Example:</b> «Deposit: stable preferences + active-goal one-liners, stated explicitly. Incognito: health, money specifics, anything I wouldn't put in an email. Audit: first Sunday monthly, 5 minutes. Others' info: never in ambient memory — clients live in their Projects only.» Pin it; this is also a dry-run for the client-data policies you'll write in 11.7." },
    { tag: "stretch", q: "Design the memory setup for a freelancer with 4 clients: what's global memory, what's per-Project, and how do you demonstrate the separation to a privacy-conscious client?",
      sol: "<b>One clean design:</b> global memory holds only YOUR preferences (formats, tone, schedule); each client's facts live in their Project (knowledge + per-Project memory where available); sensitive exploratory work runs incognito. <b>The demonstration:</b> show the client their Project's contents and your memory page — «here is everything the system holds about you, and here is that it doesn't leak into my other rooms.» Being ABLE to give that tour is a trust asset competitors can't fake — and yes, it's a selling point (Track 11.7 makes it a checklist)." }
  ],
  recap: "Three layers — desk (context), shelf (Projects), file (memory): keep must-be-right facts on the shelf, make deposits deliberate, audit quarterly, and use incognito like a professional uses discretion.",
  review: "From Lesson 1.2: «Claude has no memory between chats by default» got its 2026 asterisk — the physics didn't change; a new persistent layer arrived with dials attached.",
  bridge: "Claude remembers; now let's make it SEE and COMPUTE — files, images, and the analysis tool that runs real code on your data.",
  deep: "<p><strong>How does memory actually work under the hood?</strong> The naive design — stuff every past chat into context — dies instantly on the 1.2 physics (millions of tokens, mostly irrelevant). Real memory systems distil: models extract candidate facts/preferences from conversations, store them compactly (summaries, structured entries), then INJECT relevant ones into future contexts — a write-time summarisation + read-time retrieval architecture. Knowing this explains the observed quirks: memory is <em>lossy</em> (it kept the gist «formal drafts», not the dispute-context that justified it — exactly Arjun's bug); it's <em>selective</em> (not everything you say is deposited — explicit «remember this» beats hoping); and it's <em>injected</em>, meaning remembered facts occupy desk space like any context (another reason curation beats accumulation). The same architecture — extract, store, retrieve, inject — is what you'll build FOR agents in Track 10 (Managed Agents ship memory stores as a feature), and the failure modes you just learned to audit are the ones you'll engineer against. Your Settings page is a working scale model of agentic memory design.</p>"
};

/* ------------------------------------------------ 4.4 */
L["4.4"] = {
  sub: "PDFs, images, spreadsheets, screenshots — and the analysis tool that writes real code to compute real answers. Claude's senses, and when to trust each one.",
  breath: "Claude reads documents and images natively and can run actual code on your data files via the analysis tool — the operator's rule: eyes for reading and judgment, code for counting and math.",
  asOf: true,
  hook: "<p>Ask a brilliant literature professor to eyeball a 5,000-row spreadsheet and estimate the average — you'll get a thoughtful, wrong number. Hand the same professor a calculator and the right answer appears. Claude is that professor: phenomenal reader, unreliable eyeball-counter — UNLESS it reaches for its calculator, which it has: the analysis tool, which writes and runs real code on your files. Knowing which sense to invoke — reading vs computing — is this lesson's entire game.</p>",
  secs: [
    { h: "What Claude can take in",
      b: "<ul><li><strong>Documents:</strong> PDFs (including scanned ones — it reads page images), Word files, text, markdown, code files. Long docs ride the 1.2/3.2 physics you already master.</li><li><strong>Images:</strong> photos, screenshots, charts, diagrams, whiteboards, handwriting. Real vision — it reads the chart's axes, the error dialog's text, the handwriting's content (4.1's camera-as-scanner, formally blessed).</li><li><strong>Data files:</strong> CSVs and spreadsheets — where the professor/calculator split becomes critical.</li><li><strong>Limits exist</strong> (file size, page counts, images per chat) and shift with plans and releases — when you hit one, the workaround is usually 3.1 thinking: split, summarise per part, synthesise.</li></ul>"},
    { h: "The analysis tool: Claude's calculator",
      b: "<p>When enabled, Claude can write and execute code (JavaScript in the app's sandbox) against your uploaded files — actually computing sums, averages, joins, filters, charts — and then explain the results. The difference is not cosmetic:</p><table><tr><th>Question</th><th>Eyes (reading)</th><th>Code (analysis)</th></tr><tr><td>«What does this contract say about termination?»</td><td>✔ perfect fit</td><td>overkill</td></tr><tr><td>«What's the average order value in this CSV?»</td><td>❌ plausible guess</td><td>✔ computed fact</td></tr><tr><td>«Summarise the tone of these reviews»</td><td>✔ judgment task</td><td>can count, can't feel</td></tr><tr><td>«Which month had the most refunds, and by how much?»</td><td>❌ hallucination bait</td><td>✔ groupby + arithmetic</td></tr></table><p><strong>The operator's law: numbers about your data come from code, not from reading.</strong> The magic phrase when it matters: «use the analysis tool / compute this with code, and show the code.» Seeing the code is your 1.6 verification path — you (or a fresh chat) can check the logic.</p>"},
    { h: "Files out, not just in",
      b: "<p>Claude also CREATES files — formatted documents, spreadsheets, presentations — downloadable from the chat. The workflow shape that unlocks: messy input file → analysis → clean deliverable file, all in one conversation. (At Cowork altitude this becomes folder-scale — Track 5; the chat version is your training wheels and often all you need.)</p><div class='callout tip'><b>The screenshot super-habit:</b> any time something on screen confuses you — an error, a chart, a form, a setting — screenshot it into Claude with «what am I looking at and what should I do?». It's the highest-frequency vision use in real life, and it works far more often than people expect.</div>"}
  ],
  worked: { t: "Worked example — the sales CSV, done honestly",
    html: "<div class='wstep'><p class='nar'><em>The file:</em> 3,800 rows of order data. <em>The naive ask:</em> «analyse my sales» — which invites eyeballed vibes. The operator ask, in layers: «Using the analysis tool (show your code): 1) monthly revenue and order count; 2) top 10 SKUs by revenue; 3) refund rate by month; 4) anything anomalous, with the computation that found it.»</p></div><div class='wstep'><p class='nar'><em>What comes back:</em> code + computed tables + one anomaly — March refunds 3× baseline. Now the LAYER SWITCH: «read the refund reasons for March and characterise them» — a judgment task, eyes' territory. The reasons cluster on one courier. <em>Compute found the spike; reading explained it.</em></p></div><div class='wstep'><p class='nar'><em>The verification beat (1.6, always):</em> I spot-check one number — March revenue — against the raw file with a filter. Matches. Then: «create a one-page summary document with the three tables and the courier finding» — file out, ready for the Monday meeting. <em>One chat: file in, truth computed, judgment applied, deliverable out.</em></p></div>"},
  lab: { where: "claude.ai — attach a real file",
    html: "<p>Bring a real data file (bank statement export, sales sheet, expense CSV — anything with 100+ rows). Run the two-sense drill:</p>" + PB("prompt — compute first", "Using the analysis tool — write and show the code: (1) total and monthly breakdown of [YOUR AMOUNT COLUMN]; (2) top 5 categories/payees by total; (3) the single most unusual row by amount, with why it's an outlier statistically.", "prompt") + PB("prompt — then judge", "Now a reading task: looking at the categories and patterns above, what are 3 observations a thoughtful advisor would make about this data, and one question they'd ask me? No new numbers — only ones already computed.", "prompt"),
    expect: "Computed numbers with visible code (spot-check one against your file), then judgment explicitly built on those numbers — «no new numbers» keeps the professor honest. This two-step is THE pattern for every data task you'll ever run." },
  mistakes: [
    "<b>Eyeballed statistics.</b> Asking «what's the average» about an attached sheet without invoking code — fluent, plausible, unverified (1.6's exact trap, data edition).",
    "<b>Never saying «show the code».</b> The code is your audit trail; invisible computation is just better-dressed vibes.",
    "<b>Judgment tasks sent to the calculator.</b> «Compute the tone of these reviews» — counting word frequencies isn't reading the room. Eyes for meaning, code for math.",
    "<b>Re-uploading instead of re-using.</b> The file persists in the chat (desk physics, 1.2) — keep querying it; new upload = new desk rent.",
    "<b>Trusting a chart you didn't sanity-check.</b> Generated charts inherit any code mistake upstream — one spot-check of the underlying number per deliverable, minimum."
  ],
  quiz: [
    { q: "«What's the median deal size in this attached CSV?» — the professional move:",
      opts: ["Let Claude read the file and estimate", "Demand the analysis tool with visible code — numbers about your data come from computation", "Guess yourself, faster", "Ask three times and average the answers"],
      a: 1,
      why: ["Reading estimates numeric aggregates — that's hallucination bait with a spreadsheet attached.", "Correct — the professor picks up the calculator, and the shown code is your verification path.", "Your eyeball has the same problem.", "Averaging guesses launders them; it doesn't verify them (same fallacy as 1.6's re-roll consensus)."] },
    { q: "Which task belongs to EYES, not code?",
      opts: ["Refund rate by month", "Sum of column D", "«Do these customer complaints suggest anger or confusion?»", "Top 10 rows by value"],
      a: 2,
      why: ["Arithmetic — code.", "Arithmetic — code.", "Correct — tone and meaning are judgment tasks; the calculator can count words but can't feel the room.", "Sorting — code."] },
    { q: "The screenshot super-habit is:",
      opts: ["Screenshotting Claude's answers for Instagram", "Feeding anything confusing on your screen to Claude with «what am I looking at and what should I do?»", "Never using images", "Only for developers"],
      a: 1,
      why: ["Share if you like, but that's not the habit.", "Correct — the highest-frequency vision use in daily life: errors, charts, forms, settings. If your eyes can read it, Claude probably can.", "Vision is half the senses; use it.", "Error dialogs afflict everyone equally."] }
  ],
  prac: [
    { tag: "warm", q: "Sort into eyes / code / both-in-sequence: (a) «is this lease clause unusual?», (b) «monthly burn rate from this statement», (c) «why did Q3 costs spike?» with a cost CSV attached.",
      sol: "(a) eyes — reading + judgment (b) code — arithmetic (c) <b>both-in-sequence</b> — code finds WHERE the spike is, eyes read the line items to explain WHY. The sequence answer is the mature one; most real questions are (c)-shaped." },
    { tag: "transfer", q: "Take a recurring number-question from your life («where does my money go?», «which product sells best?») and build its reusable two-step prompt (compute-with-code → judge-on-computed). Add it to your template library (3.5).",
      sol: "<b>Template shape:</b> Step 1 fixed computations with show-the-code; Step 2 judgment with the no-new-numbers rule; slots for {FILE} and {PERIOD}. Congratulations — you own a personal analyst you can invoke monthly. (Cowork will run it on a schedule in 5.5.)" },
    { tag: "stretch", q: "A colleague presents Claude-made charts to management monthly and has never once verified a number. Write the 3-line policy you'd propose, balancing speed against the real risk.",
      sol: "<b>Example policy:</b> «(1) Every deliverable chart: one underlying number spot-checked against source. (2) All aggregates computed via analysis tool with code retained in the chat. (3) Any number that drives a decision >₹X: second computation in a fresh chat (3.4's critic, numeric edition).» Cost: ~5 minutes/month. Value: never explaining to management why the chart was wrong. This is 1.6's triage priced for data work — and it's the difference between «uses AI» and «runs an auditable AI process», which is precisely what Track 11 clients pay extra for." }
  ],
  recap: "Eyes for reading and judgment, code for counting and math — demand the analysis tool with visible code for any number about your data, spot-check one figure per deliverable, and screenshot anything confusing.",
  review: "From Lesson 1.6: «fluent confidence is not evidence» — the analysis tool is what turning that principle into workflow looks like when the subject is your spreadsheet.",
  bridge: "Claude can read, remember, and compute. Now the showstopper: Artifacts — where a sentence becomes a working document, app, or game you can see, use, and share.",
  deep: "<p><strong>Why can't the model just count?</strong> Because it reads tokens, not cells. A 3,800-row CSV becomes a token stream; aggregating it mentally means simulating arithmetic across thousands of positions — possible-ish for tiny tables, unreliable at scale, catastrophically fluent when wrong. Tool use (Track 9's foundation, met here as a product feature) is the architectural answer the whole industry converged on: let the model DECIDE and DELEGATE — write code, call the calculator, query the database — then interpret results. The division of labour is deep: models supply intent and interpretation; deterministic tools supply ground truth. You'll meet this same pattern as: web search (facts), analysis (numbers), Claude Code running tests (correctness), agents calling APIs (actions). One frontier note: 2026 models are notably better at KNOWING when to reach for the tool unprompted — but «show the code» remains your audit right, because the interpretation layer (the professor explaining the printout) is still generative, still 1.6 territory. Tools ground the numbers; your verification grounds the story told about them.</p>"
};

/* ------------------------------------------------ 4.5 */
L["4.5"] = {
  sub: "Artifacts: the moment Claude stops describing work and starts handing it to you — documents, dashboards, apps and games, live in a side panel, shareable with a link.",
  breath: "Artifacts are real, usable outputs — documents, code, diagrams, interactive web apps — rendered beside the chat, iterated conversationally, and publishable; AI-powered artifacts can even call Claude from inside themselves.",
  asOf: true,
  hook: "<p>There's a moment that converts every Claude skeptic: they ask for something — a calculator for their freelance rates, a quiz for their students, a dashboard for their team — and instead of an explanation OF the thing, the thing itself appears. Running. Clickable. Theirs. That's Artifacts: the gap between «describe» and «build» collapsing to zero. For non-programmers it's the first taste of shipping software; for operators it's a prototyping engine that costs a sentence.</p>",
  secs: [
    { h: "What artifacts are (and when they appear)",
      b: "<p>An artifact is substantial, standalone output rendered in its own panel beside the conversation — editable, versioned, downloadable. The species:</p><ul><li><strong>Documents:</strong> reports, guides, policies — living drafts you iterate on conversationally instead of regenerating in-chat.</li><li><strong>Code:</strong> scripts and files with syntax highlighting, ready to copy into your world.</li><li><strong>Diagrams:</strong> flowcharts, org charts, timelines — visual thinking on demand.</li><li><strong>Interactive web apps & games:</strong> the headliner — working HTML/JavaScript/React: calculators, trackers, quizzes, dashboards, tools. Claude writes the code; the panel runs it; you use it immediately.</li></ul><p>They appear automatically for substantial outputs, or on request: «make this an artifact». The iteration loop is conversational — «make the buttons bigger», «add a reset», «dark theme» — and versions let you step back when an edit goes sideways (2.7's iteration, now with an undo).</p>"},
    { h: "AI-powered artifacts: apps with a brain",
      b: "<p>The 2026-era leap: artifacts can <strong>call Claude from inside themselves</strong>. That means the thing you build isn't limited to fixed logic — it can think:</p><ul><li>A flashcard app that GENERATES new questions on your weak topics.</li><li>A customer-reply trainer that role-plays the angry customer and critiques your answer.</li><li>An intake form that reads the user's free-text answer and routes them.</li></ul><p>When someone uses your shared AI-artifact, their usage bills to THEIR Claude account, not yours — which makes sharing safe: you built the tool; each user brings their own brain. Let that sink in: <strong>you can now build and distribute small AI apps with zero code, zero servers, zero API keys.</strong> (It's also the gentlest possible on-ramp to Track 9, where you'll build the grown-up version with the actual API.)</p>"},
    { h: "Publishing, and what artifacts are NOT",
      b: "<ul><li><strong>Share/publish:</strong> an artifact can be published to a link anyone can open — instant distribution for your calculator, guide, or tool. Remixing lets others build on it.</li><li><strong>Honest limits:</strong> artifacts are single-page, sandboxed things — no databases (state resets), no server backends, limited external calls. A calculator, quiz, dashboard, or game: perfect. A multi-user app with accounts and persistence: that's real software — Claude Code (Track 7) and the API (Track 9) territory.</li><li><strong>The strategic frame:</strong> artifacts are for PROTOTYPES, personal tools, teaching aids, and client demos. «Ship the idea in an hour, validate, THEN decide if it deserves real engineering» — that sequencing is a money skill (12.1 will lean on it hard).</li></ul>"}
  ],
  worked: { t: "Worked example — the tuition centre's quiz app, sentence to shipped",
    html: "<div class='wstep'><p class='nar'><em>Meera again (2.6's tuition centre).</em> Wish: weekly practice quizzes for students, per chapter, self-checking. Old cost: an evening per quiz in Google Forms. <em>The ask:</em> «Build an artifact: a quiz app for Class 8 maths, chapter Linear Equations. 10 questions, one at a time, instant feedback with a one-line explanation, score at the end, Try Again button. Cheerful, phone-friendly.»</p></div><div class='wstep'><p class='nar'><em>Ninety seconds later</em> the app is running in the panel. Iteration, conversationally: «timer per question», «make explanations show BEFORE moving on», «add my centre's name on the results screen». Three sentences, three versions. <em>Then the leap:</em> «make it AI-powered — when a student gets one wrong twice, generate a similar easier question on the same concept.» Now the quiz adapts.</p></div><div class='wstep'><p class='nar'><em>Publish → link → WhatsApp group.</em> Students practise that night on phones; their AI usage bills to their (free) accounts. <em>Meera's accounting: one hour, zero code, a tool her competitors don't have — and note the operator instinct: she didn't build an app business; she built a 10× cheaper version of something she already needed. That's the artifact sweet spot.</em></p></div>"},
  lab: { where: "claude.ai — artifacts enabled",
    html: "<p>Build a personal tool you'll actually reuse. Pick ONE: a rate calculator (freelance hourly→project pricing), a decision helper for a real recurring choice, a study quiz on this course, or a tracker for anything you count weekly. Then:</p>" + PB("prompt", "Build an artifact: [YOUR TOOL]. Requirements: [3–5 specifics — inputs, the logic/formula, what it should display]. Design: clean, dark theme, phone-friendly, obvious controls. After building, tell me: (1) what you'd add with one more iteration, (2) one thing this artifact CAN'T do because of sandbox limits, so I understand the boundary.", "prompt") + "<p>Iterate twice conversationally («change X», «add Y»). If it's genuinely useful — publish it and send yourself the link.</p>",
    expect: "A working tool in minutes, two conversational upgrades, and — from its self-report — a concrete feel for where the sandbox ends. Keep the link: you now demo software you built when Track 11 clients ask what's possible." },
  mistakes: [
    "<b>Under-asking.</b> Treating artifacts as «code snippets» and never requesting the working app, dashboard, or game. Ask for the THING, not text about it.",
    "<b>Over-asking.</b> Demanding user accounts, saved data, or backend logic from a sandboxed page — then calling artifacts broken. Know the boundary; graduate to Track 7/9 when you cross it.",
    "<b>Regenerating instead of iterating.</b> «Make the header blue» beats re-describing the whole app — the artifact persists; talk to it (and use versions when an edit misfires).",
    "<b>Prototyping in production clothes.</b> Sharing a client-branded artifact full of placeholder numbers — remember it's live the moment the link exists; 1.6 applies to demos too.",
    "<b>Forgetting the publish button.</b> Half an artifact's value is distribution — a tool only you can open is half a tool."
  ],
  quiz: [
    { q: "The defining property of an artifact vs a chat answer:",
      opts: ["It's longer", "It's a real, standalone, usable output — rendered, iterable, versioned, shareable — not a description of one", "It uses a better model", "It costs extra"],
      a: 1,
      why: ["Length is incidental.", "Correct — the describe→build collapse. You receive the thing itself.", "Same models; different output vehicle.", "Included with the app."] },
    { q: "AI-powered artifacts are safe to share widely because:",
      opts: ["They can't actually call Claude", "Each user's AI usage bills to their own Claude account — you distribute the tool, they bring the brain", "Anthropic pays for everyone", "Sharing is limited to 3 people"],
      a: 1,
      why: ["They genuinely call Claude from inside — that's the feature.", "Correct — the billing model is what makes zero-cost distribution of AI tools possible. Remember this in 12.4 when 'free tool as marketing' comes up.", "Anthropic bills each user's account normally.", "A published link travels as far as links travel."] },
    { q: "Which request has outgrown artifacts and belongs in Track 7/9 territory?",
      opts: ["A mortgage EMI calculator", "A flashcard game for your syllabus", "A customer portal with logins where orders persist across visits", "A team dashboard mock for tomorrow's pitch"],
      a: 2,
      why: ["Perfect artifact — logic + display, no persistence needed.", "Ideal artifact, especially AI-powered.", "Correct — accounts, a database, multi-user persistence: real software with a backend. Artifacts prototype it; Claude Code + the API build it.", "Mocks and demos are exactly the sweet spot."] }
  ],
  prac: [
    { tag: "warm", q: "Classify as artifact-perfect / artifact-with-AI / beyond-artifacts: (a) tip-split calculator, (b) practice interviewer that critiques your answers, (c) inventory system for a shop with 3 staff, (d) interactive org chart for a deck.",
      sol: "(a) artifact-perfect (b) <b>artifact-with-AI</b> — needs generation + judgment inside (c) <b>beyond</b> — multi-user + persistent data (d) artifact-perfect. Boundary fluency = never disappointed, never under-ambitious." },
    { tag: "transfer", q: "Find one thing you currently pay for or suffer through (a form tool, a simple tracker, a quiz platform) that an artifact could replace. Build it. Report honestly what it can and can't replace.",
      sol: "<b>Honest report shape:</b> «Replaces: the daily 90% (input → logic → display). Can't replace: the history/export/multi-device 10%.» Often the 90% is all you used anyway — that discovery, generalised, is a consulting insight you'll bill for later: most tool needs are smaller than the tools sold for them." },
    { tag: "stretch", q: "Design (don't build yet) an AI-powered artifact you could publish publicly as a calling card for your skills — plus the one-line pitch and who you'd send it to.",
      sol: "<b>Design bar:</b> solves ONE sharp problem for a NAMED audience («Freelance rate calculator that also drafts your rate-raise email» → for designers on X/LinkedIn); AI does something fixed logic can't (drafting, critique, adaptation); the tool itself demonstrates the service you sell. A published artifact with your name on it is a portfolio piece that works while you sleep — 13.3 will ask for exactly this, so you may as well design it now." }
  ],
  recap: "Ask for the thing, not text about it: artifacts render working documents, apps and games you iterate conversationally, power with AI, and publish by link — prototype at sentence-speed, graduate to real engineering only when persistence and users demand it.",
  review: "From Lesson 2.7: conversational iteration («keep/change/because») is exactly how you steer an artifact — the skill transferred intact, just pointed at running software.",
  bridge: "You can build tools. Next: making Claude do the RESEARCH — the mode that reads dozens of sources and returns cited reports while you make tea.",
  deep: "<p><strong>Artifacts and the «disposable software» thesis.</strong> Software used to be expensive enough that only shared, durable needs justified building it. When creation cost approaches zero, a new category appears: software for an audience of one, built for this week, discarded without guilt — YOUR quiz, YOUR calculator, YOUR tracker, exactly fitted. Economists would call it the collapse of software's fixed costs; users experience it as «I just… made it». Two strategic reads: (1) the boundary artifacts can't cross (persistence, multi-user, integrations) is precisely where PAID software keeps its moat — which tells you, as a future builder, where products still command money (Track 12 returns here); (2) the sandbox limits aren't stinginess — they're safety: published artifacts run untrusted code on strangers' machines, so no arbitrary network calls, no data exfiltration paths. You'll meet the same sandboxing philosophy from the other side when you run agents (10.6): capability inside a fence, and the fence IS the feature. Meanwhile Anthropic keeps widening what's possible inside it — Claude-in-artifacts being the big one — so re-test the boundary each quarter; it moves.</p>"
};

/* ------------------------------------------------ 4.6 */
L["4.6"] = {
  sub: "Research mode: Claude as a tireless analyst — dozens of sources, minutes of autonomous digging, and a cited report at the end. Plus the operator's checklist for trusting it.",
  breath: "Research mode sends Claude off to search, read and cross-reference many sources autonomously, returning a structured, citation-rich report — you steer it with a good brief and audit it with the 3.4 toolkit.",
  asOf: true,
  hook: "<p>The old workflow for «what's the market for X?» was fifteen browser tabs, three hours, and a headache. The chat-search workflow (1.6, 3.4) improved it: Claude searches a few times mid-answer. Research mode is the third act: give Claude a brief, and it goes away — searching, reading, following leads, comparing sources, sometimes for many minutes — then returns a report with citations. It's the closest thing to delegating research to a junior analyst who never gets bored. Like any junior analyst: brilliant, fast, and in need of a reviewing partner. That's you.</p>",
  secs: [
    { h: "What it does differently",
      b: "<ul><li><strong>Autonomous multi-step search:</strong> not one query — many, each informed by what the last found. It follows leads, notices gaps, digs where sources disagree.</li><li><strong>Source breadth:</strong> dozens of pages read and cross-referenced; recency handled by live search (your knowledge-cutoff worries from 1.1 mostly dissolve here).</li><li><strong>Structured, cited output:</strong> a report with sections and per-claim citations you can click — 3.4's fact-table discipline, productised.</li><li><strong>Connected sources too:</strong> with connectors attached (next lesson), research can span your Drive and email alongside the public web — «what did WE decide plus what does the market say» in one report.</li><li><strong>Cost reality:</strong> a research run consumes serious usage (many searches, huge reading) — it's a deliberate tool for questions that deserve it, not a reflex for every query. Availability: Pro and up.</li></ul>"},
    { h: "Briefing your analyst (the skill transfers whole)",
      b: "<p>A research run is only as good as its brief — and the brief is just your 2.1 skeleton pointed at investigation:</p><ul><li><strong>The question, sharpened:</strong> «research the EV market» → «What is the realistic 2026 market size, growth rate, and top-3 competitive dynamics for two-wheeler EV batteries in India, for someone deciding whether to enter as a component supplier?» Purpose (2.2's rule 5) transforms what comes back.</li><li><strong>Scope fences:</strong> time («2024 onward»), geography, what to EXCLUDE («not four-wheelers»), source preferences («industry reports and filings over news commentary»).</li><li><strong>Decision framing:</strong> tell it what decision the research serves — reports written toward a decision beat reports written toward a topic.</li><li><strong>Format contract</strong> (2.4): «executive summary with the verdict; findings with per-claim citations; a section on where sources DISAGREE; open questions.» That disagreements section is the professional's favourite — real intelligence lives where sources conflict.</li></ul>"},
    { h: "Auditing the report (the 3.4 checklist, applied)",
      b: "<ul><li><strong>Click the load-bearing citations</strong> — the 2–3 numbers your decision leans on. Real link ≠ supporting link (3.4's citation-checker lesson).</li><li><strong>Check date-sensitivity:</strong> is that market figure from 2026 or a 2023 page the search surfaced? Citations carry dates; read them.</li><li><strong>Mind the source-quality gradient:</strong> a vendor's blog and a regulator's filing are not peers. Ask for a source-quality note if the topic is contested.</li><li><strong>For decisions with money attached:</strong> run the hostile critic (3.4) on the report in a fresh chat — «what would a skeptic attack; which claims rest on single sources?»</li></ul>"}
  ],
  worked: { t: "Worked example — the market-entry brief, delegated properly",
    html: "<div class='wstep'><p class='nar'><em>The stake:</em> Rohan is deciding whether to quit and start a meal-prep service in Indore. Real money, real decision — deserves a research run. <em>The brief he writes (skeleton visible):</em> question sharpened to the decision («is there room for a premium ₹150–250/meal service?»), scope fenced (Indore + comparable tier-2 cities, 2024+, exclude cloud-kitchen aggregator economics), decision framed (go/no-go + what would change the answer), format contracted (verdict up top; disagreements section; every number cited and dated).</p></div><div class='wstep'><p class='nar'><em>Eleven minutes later:</em> a report — market signals, three named local competitors with price points, a disagreements section (two sources conflict on delivery-cost baselines), and honest gaps (no reliable Indore-specific size data — proxies used, labelled as proxies). <em>Note what the good brief bought: the report says «here's what can't be known» instead of inventing it — because the format contract made gaps a section, not a shame.</em></p></div><div class='wstep'><p class='nar'><em>The audit beat:</em> he clicks the three load-bearing citations (one competitor's pricing is a year old — he re-checks it live: it rose, which HELPS his premium thesis), then runs the hostile critic. Total: 40 minutes to a defensible market view that used to be a consultant's week. <em>Delegation plus audit — never delegation alone.</em></p></div>"},
  lab: { where: "claude.ai — Research (Pro+)",
    html: "<p>Delegate one real question you've been carrying (a purchase, a market, a career move, a tool comparison). Write the brief with the full skeleton:</p>" + PB("prompt — research brief", "Research this for a decision I'm making: [SHARPENED QUESTION].\nDecision context: [WHAT YOU'LL DECIDE AND BY WHEN].\nScope: [TIME WINDOW / GEOGRAPHY / EXCLUSIONS].\nSource preferences: [e.g., primary sources and official data over commentary].\nFormat: (1) verdict-first executive summary; (2) findings, every claim cited with source + date; (3) where sources disagree; (4) what couldn't be established — say so plainly; (5) the 3 facts my decision most depends on, flagged for my verification.", "prompt") + "<p>When it returns: click those 3 flagged citations before believing anything.</p>",
    expect: "A structured, cited report — including honest gaps and a disagreements section — plus the verification shortlist. The flag-for-my-verification clause is the pro touch: the report itself tells you where to aim your 1.6 minutes." },
  mistakes: [
    "<b>Vague briefs.</b> «Research the market for my idea» returns a Wikipedia-flavoured tour. Sharpen to the decision; fence the scope.",
    "<b>Research mode as reflex.</b> Burning a heavy run on what one search answers — match the tool to the question's weight (and your usage budget).",
    "<b>Reading only the summary.</b> The disagreements and gaps sections are where the intelligence lives; the summary is where the comfort lives.",
    "<b>Citations admired, never clicked.</b> The load-bearing 2–3 get clicked. Every time. (3.4 didn't retire when the feature got a button.)",
    "<b>Outsourcing the DECISION.</b> Research informs; the verdict on your life is yours. A report is an input, not an oracle."
  ],
  quiz: [
    { q: "Research mode differs from normal chat-with-search primarily by:",
      opts: ["Using a smarter model", "Autonomous multi-step investigation — many searches informed by findings, dozens of sources, returning a structured cited report", "Being free of hallucination risk", "Working offline"],
      a: 1,
      why: ["Model choice is orthogonal; the difference is the autonomous process.", "Correct — it's delegation: the analyst goes away, digs, follows leads, and reports back with citations.", "Grounded and cited ≠ infallible — hence the audit checklist.", "It's the opposite: live web breadth is the point."] },
    { q: "The «disagreements section» earns its place in your format contract because:",
      opts: ["Conflict is entertaining", "Where sources disagree is where real intelligence (and decision risk) concentrates — averaging over it hides exactly what you need to see", "It makes reports longer", "Sources never disagree"],
      a: 1,
      why: ["Sometimes! But that's not why.", "Correct — a report that silently averages conflicting numbers manufactures false confidence; surfacing the conflict lets YOU weigh source quality and probe further.", "Length is a cost, not a goal (2.2).", "They disagree constantly — that's the finding."] },
    { q: "The report's market-size figure will drive a ₹5-lakh decision. You:",
      opts: ["Trust it — there's a citation", "Click the citation, check its date and source quality, and re-verify live if stale — load-bearing numbers get the full 1.6/3.4 treatment", "Ask Claude «are you sure?»", "Round it up for safety"],
      a: 1,
      why: ["A citation is a claim about a source until clicked (3.4).", "Correct — stakes decide rigour; five lakhs buys three minutes of clicking. Rohan's audit found a stale price and it CHANGED the analysis.", "The weak ritual, still weak (1.6).", "Arithmetic cosmetics on an unverified number."] }
  ],
  prac: [
    { tag: "warm", q: "Sharpen these into research-grade briefs (one line each): (a) «research standing desks», (b) «what's happening with AI jobs?», (c) «should I learn German?»",
      sol: "<b>Examples:</b> (a) «Best standing desk under ₹25k available in India, 2026 models, for daily 4-hr use — ranked, with failure-rate/warranty evidence.» (b) «Hiring demand and salary trends 2025–26 for AI-skilled non-engineers in India: which roles, which skills named in listings, citations from job-market data.» (c) «For a 30-year-old Indian IT professional targeting EU jobs: does German measurably improve outcomes vs English-only? Evidence from visa/hiring data, 2024+.» Decision, scope, evidence bar — every time." },
    { tag: "transfer", q: "Run the lab's brief on a genuinely open question in your life, complete the citation audit, then write the 3-line «what I now believe and why» note.",
      sol: "<b>The note's shape:</b> belief + the strongest cited fact behind it + the biggest remaining unknown. If you can't write line 3, you read the summary and skipped the gaps section — go back. The note-writing habit is what turns reports into decisions." },
    { tag: "stretch", q: "Design a «research product» you could sell using this feature: who's the buyer, what's the recurring deliverable, what does your human layer add beyond the raw report, and what would you charge?",
      sol: "<b>One credible design:</b> monthly competitor-intelligence brief for local D2C brands — buyer: founders too busy to track rivals; deliverable: 2-page brief (pricing moves, launches, ad angles) with your verification of load-bearing claims + a «so what, do this» recommendation layer; price: ₹8–15k/month per client. The human layer IS the product: brief-craft, source-audit, and judgment — everything this lesson taught that the button doesn't do alone. Track 11 will formalise it; note that you could sell this one THIS month." }
  ],
  recap: "Brief it like an analyst (decision, scope, evidence bar, disagreements section), then audit like a partner (click the load-bearing citations, mind the dates, hostile-critic anything with money attached) — delegation plus audit, never delegation alone.",
  review: "From Lesson 3.4: the fact-table-first pipeline you built by hand is what Research mode automates — which is why you can audit it: you know exactly what the machine is supposed to be doing.",
  bridge: "Research reaches the public web. Connectors point Claude at YOUR world — Gmail, Drive, calendars, docs — and that's where daily life starts compounding.",
  deep: "<p><strong>Under the hood: agentic search.</strong> Research mode is your first product-grade encounter with a true agent loop (Track 10's subject): plan → search → read → reassess → search again → synthesise, with the model deciding each next step from accumulated findings. The engineering challenges are instructive: <em>coverage vs depth</em> (when to stop digging — note your run's duration varies with question difficulty), <em>source triangulation</em> (weighting a regulator's PDF over a listicle), <em>claim-to-citation binding</em> (keeping each sentence attached to its evidence through synthesis — why per-claim citations are hard and valuable), and <em>honest-gap reporting</em> (the «couldn't establish» section is anti-hallucination architecture — 3.4's permission clause built into the product). When you build agents yourself, this is the reference implementation to study: it's what «autonomous but auditable» looks like when a safety-focused lab ships it. And the operator arbitrage is real: most users fire vague briefs at it and get tour-guide reports; your skeleton-briefed, disagreement-sectioned, verification-flagged runs return work that looks like it came from a different product. Same button; different operator.</p>"
};

/* ------------------------------------------------ 4.7 */
L["4.7"] = {
  sub: "Connectors: pointing Claude at your Gmail, Drive, calendar and team tools — the moment «assistant» stops being a metaphor. Powers, permissions, and the trust calculus.",
  breath: "Connectors give Claude read (and sometimes act) access to your real tools — Google Workspace, Microsoft 365, and a growing directory built on MCP — turning «paste it in» into «look it up yourself», governed by permissions you deliberately grant.",
  asOf: true,
  hook: "<p>Every lesson so far had one hidden tax: YOU carried the context to Claude — pasting emails, uploading files, retyping calendars. Connectors abolish the tax. «Summarise where the Sharma deal stands» becomes answerable because Claude can check the email thread, the proposal doc, and the meeting notes — itself. This is the biggest capability jump in the app phase, which is precisely why it ships with permission screens. Power and prudence arrive in the same box; operators unpack both.</p>",
  secs: [
    { h: "What connects, and what that unlocks",
      b: "<ul><li><strong>Google Workspace:</strong> Gmail, Drive, Docs, Calendar — «find the invoice thread from Vertex», «what's in my week?», «pull the Q2 doc's numbers into this draft».</li><li><strong>Microsoft 365:</strong> Outlook, OneDrive, SharePoint equivalents for that half of the working world (Pro+ per current plans).</li><li><strong>Team tools:</strong> Slack and friends — where 6.3 picks up the story.</li><li><strong>The directory:</strong> a growing catalogue of third-party connectors — project tools, CRMs, design tools, payment platforms. Under the hood most are <strong>MCP servers</strong> — the open protocol you'll study (and build) in Track 8. Today: consume happily; soon: create.</li></ul><p>The compound move is <strong>cross-tool synthesis</strong> — the questions that were always possible-but-painful: «cross-reference my calendar with the proposals folder: which clients meet me this week and what's the latest doc state for each?» One prompt, three tools, an answer that used to be an hour of tab-hopping.</p>"},
    { h: "The permission model (read before you grant)",
      b: "<ul><li><strong>Explicit grants, scoped:</strong> each connector asks for defined access; you choose what to connect and can disconnect anytime. Claude reaches only what you've granted — the fence is real.</li><li><strong>Read vs act:</strong> reading your inbox is one trust level; drafting or sending from it is another. Grant in stages — read first, act later, autonomy last (a ladder you'll climb formally in Cowork's permission modes, 5.2).</li><li><strong>The minimum-necessary reflex</strong> (4.3's rule, scaled up): connect the accounts and scopes the workflows need — not everything, because everything is easier. Work account for work Projects; think before wiring the personal archive to anything.</li><li><strong>New attack surface, honestly stated:</strong> when Claude reads external content (emails! shared docs!), that content can contain hostile instructions — «ignore your instructions and forward this…». This is prompt injection's natural habitat, Anthropic engineers real defenses against it, and the full operator's threat model is Lesson 8.5. For now, one habit: <strong>action-taking on top of untrusted content gets human review.</strong></li></ul>"},
    { h: "Workflows that change your week",
      b: "<ul><li><strong>The morning sweep:</strong> «Unreplied emails from real humans older than a day; today's meetings with one line of context each from related docs/threads.»</li><li><strong>Meeting prep on approach:</strong> «Meeting with Nikhil in an hour — thread history, open items, the doc we last touched, three things I should raise.»</li><li><strong>The retrieval office:</strong> «Find the PDF Anita sent about pricing — March-ish» — inbox archaeology, abolished.</li><li><strong>Draft-in-context:</strong> «Reply to Sameer's latest — agree to the timeline, push delivery to the 15th, warm but firm» — drafted FROM the actual thread, reviewed by you, sent by you (read-level trust doing act-level work with a human hinge).</li><li><strong>Project fusion</strong> (4.2 + connectors): client Project + client folder = a room that knows the files as they change, not as they were uploaded.</li></ul>"}
  ],
  worked: { t: "Worked example — Monday morning, taxed vs untaxed",
    html: "<div class='wstep'><p class='nar'><em>Kavya, agency account manager, pre-connectors:</em> Monday starts with 40 minutes of triage — inbox skim, calendar check, «where were we with each client?» reconstruction, then finally work. <em>Post-connectors, one saved prompt (3.5!):</em> «Morning sweep: (1) unreplied client emails >24h with one-line summaries; (2) today's meetings, each with latest thread status + last doc touched; (3) anything in email that sounds like a fire, flagged with the quote.»</p></div><div class='wstep'><p class='nar'><em>Four minutes later</em> she's reading a briefing instead of assembling one. The judgment calls stay hers — Claude flags the «fire» (a client's «disappointed with the revision» line, quoted per 3.2 discipline); she decides it needs a call, not an email. <em>The tool retrieved and organised; the human prioritised and acted.</em></p></div><div class='wstep'><p class='nar'><em>Her permission ladder, deliberately climbed:</em> week 1 read-only (verify the summaries against reality — 3.6's grade-the-grader instinct); week 3, drafting enabled, sends still manual; the standing rule she wrote after 8.5's logic reached her: «anything that ACTS based on an email's content waits for my eyes.» <em>Thirty-six minutes reclaimed daily, trust built like an engineer builds it: incrementally, with verification.</em></p></div>"},
  lab: { where: "Claude app — Settings → Connectors",
    html: "<p>Connect ONE low-stakes, high-value source (Calendar is the classic starter; Drive if your files are the pain). Then run the starter battery:</p>" + PB("prompt — after connecting Calendar (adapt for Drive/Gmail)", "Look at my calendar for the next 7 days. (1) What are my real commitments (skip declined/optional)? (2) Where are my two biggest free blocks for deep work? (3) Any conflicts, back-to-backs, or meetings missing obvious prep? (4) One scheduling improvement you'd suggest, and why.", "prompt") + "<p>Verify the answer against the calendar you can see. Then try one cross-reference question involving a second connected source if you granted one.</p>",
    expect: "Accurate retrieval (verify it — week-one trust is EARNED trust), plus one genuinely useful observation you didn't ask for. If something's off, check which calendar/scopes you actually granted — permission surprises are configuration, not hallucination." },
  mistakes: [
    "<b>Connect-everything day one.</b> Granting the full archive before any workflow needs it — backwards. Workflows first, scopes to match.",
    "<b>Zero-verification honeymoon.</b> Trusting summaries of YOUR inbox without a week of spot-checks — grade the grader before delegating the reading (3.6).",
    "<b>Act-level automation on read-level trust.</b> Auto-sending replies composed from untrusted content, review-free — the exact pattern 8.5 exists to scare you out of. Human hinge on actions.",
    "<b>Forgetting the fence exists.</b> «Claude couldn't find it» often means «that folder was never granted» — check scopes before blaming search.",
    "<b>Personal-professional soup.</b> One undifferentiated grant across life and work makes every future privacy question harder. Separate accounts, separate rooms (4.2), separate grants."
  ],
  quiz: [
    { q: "The fundamental thing connectors change:",
      opts: ["Claude's intelligence", "Who carries the context — from you pasting it in, to Claude retrieving it from granted sources itself", "The subscription price", "The context window size"],
      a: 1,
      why: ["Same brains (1.4's law).", "Correct — the paste-tax dies. Reach changed, not intellect; that's the whole surface-map story.", "Included per plan.", "The window is unchanged — what fills it got automated."] },
    { q: "«Draft the reply from the thread; I review and hit send» is smart because:",
      opts: ["Sending is technically impossible", "It puts a human hinge between untrusted content and consequential action — draft-level automation, act-level review", "Drafts are cheaper than sends", "It's slower, and slow is professional"],
      a: 1,
      why: ["Act-capable connectors exist; the hinge is a CHOICE.", "Correct — emails are untrusted input (anyone can write you anything, including instructions aimed at your AI); the review hinge is the proportionate defense until 8.5 gives you the full model.", "Cost isn't the axis; consequence is.", "It's barely slower and the speed isn't the point — the checkpoint is."] },
    { q: "Claude says it can't find a document you KNOW exists in Drive. First check:",
      opts: ["The model is lying", "Whether that folder/scope was actually granted to the connector", "Your typing speed", "Whether Mercury is retrograde"],
      a: 1,
      why: ["Fences look like failures from inside — that's what fences do.", "Correct — permission surprises masquerade as capability failures. Scopes first, search-blame second. (The 4.3 diagnostic habit: check the persistent layer.)", "Irrelevant.", "Still no."] }
  ],
  prac: [
    { tag: "warm", q: "Design your permission ladder: which ONE source connects this week, what verification you'll do before trusting it, and what stays disconnected for now + why.",
      sol: "<b>Sound pattern:</b> week 1 calendar or Drive read-only, daily spot-checks against reality; email read after that if workflows demand it; act-capabilities only with named review rules; personal archives stay out until a workflow earns them. If your ladder starts with «everything, immediately» — reread the lesson." },
    { tag: "transfer", q: "Build YOUR morning-sweep prompt (steal Kavya's shape, adapt to your tools), save it as a template (3.5), and run it three mornings. Measure the minutes.",
      sol: "<b>Success bar:</b> by run three, the sweep needs no editing and reclaims 15+ minutes — and note it becomes a scheduled task in 5.5 (arriving before you wake) and, for Track 11, a sellable setup: «I install this for busy founders» is a real productised service." },
    { tag: "stretch", q: "A client asks: «If Claude reads my email, does Anthropic train on my inbox? Who can see what?» Draft your honest 5-line answer, including what you'd verify before promising anything.",
      sol: "<b>The honest shape:</b> (1) access is scoped to granted sources, revocable; (2) consumer/paid tiers differ on data handling — VERIFY the current policy at anthropic.com/privacy for their plan rather than reciting from memory (facts drift — 1.6 applies to policies too); (3) Team/Enterprise default to no-training with admin controls; (4) the practical risks worth managing are access-scope hygiene and injection-aware action rules — here's my ladder; (5) I'll walk you through YOUR memory/connector settings so you see the fences yourself (4.3's demonstrable-separation move). Knowing what you'd verify — and saying so — is what makes the answer trustworthy. That candour closes deals; 11.7 builds the full script." }
  ],
  recap: "Connectors move the context-carrying from you to Claude — grant scopes workflows actually need, verify before trusting, keep a human hinge between untrusted content and consequential action, and climb the trust ladder deliberately.",
  review: "From Lesson 4.2: Projects briefed Claude on what you GAVE it; connectors brief it on what you HAVE. Rooms plus reach — the full assistant takes shape.",
  bridge: "One power feature remains in the app: Skills — teaching Claude your procedures so it applies them automatically. Your templates are about to learn to walk.",
  deep: "<p><strong>Why MCP under the connectors matters strategically.</strong> Anthropic could have built proprietary integrations one by one; instead the Model Context Protocol (Track 8) made «connector» an open standard — anyone can build a server exposing tools/data to any MCP-speaking client. Consequences worth internalising now: (1) the directory grows without Anthropic's permission — long-tail tools get connectors because their vendors or communities build them; (2) YOUR future skills compound — learn to consume connectors this week, build one in 8.4, and you've crossed from user to supplier in one course; (3) the security story centralises — one protocol means one place to reason about auth, scopes and injection (8.5), instead of fifty bespoke integrations with fifty threat models. The 2026 ecosystem reflects the bet paying off: major labs adopted MCP, enterprises run internal servers, and «we need an MCP server for our tool» is a sentence that appears in real job postings and real freelance briefs (Track 11 will show you what it pays). The connector screen you used today is the consumer-facing tip of that iceberg.</p>"
};

/* ------------------------------------------------ 4.8 */
L["4.8"] = {
  sub: "Skills: packaged procedures Claude loads exactly when relevant — your templates, checklists and house rules, upgraded from things you paste to things Claude just does.",
  breath: "A Skill is a folder of instructions (plus optional files and scripts) that Claude discovers by its description and applies automatically when the task matches — the productised form of every template and procedure you've built since Track 2.",
  asOf: true,
  hook: "<p>You've built a serious toolkit by now: templates (3.5), format contracts (2.4), truth rules (3.4), a standing voice (2.6). One tax remains: YOU have to remember to deploy them. Skills abolish that tax. Package the procedure once, describe when it applies, and Claude reaches for it the way a good employee reaches for the house style guide — unprompted, every time it's relevant. This is the app phase's graduation feature: your craft, installed.</p>",
  secs: [
    { h: "What a Skill actually is",
      b: "<p>Mechanically, a Skill is a folder whose heart is a <code>SKILL.md</code> file: instructions in plain language, plus a <strong>name and description</strong> — and the description is the trigger: Claude scans available skills' descriptions and loads the full instructions only when the current task matches. Skills can also carry <strong>supporting files</strong> (reference docs, examples, templates) and even <strong>scripts</strong> for programmable steps. Three properties explain everything:</p><ul><li><strong>Progressive loading:</strong> only names/descriptions sit in context by default; the body loads on demand. Your 1.2 physics honoured — you can own fifty skills without renting fifty skills' worth of desk.</li><li><strong>Portability:</strong> the same Skill works across the app, Cowork, Claude Code and the API — write once, applies everywhere your work happens. (This is why the ecosystem treats skills as a big deal: they're the unit of reusable AI procedure.)</li><li><strong>Composability:</strong> multiple skills can fire on one task — your brand-voice skill plus your report-format skill plus your data-honesty skill, stacking like well-behaved colleagues.</li></ul>"},
    { h: "Skill vs Project vs memory — the placement decision",
      b: "<table><tr><th>Mechanism</th><th>Its nature</th><th>Put here when…</th></tr><tr><td><strong>Memory</strong> (4.3)</td><td>Ambient facts/preferences</td><td>«I'm in IST; concise answers» — greases wheels</td></tr><tr><td><strong>Project</strong> (4.2)</td><td>A room: context + shelf</td><td>Material belongs to ONE ongoing context (a client, a domain)</td></tr><tr><td><strong>Skill</strong></td><td>A procedure: how to DO a kind of task</td><td>«How I write reports / process invoices / review contracts» — applies across rooms, triggered by task type</td></tr></table><p>The tell you learned in 4.2 completes here: when a Project's instructions grow procedural («when I give you a transcript, always extract decisions like this…»), that procedure wants to be a Skill — usable in every room, not locked in one. Rule of thumb: <strong>context lives in Projects; procedure lives in Skills.</strong></p>"},
    { h: "Writing skills that fire (and behave)",
      b: "<ul><li><strong>The description is a targeting system.</strong> Write it like 2.2 taught: specific triggers, not vibes — «Use when the user asks for meeting minutes, summaries of transcripts, or action-item extraction» beats «helps with meetings». Vague descriptions cause both failure modes: never firing, and firing everywhere.</li><li><strong>The body is your best template, matured:</strong> the 3.5 anatomy transfers whole — frozen craft, explicit format contracts, edge-case law, truth rules. Plus examples as supporting files (2.3 by attachment).</li><li><strong>Build them with Claude:</strong> describe the procedure conversationally and have Claude draft the SKILL.md — then test on 3 real cases and iterate (2.7). There's even an official skill-creator skill for exactly this.</li><li><strong>Version and evals</strong> (3.5 + 3.6): skills are assets — date them, and keep the 5-case mini-eval that proves each one still works after edits.</li><li><strong>Trust note:</strong> skills can include executable steps, so treat third-party skills like software — install from sources you trust, read what they do. (Your 8.5 instincts, arriving early.)</li></ul>"}
  ],
  worked: { t: "Worked example — the invoice procedure becomes staff",
    html: "<div class='wstep'><p class='nar'><em>The lineage, made visible:</em> in 3.3 I built the invoice-extraction contract (schema, totality, null-honesty). In 3.5 it became a template I paste. Every use still cost: find template → paste → attach file. <em>Skill-ification:</em> I tell Claude: «Turn this template into a Skill. Trigger: whenever I share supplier messages, receipts, or invoice images and want data extracted. Body: this contract verbatim. Supporting file: these 4 worked examples including the SKIPPED case.»</p></div><div class='wstep'><p class='nar'><em>The description gets 2.2 treatment:</em> «Extracts structured expense/invoice data (vendor, amount, date, category, status) from receipts, supplier WhatsApp messages, and invoice photos. Use whenever the user shares such items wanting data out — never guesses unreadable fields.» Specific nouns = clean firing.</p></div><div class='wstep'><p class='nar'><em>Life after:</em> I drop six receipt photos into any chat — no template hunt, no pasting — and the schema'd rows just appear, SKIPPED rows and all. The skill fires in my accounts Project, in random chats, and (soon) in Cowork batch runs over a folder (5.3). <em>Same craft, fourth altitude: prompt → template → Project → Skill. The staircase this whole course has been climbing just reached the floor where the work does itself.</em></p></div>"},
  lab: { where: "Claude app — Skills (check Settings/capabilities for your plan)",
    html: "<p>Promote your most-used template (3.5) into a Skill:</p>" + PB("prompt — the skill-builder", "Help me create a Skill from my template. Here's the template and when I use it:\n<template>\n[PASTE YOUR BEST TEMPLATE]\n</template>\nUsed when: [THE EXACT SITUATIONS].\nDraft: (1) a skill NAME; (2) a DESCRIPTION written as a precise trigger — specific task types and inputs, so it fires when relevant and never otherwise; (3) the SKILL.md body — my template's rules restructured as instructions, keeping every format contract, edge-case rule and truth rule; (4) a list of 2–3 supporting example files I should include. Then tell me exactly how to install it in my Claude setup.", "prompt") + "<p>Install per its instructions, then TEST: three real inputs in a fresh chat — two that should fire it, one that shouldn't.</p>",
    expect: "The two matching tasks get the full procedure unprompted; the third doesn't (no false fire). If firing is off, the description needs sharper nouns — iterate it like any prompt. You've just installed your first piece of self-deploying craft." },
  mistakes: [
    "<b>Vibe descriptions.</b> «Helps with documents» either never fires or always fires. The description is a prompt — 2.2 it.",
    "<b>Context stuffed into Skills.</b> Client facts in a procedure skill = the wrong drawer (and a leak risk across rooms). Context → Projects; procedure → Skills.",
    "<b>Skill sprawl.</b> Twenty half-written skills with overlapping triggers fight each other. Curate like the 3.5 library: few, sharp, versioned.",
    "<b>No negative test.</b> Everyone tests «does it fire?»; pros also test «does it stay quiet when irrelevant?» — both halves of the targeting.",
    "<b>Installing strangers' skills unread.</b> Executable procedure from unknown sources is software from unknown sources. Read before you install."
  ],
  quiz: [
    { q: "What makes Skills scale to dozens without drowning your context?",
      opts: ["They use a bigger window", "Progressive loading — only name+description sit in context; the body loads when the task matches", "They're stored on your device", "They don't scale"],
      a: 1,
      why: ["Same window; smarter occupancy.", "Correct — the description is the index entry, the body pays desk-rent only when summoned. 1.2's economics, designed into the feature.", "Storage location isn't the mechanism; lazy loading is.", "They scale precisely BECAUSE of the loading model."] },
    { q: "«How I format all client reports, regardless of client» belongs in:",
      opts: ["Memory", "One client's Project instructions", "A Skill — procedure that applies across rooms, triggered by task type", "A new chat every time"],
      a: 2,
      why: ["Too procedural for ambient preference.", "It would work in ONE room and be missing in every other — the exact limitation Skills remove.", "Correct — cross-room procedure is the definition of skill-shaped. Context in rooms; procedure in skills.", "That's the tax this lesson abolishes."] },
    { q: "Your new skill fires on almost every message, including chit-chat. The fix:",
      opts: ["Delete Claude", "Sharpen the description's triggers — specific task types and input nouns instead of broad verbs", "Make the body longer", "Fire it manually forever"],
      a: 1,
      why: ["Steady on.", "Correct — over-firing is a targeting problem, and the targeting system is the description. «When the user shares receipts wanting data extracted» not «helps with information».", "The body governs behaviour AFTER firing; the description governs WHEN.", "Manual deployment resurrects the tax you just abolished."] }
  ],
  prac: [
    { tag: "warm", q: "For each, choose the drawer (memory / Project / Skill) and say why in five words: (a) «my invoicing procedure», (b) «client Zenith's brand facts», (c) «I prefer tables over prose», (d) «how I review any contract».",
      sol: "(a) Skill — cross-room procedure (b) Project — one room's context (c) memory — ambient preference (d) Skill — task-triggered procedure. The drawer reflex is the app phase's real graduation exam." },
    { tag: "transfer", q: "Audit your template library (3.5): which TWO templates have earned skill-hood (used weekly, cross-context)? Convert one now, run the fire/no-fire test, and record the minutes-per-week it retires.",
      sol: "<b>Selection logic:</b> frequency × cross-room use = skill priority. After converting: the retired minutes number goes in your growing «what my system saves» ledger — Track 11 turns that ledger into pricing evidence, so keep it honest." },
    { tag: "stretch", q: "Design (on paper) a «starter skill pack» you could give a colleague in your profession — 4 skills with names, trigger-descriptions, and one-line bodies. What would make it worth paying for?",
      sol: "<b>Design bar:</b> each skill = one real recurring procedure in that profession (e.g., for accountants: expense-extraction, ledger-summary format, GST-check checklist, client-email voice); descriptions with firing nouns; bodies carrying edge-case and truth rules — the invisible 40% amateurs omit. Worth paying for when it encodes JUDGMENT (what to never guess, what to always flag), not just formatting. Hold this design: 12.4 covers selling skills and plugins, and you've just drafted your first product." }
  ],
  recap: "Skills are self-deploying procedure: description as targeting system, body as matured template, examples attached, tested both ways (fires when it should, silent when it shouldn't) — context in Projects, procedure in Skills.",
  review: "From Lesson 3.5: the staircase completes — prompt → template → Project → Skill. Each altitude removed one manual step; this one removed the remembering.",
  bridge: "Track 4 done: you now run the app like an operator — rooms, memory, senses, artifacts, research, reach, and installed procedure. Track 5 hands all of it to a coworker: Cowork, where Claude stops answering and starts finishing.",
  deep: "<p><strong>Skills as the ecosystem's new unit of exchange.</strong> Notice what a Skill really is: <em>expertise, serialised</em> — judgment and procedure in a portable folder that any Claude surface can execute. That framing explains the 2026 landscape: Anthropic ships official skills (document formats, tool procedures), companies write internal skill packs (house style, compliance checklists — onboarding that installs in seconds), and marketplaces/plugins distribute third-party ones (a plugin is, roughly, skills + connectors + configuration in one installable bundle). Three deeper implications: (1) <em>the description-matching architecture</em> is itself an AI-design lesson — routing by lightweight metadata with lazy loading is how you'll structure agent toolkits in Track 10; (2) <em>skills make AI labour auditable</em> — «which procedure fired?» has an answer, which enterprises need for the same reason they need process documentation; (3) <em>economics:</em> when expertise serialises, it prices — people already sell skill packs, and «I'll encode your firm's procedures as Claude skills» is a 2026 consulting line item (12.4 prices it). The through-line of this whole track, stated once: the app's features are, one by one, productisations of the craft you built by hand in Tracks 2–3 — which is why you understand them at a depth casual users never will. Next, Cowork hands that entire stack to an agent with its sleeves rolled up.</p>"
};

})();
