/* Track 1 — How Claude Works (L1) */
(function(){
var L = window.LESSONS;

/* ------------------------------------------------ 1.1 */
L["1.1"] = {
  sub: "Before you can master Claude, you need the right mental model. Most people carry a wrong one — and it costs them every single day.",
  breath: "Claude is a prediction engine that read a huge slice of human writing and was then trained to be helpful, honest and harmless — it generates answers fresh every time instead of looking them up.",
  asOf: true,
  hook: "<p>In 2026, two people sit down with the same AI. One gets a mediocre paragraph and walks away calling it a toy. The other gets a week of work done before lunch. Same tool, same subscription, same day. The difference is never the tool — it is the <em>mental model</em> of the person driving it. This first lesson installs the correct one, because every technique in the next 87 lessons stands on it.</p><p>So let us answer the question properly: what actually is Claude?</p>",
  secs: [
    { h: "A prediction engine, not a database",
      b: "<p>Claude is a <strong>large language model</strong> (LLM) built by <strong>Anthropic</strong>, an AI safety company founded in 2021. Here is the plainest true description of how it works:</p><ul><li>During training, it read an enormous amount of human text — books, articles, code, conversations.</li><li>From all that reading, it learned deep statistical patterns: which words, ideas and structures follow which.</li><li>When you send it a message, it <strong>generates</strong> a response one small chunk at a time, each chunk chosen by asking «given everything so far, what comes next?»</li></ul><p>Think of a session musician who has played ten thousand songs. Ask for «something jazzy in a minor key» and she doesn't <em>look up</em> a song — she <em>produces</em> one, note by note, shaped by everything she has absorbed. That is Claude with language. It is why Claude can write a poem about your dog in the style of a pirate — no database contains that. It is also why Claude can occasionally state a wrong «fact» with total confidence: it is composing, not quoting. We deal with that properly in Lesson 1.6.</p>"},
    { h: "Trained to be helpful, honest, harmless",
      b: "<p>Raw pattern-prediction alone would make a strange assistant. So after the reading phase, Anthropic shapes the model's behaviour. Two ideas are worth knowing by name:</p><ul><li><strong>Reinforcement learning from human feedback (RLHF):</strong> humans compare pairs of model answers, and the model is nudged toward the kind people prefer — clearer, more useful, less evasive.</li><li><strong>Constitutional AI:</strong> Anthropic's signature method. The model is given a written set of principles — a constitution — and learns to critique and revise its own answers against those principles, rather than relying only on human raters.</li></ul><p>This is why Claude has a recognisable character: it explains its reasoning, admits uncertainty, pushes back on harmful requests, and generally behaves like a thoughtful colleague rather than a slot machine. Anthropic's stated mission — building AI that is <em>safe and beneficial</em> — is not marketing garnish; it shapes product decisions you will notice throughout this course.</p>"},
    { h: "What Claude is not",
      b: "<p>Clearing three misconceptions now will save you a hundred frustrations later:</p><ul><li><strong>Not a search engine.</strong> Claude's core knowledge comes from training, which has a cutoff date. For anything recent it must use its <em>web search</em> tool (it can — Lesson 4.6). Untangling «what the model knows» from «what it can look up» is a professional skill.</li><li><strong>Not a person.</strong> No feelings to hurt, no ego to bruise. You can demand three rewrites, say «that was wrong, fix it», or abandon a thread mid-sentence. Politeness costs nothing, but hesitation costs plenty.</li><li><strong>Not a mind-reader.</strong> Claude sees exactly the words you send and nothing else. Not your screen, not your intentions, not the context in your head. The whole craft of prompting — Phase B of this course — is the skill of transferring what is in your head into words.</li></ul>"}
  ],
  worked: { t: "Worked example — watching the mental model pay off",
    html: "<div class='wstep'><p class='nar'><em>The scene:</em> two people ask about the same topic. Person A types: «marketing tips». They get generic listicle mush — because a prediction engine given a generic prompt predicts the generic continuation. Garbage in, average out.</p></div><div class='wstep'><p class='nar'><em>Person B thinks like an operator:</em> «Claude only sees my words, so I'll put the context in the words.» They type: «I run a 6-table vegetarian café in Pune. Instagram following: 800 locals. Budget: ₹0. Give me 5 marketing moves I can execute this week, each under 2 hours of work, ranked by expected foot traffic.»</p></div><div class='wstep'><p class='nar'><em>Why B wins:</em> every constraint (6 tables, Pune, ₹0, this week) narrows the prediction space toward useful territory. B didn't know a secret feature. B just understood <strong>what kind of machine they were talking to</strong> — which is exactly what you now understand.</p></div>"},
  lab: { where: "claude.ai — free account works",
    html: "<p>Open <a href='https://claude.ai' target='_blank' rel='noopener'>claude.ai</a> (create a free account if needed) and run this experiment. First send the lazy version:</p>" + PB("prompt — version 1 (lazy)", "Give me some productivity tips.", "prompt") + "<p>Read the answer. Now send the operator version:</p>" + PB("prompt — version 2 (operator)", "I'm a college student juggling final-year exams and a part-time job (evenings, 4 hours). My phone is my biggest distraction and my mornings are free. Give me a realistic weekly productivity system: a morning study routine, one phone-taming tactic that doesn't require deleting apps, and one weekly review habit. Keep the whole plan under 300 words.", "prompt") + "<p>Compare the two answers side by side.</p>",
    expect: "Version 2 is dramatically more specific and usable — same model, same day, only the words changed. That gap is the skill this course trains." },
  mistakes: [
    "<b>Treating Claude like Google.</b> Typing two keywords and expecting magic. Claude rewards full sentences packed with context — it is a colleague, not a search box.",
    "<b>Assuming it knows «everything».</b> Its built-in knowledge has a cutoff date. For today's prices, news, or versions, it must search the web — and you should expect it to.",
    "<b>Quitting after one weak answer.</b> A first draft is an opening bid, not a verdict. Reply with what was wrong and watch it correct course — the conversation is the tool.",
    "<b>Believing confident tone = correct content.</b> Fluency is how LLMs fail: smoothly. Lesson 1.6 gives you the verification habits professionals use."
  ],
  quiz: [
    { q: "When Claude answers your question, what is it fundamentally doing?",
      opts: ["Searching a giant internal database of stored answers", "Generating a fresh response by predicting what text should come next", "Forwarding your question to human experts", "Copying the top result from the web"],
      a: 1,
      why: ["There is no database of stored answers inside the model — that's why it can write things nobody has ever written (and why it can also be wrong).", "Correct. Claude composes each answer chunk by chunk from learned patterns — like a musician improvising from deep experience, not playing back a recording.", "No humans are in the loop when Claude answers you. Responses are generated by the model in seconds.", "Claude can use web search as a tool when needed, but its default answers are generated from training, not copied from the web."] },
    { q: "What is «Constitutional AI», in one line?",
      opts: ["A law passed by governments to regulate AI models", "Anthropic's method of training Claude to critique and revise its own answers against a written set of principles", "A rule that Claude may only discuss legal topics", "The hardware Claude runs on"],
      a: 1,
      why: ["It's a training technique, not legislation — the name is a metaphor: the model gets a 'constitution' of principles.", "Correct — instead of relying only on human raters, the model learns to check its own outputs against explicit principles. It's a big part of Claude's character.", "Nothing to do with restricting topics to law — the 'constitution' is a set of behavioural principles.", "It's a training method, not hardware."] },
    { q: "Your friend types «business ideas» into Claude and gets a bland list. Based on this lesson, what's the best diagnosis?",
      opts: ["Claude is bad at business topics", "The free plan gives dumber answers on purpose", "A generic prompt makes the model predict the generic continuation — the input lacked context and constraints", "Claude was having a slow day"],
      a: 2,
      why: ["Claude handles business strategy extremely well — when given specifics to work with.", "Plans differ in usage amounts and features, but a lazy prompt gets a lazy answer on every plan.", "Correct. A prediction engine given an average prompt produces the average of the internet. Context and constraints steer it toward the specific and useful.", "Model quality doesn't wobble day to day in a way that explains this — the prompt is the variable that changed nothing and got nothing."] }
  ],
  prac: [
    { tag: "warm", q: "In one sentence of your own words, explain to a 12-year-old what Claude does when it answers a question.",
      sol: "<b>Something like:</b> «Claude read a gigantic amount of writing, and when you ask it something, it writes a brand-new answer by guessing — very cleverly — what words should come next, one bit at a time.» If your sentence says 'looks up' anywhere, revisit the first section." },
    { tag: "transfer", q: "Take a real question you asked any AI this month. Rewrite it the «operator» way: add who you are, your constraints, and exactly what shape of answer you want. Send both to Claude and compare.",
      sol: "<b>Check yourself:</b> your rewrite should include at least three concrete details (numbers, deadlines, tools, audience). If the two answers came back nearly identical, your added context wasn't specific enough to change the prediction — tighten it further." },
    { tag: "stretch", q: "Claude writes a confident paragraph about a medicine dosage, and separately a confident paragraph reviewing your poem. Explain why the first deserves verification and the second doesn't, using the prediction-engine model.",
      sol: "<b>Key idea:</b> the poem review only needs to be <em>useful</em>, and you can judge it directly — there's no external fact to get wrong. The dosage is a <em>factual claim about the world</em>: a prediction engine can compose plausible-but-wrong numbers with the same fluent confidence as right ones, and you can't judge it by reading. Fact-shaped output about high-stakes topics always gets verified (Lesson 1.6 shows how)." }
  ],
  recap: "Claude generates — it does not look up. It sees only the words you send, so context and constraints are how you steer the prediction. Fluent confidence is not evidence of truth.",
  bridge: "Every message you send gets chopped into «tokens», and Claude can only hold so many at once. That single fact explains costs, forgetful long chats, and half of all advanced technique — next lesson makes it visceral.",
  deep: "<p><strong>How deep does «prediction» go?</strong> Modern LLMs are transformer neural networks with billions of parameters. «Predicting the next token» sounds shallow, but to predict well the network must internally represent grammar, facts, logic, code semantics, even theory-of-mind-like structure — prediction pressure forces understanding-like machinery to emerge. Anthropic's own <em>interpretability</em> research (worth searching: «Anthropic interpretability features») peers inside and finds millions of human-recognisable concepts encoded in the network. The honest scientific position in 2026: these systems are far more than autocomplete, and far less than settled science — which is exactly why Anthropic invests so heavily in understanding them.</p>"
};

/* ------------------------------------------------ 1.2 */
L["1.2"] = {
  sub: "Tokens are Claude's atoms; the context window is its working memory. Master these two ideas and half of all «weird AI behaviour» becomes predictable physics.",
  breath: "Claude reads and writes in tokens (≈ three-quarters of an English word each), and everything — your chat, files, its answers — must fit in one context window; when it's full, quality drops and old material falls away.",
  asOf: true,
  hook: "<p>Why did Claude «forget» the name you told it an hour ago? Why does the same question cost 40× more with a big PDF attached? Why do very long chats slowly get… dumber? These look like three mysteries. They are one fact wearing three costumes: <strong>Claude thinks in tokens, and it can only hold so many at once.</strong> This is the closest thing Claude has to laws of physics — learn them once and you will never be surprised again.</p>",
  secs: [
    { h: "Tokens: the atoms of language",
      b: "<p>Before Claude sees your message, a <strong>tokenizer</strong> chops it into tokens — common chunks of characters. «cat» is one token; «unbelievable» might be «un» + «believ» + «able»; code and rare words shatter into more pieces. Handy rules of thumb for English:</p><ul><li>1 token ≈ 4 characters ≈ ¾ of a word</li><li>100 tokens ≈ 75 words</li><li>A dense page of text ≈ 400–500 tokens; a 50-page report ≈ 25,000 tokens</li></ul><p>Tokens matter for two blunt reasons. <strong>Money:</strong> API usage is priced per million tokens, in and out — and on subscription plans, your usage allowance is consumed token by token too. <strong>Space:</strong> which brings us to the context window.</p>"},
    { h: "The context window: one desk, finite surface",
      b: "<p>The <strong>context window</strong> is the maximum number of tokens Claude can consider at once — and here is the part most people never realise: it must hold <em>everything</em>. Your current message. The entire conversation so far. Attached files. The system's own instructions. And the answer being written, which grows token by token. One desk; everything on it.</p><p>As of July 2026, Claude's standard window is <strong>200,000 tokens</strong> (roughly 500 pages), and the newest models support up to <strong>1 million tokens</strong> — around 2,500 pages, a small bookshelf. Enormous. And still finite, which produces three effects you will now recognise instantly:</p><ul><li><strong>Falling off the desk.</strong> In very long chats, the oldest material gets summarised or dropped. That name from an hour ago didn't get «forgotten» — it slid off the desk.</li><li><strong>Crowded-desk degradation.</strong> Even before the hard limit, models attend less sharply when the window is stuffed — like proofreading page 900 of a messy pile. Practical rule: quality before quantity in what you include.</li><li><strong>Every token is rent.</strong> That 200-page PDF costs money and attention on <em>every</em> subsequent turn of the conversation, because it sits on the desk the whole time.</li></ul>"},
    { h: "The five professional habits",
      b: "<p>Everything advanced users do about context reduces to five habits:</p><ul><li><strong>Fresh chat per task.</strong> A new conversation = a clean desk. Long meandering chats are where quality goes to die.</li><li><strong>Curate what you attach.</strong> Ten relevant pages beat three hundred vaguely related ones — for cost <em>and</em> accuracy.</li><li><strong>Summarise and restart.</strong> When a long chat sags, ask: «Summarise our decisions and open questions so far.» Paste that into a fresh chat and continue with a clean, dense desk.</li><li><strong>Front-load what matters.</strong> Put large reference material early and keep instructions crisp near the end (much more on placement in Lesson 3.2).</li><li><strong>Watch the meter.</strong> On paid tools you'll see usage indicators; in Claude Code the /context and /compact commands manage the desk explicitly (Track 7).</li></ul>"}
  ],
  worked: { t: "Worked example — costing a real job in tokens",
    html: "<div class='wstep'><p class='nar'><em>The job:</em> summarise a 60-page contract (≈ 30,000 tokens) and answer 10 follow-up questions. <em>I think in tokens before I think in prompts.</em></p></div><div class='wstep'><p class='nar'><em>Naive plan:</em> paste the contract, ask questions one by one in the same chat. The contract sits on the desk for all 10 turns — so input ≈ 30k tokens × 11 turns ≈ 330k tokens processed. Slow, and on the API, expensive.</p></div><div class='wstep'><p class='nar'><em>Operator plan:</em> Turn 1 — paste contract, ask for a structured 800-token brief: parties, obligations, dates, risks, <strong>with clause numbers</strong>. Then open a fresh chat, paste only the brief, and ask the 10 questions against it, dipping back to the full text only when a specific clause needs exact wording. Total ≈ 40k tokens. Same quality where it matters, ~8× cheaper and faster.</p></div><div class='wstep'><p class='nar'><em>The judgment call:</em> clause numbers in the brief are the safety rope — summaries are lossy, and the rope lets me climb back to ground truth when a question smells high-stakes. That reflex — <em>compress, but keep a path back to the source</em> — is the whole game.</p></div>"},
  lab: { where: "claude.ai",
    html: "<p>Feel the desk-space effect yourself. In a fresh chat, paste a long article (or any 2–3 pages of text), then ask:</p>" + PB("prompt", "In exactly 3 bullet points, what are the core claims of this text? Then: roughly how many tokens do you estimate this conversation has used so far, and what percentage of your context window is that? Explain the estimate.", "prompt") + "<p>Then keep the chat going with 3–4 unrelated questions, and finally ask it to quote the article's opening line from memory of the chat.</p>",
    expect: "You'll get a token estimate with the math explained — and you'll see that even a «huge» article barely dents a 200K window, while the model stays perfectly able to quote early material. Now imagine 40 documents and 200 turns: that's when the habits from this lesson start paying." },
  mistakes: [
    "<b>One eternal mega-chat for everything.</b> The #1 beginner habit. Old, irrelevant turns crowd the desk and drag quality down. New task → new chat.",
    "<b>Attaching the whole folder «just in case».</b> Every irrelevant page costs money and dilutes attention on every turn. Curate first.",
    "<b>Blaming «bad memory» instead of managing context.</b> Claude has no memory <em>between</em> chats by default (Lesson 4.3 covers the memory features that change this) — and within a chat, the window is the memory.",
    "<b>Forgetting the answer needs desk space too.</b> Asking for a 5,000-word report when the window is nearly full guarantees a truncated or shallow result."
  ],
  quiz: [
    { q: "A 150-word paragraph is roughly how many tokens?",
      opts: ["About 15", "About 50", "About 200", "About 1,500"],
      a: 2,
      why: ["Far too low — that would be ~11 words' worth.", "Too low — 50 tokens is only ~38 words.", "Correct. Words ÷ 0.75 ≈ tokens, so 150 words ≈ 200 tokens. The ¾-word rule gets you close enough for planning.", "That's ~10× too high — 1,500 tokens is roughly 1,100 words, several pages."] },
    { q: "Which of these does NOT have to fit inside the context window?",
      opts: ["The conversation so far", "The files you attached", "The answer Claude is currently writing", "Claude's training data"],
      a: 3,
      why: ["The whole visible conversation rides on the desk every turn.", "Attachments are converted to tokens and occupy the window for the rest of the chat.", "The response streams into the same window as it's generated — output rents desk space too.", "Correct. Training data shaped the model's weights long ago; it isn't loaded into your window. The window holds only your session's material."] },
    { q: "Deep into a 3-hour chat, Claude mixes up details you established early on. What's the most likely cause and best fix?",
      opts: ["The model is broken — report a bug", "Early material slid off or got diluted in a crowded window — ask for a summary of decisions, then continue in a fresh chat", "You should type in ALL CAPS so it pays attention", "Switch to a completely different AI"],
      a: 1,
      why: ["Not a bug — it's the physics of finite context, and it's manageable.", "Correct. Summarise-and-restart is the professional move: compress the chat's real content into a dense brief and give it a clean desk.", "Volume isn't attention. Position and window hygiene are.", "Every LLM on Earth has a finite context window — the habit transfers; the problem follows."] },
    { q: "Why do professionals attach 10 curated pages instead of a 300-page dump, even though 300 pages fits in the window?",
      opts: ["Claude refuses files over 10 pages", "Purely superstition", "Relevant-only context is cheaper AND gets sharper attention — stuffing the desk dilutes focus", "Fewer pages upload faster, that's all"],
      a: 2,
      why: ["No such refusal — the window happily holds hundreds of pages.", "It's measurable, not superstition: needle-in-haystack quality drops as windows fill with noise.", "Correct. Tokens are rent and attention is finite — curation buys both accuracy and economy. This becomes a literal business skill in the API tracks.", "Upload speed is trivial; the real costs are attention and per-token pricing."] }
  ],
  prac: [
    { tag: "warm", q: "Estimate the tokens in: (a) a tweet (~50 words), (b) a 2-page memo (~800 words), (c) a 300-page book (~90,000 words).",
      sol: "<b>≈ 67, ≈ 1,070, ≈ 120,000.</b> (words ÷ 0.75). Notice (c): a full book fits in a 200K window with room to spare — and would nearly fill older 128K-class models. Size intuition is a superpower when you start paying per token." },
    { tag: "transfer", q: "You're using Claude to prep for a job interview across 5 sessions this week. Design your context strategy using this lesson's habits.",
      sol: "<b>One good design:</b> Session 1 — build a «briefing doc»: your CV summary, the job description, your stories, weak areas (ask Claude to compress it, ~600 tokens). Sessions 2–5 — fresh chat each time, paste the briefing doc first, then do one focused drill (behavioural, technical, salary, mock). End each session by asking for 3 lines to append to the briefing doc. Clean desk every day; compounding memory in a doc <em>you</em> control." },
    { tag: "stretch", q: "The newest models offer 1M-token windows. Give one task that genuinely needs it, and one task where using it would be a mistake even though it fits.",
      sol: "<b>Genuinely needs it:</b> cross-referencing an entire codebase or a full litigation file where any page may reference any other — the connections ARE the task. <b>Mistake:</b> answering one specific question by dumping an entire wiki «because it fits» — you'd pay for a million tokens of rent and <em>lower</em> your accuracy versus retrieving the 5 relevant pages. Fit is not the bar; relevance is." }
  ],
  recap: "Tokens ≈ ¾ of a word and everything rides in one finite context window — so curate what you include, restart long chats with summaries, and think in tokens before you think in prompts.",
  bridge: "Now that you know what fills the window, meet the minds that read it: four models with very different brains, speeds and prices — and a simple rule for choosing.",
  deep: "<p><strong>Why ~¾ of a word?</strong> Tokenizers (byte-pair encoding family) build a vocabulary of the most frequent character sequences in training data. Frequent English words earn a single token; rare words assemble from sub-pieces. Consequences worth knowing: non-English languages often cost <em>more</em> tokens per sentence (fewer of their sequences made the vocabulary); code tokenizes surprisingly well; and token boundaries explain classic stumbles like counting letters in a word — the model sees «strawberry» as chunks, not as ten letters. Anthropic's 2026 models introduced a new tokenizer that packs roughly 30% more text into the same token budget — a quiet change that directly cut effective costs, and a good example of why an operator keeps an eye on release notes.</p>"
};

/* ------------------------------------------------ 1.3 */
L["1.3"] = {
  sub: "Fable, Opus, Sonnet, Haiku — four brains, four price tags. Choosing well is the difference between overpaying 10× and under-delivering.",
  breath: "Claude comes as a family — flagship Fable 5 for the hardest work, Opus 4.8 for heavyweight reasoning, Sonnet 5 as the everyday workhorse, Haiku 4.5 for fast cheap volume — and pros deliberately match the model to the job.",
  asOf: true,
  hook: "<p>A carpenter doesn't own one hammer. She owns a framing hammer, a finish hammer, and a tack hammer — and reaching for the right one is half of looking professional. «Which model should I use?» is the single most-asked practical Claude question, and by the end of this lesson you'll answer it on reflex — including the version where the answer saves a client real money.</p>",
  secs: [
    { h: "Meet the family (as of July 2026)",
      b: "<p>Model names follow a pattern: a <strong>family name</strong> (tier of capability) plus a <strong>version number</strong>. The current line-up:</p><table><tr><th>Model</th><th>Character</th><th>Reach for it when…</th></tr><tr><td><strong>Claude Fable 5</strong></td><td>The flagship. Deepest reasoning, adaptive thinking built in, 1M-token context.</td><td>The hardest problems: complex agents, subtle analysis, high-stakes writing, long autonomous work.</td></tr><tr><td><strong>Claude Opus 4.8</strong></td><td>Heavyweight reasoner, a notch below the flagship, priced accordingly.</td><td>Serious reasoning and coding when you want premium quality at a friendlier rate.</td></tr><tr><td><strong>Claude Sonnet 5</strong></td><td>The workhorse: near-frontier quality, fast, mid-priced.</td><td>Daily driver for writing, coding, analysis — the default when unsure.</td></tr><tr><td><strong>Claude Haiku 4.5</strong></td><td>Small, very fast, very cheap.</td><td>Volume work: classification, extraction, simple chat, first-pass drafts.</td></tr></table><p>Names and numbers will roll forward after this course's July 2026 snapshot — the <em>tiers</em> (flagship / heavyweight / workhorse / fast-and-cheap) are the durable idea. Current list: <strong>docs.claude.com → models</strong>.</p>"},
    { h: "What you actually trade off",
      b: "<p>Three dials move together:</p><ul><li><strong>Capability.</strong> Bigger models hold more complex instructions, reason more reliably, and fail more gracefully. On simple tasks, the gap is often invisible — that's the money insight.</li><li><strong>Speed.</strong> Haiku answers while Fable is still thinking. For interactive products and high-volume pipelines, latency is a feature.</li><li><strong>Price.</strong> API list prices (per million tokens, July 2026): Fable 5 about $10 in / $50 out; Opus 4.8 about $5 / $25; Sonnet 5 about $2 / $10 introductory; Haiku 4.5 about $0.80 / $4. Read that spread again: <strong>the flagship costs roughly 12× the small model.</strong> On subscriptions the same logic shows up as how fast you burn your usage allowance.</li></ul><p>There's a fourth dial on modern models: <strong>thinking</strong>. Newer Claude models can spend extra tokens reasoning before answering — the flagship does this <em>adaptively</em>, deciding how hard to think based on the problem. Deeper thinking = better answers on hard problems = more tokens. You'll meet the controls in Lesson 2.5.</p>"},
    { h: "The operator's selection rule",
      b: "<p>Memorise this and you're better than most working professionals:</p><ul><li><strong>Default to the workhorse (Sonnet).</strong> It clears the bar for ~80% of real tasks.</li><li><strong>Escalate on failure or stakes.</strong> If the workhorse's answer wobbles — or the task is high-stakes (legal wording, architecture decisions, client deliverables) — rerun on Opus/Fable. Paying 5× on the 20% of tasks that deserve it is cheap.</li><li><strong>Descend for volume.</strong> Doing something simple 10,000 times? Haiku. This is how profitable AI products are built — Track 9 turns it into arithmetic.</li><li><strong>Mix models in one system.</strong> The pro pattern: Haiku sorts and filters, Sonnet drafts, the flagship reviews the top 5%. Same quality where it counts, fraction of the cost.</li></ul>"}
  ],
  worked: { t: "Worked example — one client project, three models",
    html: "<div class='wstep'><p class='nar'><em>The job:</em> a client has 8,000 customer-support emails. They want each tagged by topic and urgency, the 200 angriest summarised, and one executive report on systemic problems.</p></div><div class='wstep'><p class='nar'><em>My split, and why:</em> tagging 8,000 emails is simple pattern work ×8,000 — <strong>Haiku</strong>, because per-unit price dominates and capability headroom would be wasted. Summarising 200 angry emails needs nuance (sarcasm, mixed complaints) — <strong>Sonnet</strong>. The exec report is one artifact the client's leadership will act on — <strong>flagship</strong>, because a single brilliant document justifies premium tokens.</p></div><div class='wstep'><p class='nar'><em>The arithmetic instinct:</em> all-flagship would cost roughly 10× my mixed pipeline and improve only the piece that was already flagship-grade. All-Haiku would be 10× cheaper still — and produce a mushy report that costs me the client. <em>Match the metal to the load.</em></p></div>"},
  lab: { where: "claude.ai — model picker",
    html: "<p>In claude.ai, find the model selector (near the message box). Run the same two prompts on two different models — one fast/small, one top-tier:</p>" + PB("prompt A — simple", "Rewrite this sentence to be friendlier: 'Your payment is late. Pay immediately or service stops.'", "prompt") + PB("prompt B — hard", "I sell handmade candles. Wholesale cost ₹90, I sell at ₹250, Instagram ads bring customers at ₹120 each, and 30% of customers reorder twice a year. Is paid advertising profitable for me? Walk through the math step by step, state your assumptions, then give a verdict and one lever that would most improve the economics.", "prompt"),
    expect: "On prompt A the models are nearly interchangeable — capability headroom wasted. On prompt B the bigger model's answer is visibly better structured, with cleaner assumptions and a sharper verdict. You just felt the selection rule in your hands." },
  mistakes: [
    "<b>Flagship-for-everything.</b> Burns money and usage allowance on work a cheaper model does identically. The skill isn't using the best model — it's knowing when it matters.",
    "<b>Cheapest-for-everything.</b> The mirror error: one hallucinated clause in a client contract erases a year of Haiku savings.",
    "<b>Never re-evaluating.</b> Models improve in leaps. The task Sonnet fumbled last year may be trivial for this year's Sonnet — re-test your assumptions each release.",
    "<b>Comparing models on one prompt.</b> Single anecdotes mislead; differences show up over a handful of varied, realistic tasks. (Track 3 teaches proper evals.)"
  ],
  quiz: [
    { q: "Client work: classify 50,000 product reviews as positive/negative/neutral. Which model and why?",
      opts: ["Fable 5 — always use the best", "Haiku 4.5 — simple task × huge volume means per-unit price dominates", "Opus 4.8 — reviews need heavyweight reasoning", "Refuse the job — too many reviews"],
      a: 1,
      why: ["'Always the best' is the most expensive habit in AI — sentiment tagging doesn't use flagship depth, you'd pay ~12× for nothing.", "Correct. Simple, repetitive, high-volume = the small fast model. This exact decision is where API profit margins live.", "Basic sentiment is pattern-matching the small models handle reliably — heavyweight reasoning is wasted here.", "50,000 items is a completely routine batch job — Track 9 shows you how to run it."] },
    { q: "Roughly how does flagship API pricing compare to the smallest model's (July 2026)?",
      opts: ["About the same", "About 2× more", "Around 12× more", "About 100× more"],
      a: 2,
      why: ["The spread is enormous — that's the whole reason model choice is a money skill.", "Even flagship vs the mid-tier workhorse is bigger than 2×.", "Correct — ~$10/$50 vs ~$0.80/$4 per million tokens. A pipeline built on the wrong tier can cost an order of magnitude extra.", "Not 100× — but 12× compounds brutally at scale."] },
    { q: "Sonnet gave a shaky answer on a tricky contract clause you're sending a client. The operator move is:",
      opts: ["Ship it — good enough", "Re-run on a higher-tier model, because stakes and observed failure both trigger escalation", "Ask Sonnet the identical question five times", "Give up on AI for legal text"],
      a: 1,
      why: ["'Client-facing' + 'shaky' is exactly the situation escalation exists for.", "Correct. Escalate on failure or stakes — premium tokens on the 20% that matters is the cheapest insurance you'll ever buy. (And verify against the source — Lesson 1.6.)", "Re-rolling the same model mostly re-rolls the same weaknesses; changing the model changes the odds.", "AI handles contract analysis well when driven by someone with your (growing) skill — the fix is tooling, not surrender."] }
  ],
  prac: [
    { tag: "warm", q: "Assign a tier (flagship / heavyweight / workhorse / fast-cheap) to: (a) naming 500 spreadsheet columns sensibly, (b) drafting your wedding speech, (c) architecting a startup's database, (d) tagging 20k tweets by topic.",
      sol: "(a) <b>fast-cheap</b> — simple × volume. (b) <b>workhorse</b>, escalate to flagship if it matters deeply to you — emotional nuance rewards capability. (c) <b>flagship/heavyweight</b> — one decision with years of consequences. (d) <b>fast-cheap</b> — classic Haiku territory." },
    { tag: "transfer", q: "Design a three-model pipeline for producing a weekly industry newsletter from 300 articles: which model reads/filters, which drafts, which polishes — and what does each step cost in capability terms?",
      sol: "<b>One strong design:</b> Haiku scores all 300 articles for relevance (volume filter) → Sonnet summarises the top 15 and drafts sections (quality writing at scale) → flagship does one editorial pass for voice, insight and the intro essay (single high-leverage artifact). You've just designed your first multi-model system — Track 10 makes these run automatically." },
    { tag: "stretch", q: "A founder says: «We'll launch on the flagship for quality, then silently swap to the cheapest model to cut costs once users are hooked.» Give one technical and one business critique.",
      sol: "<b>Technical:</b> outputs will visibly change (depth, formats, edge-case handling) — silent swaps break prompts tuned on the big model; you need eval suites proving parity per task first. <b>Business:</b> users notice quality cliffs and churn silently; honest tiering (fast vs deep modes, priced accordingly) converts the same economics into a feature instead of a betrayal." }
  ],
  recap: "Default to the workhorse, escalate on stakes or failure, descend to the small model for volume, and mix tiers inside one pipeline — model choice is a money skill, not trivia.",
  bridge: "You know the brains. Now the bodies: Claude lives in seven different places — app, Cowork, Code, Chrome, Excel, Slack, API — and picking the right surface is the next reflex to install.",
  deep: "<p><strong>Why do smaller models exist at all?</strong> Serving cost scales with parameters and compute per token. Anthropic (like all labs) distils and optimises smaller models to sit on the efficient frontier: maximum capability per dollar per millisecond at each tier. Two frontier facts worth knowing in 2026: <em>adaptive thinking</em> means the flagship dynamically allocates reasoning compute per query — blurring the old fixed-tier logic; and <em>capability lag</em> keeps collapsing — today's workhorse roughly matches the flagship of ~a year ago. Strategic consequence: any workflow you build with clean model-selection logic gets automatically better and cheaper every year without you lifting a finger.</p>"
};

/* ------------------------------------------------ 1.4 */
L["1.4"] = {
  sub: "One brain, seven bodies. The map of every place Claude lives — and the fastest way to know which one your task wants.",
  breath: "The same Claude models power the chat app, Cowork, Claude Code, the Chrome extension, Excel, Slack/Microsoft 365, and the developer API — surfaces differ in what they can touch (files, browser, terminal, your code), not in intelligence.",
  asOf: true,
  hook: "<p>Electricity is one thing, but it reaches you as wall sockets, car batteries, and phone cells — same power, different fittings for different jobs. Claude in 2026 is the same: one family of models, delivered through seven surfaces. People who know only the chat app are using maybe 20% of what their subscription can do. This lesson hands you the whole map; Phases C and D explore each territory in depth.</p>",
  secs: [
    { h: "The seven surfaces",
      b: "<table><tr><th>Surface</th><th>What it is</th><th>Its superpower</th></tr><tr><td><strong>Claude app</strong> (web · desktop · mobile)</td><td>The conversation home: chat, Projects, files, Artifacts, Research, connectors, Skills.</td><td>Thinking together: writing, analysis, learning, planning.</td></tr><tr><td><strong>Cowork</strong></td><td>Agentic workspace inside the app — give Claude folders and an outcome; it works through multi-step tasks, even after you close the laptop.</td><td>Delegation: finished documents, organised files, synthesized research.</td></tr><tr><td><strong>Claude Code</strong> (terminal · desktop · web)</td><td>An agent in your development environment: reads files, edits, runs commands, tests, commits.</td><td>Building software — and, quietly, any file-heavy technical work.</td></tr><tr><td><strong>Claude for Chrome</strong></td><td>Browser extension: Claude sees pages, clicks, types, fills forms.</td><td>Web-bound work: research across sites, form-filling, web-app chores.</td></tr><tr><td><strong>Claude for Excel</strong></td><td>Add-in inside spreadsheets: reads workbooks, explains formulas, edits with cell-level citations.</td><td>Spreadsheet jobs where the spreadsheet must stay a spreadsheet.</td></tr><tr><td><strong>Claude in Slack / Microsoft 365</strong></td><td>Claude joins your team's chat and documents.</td><td>Shared team assistant where collaboration already happens.</td></tr><tr><td><strong>Claude API + Agent SDK</strong></td><td>The raw programmable brain, for software you build.</td><td>Products and automation serving other people — where businesses get built.</td></tr></table>"},
    { h: "One skill, compounding everywhere",
      b: "<p>The map explains why this course is ordered the way it is. Everything you learn in Phase B — prompting — transfers to <em>all seven surfaces</em>, because they share the same brains. Learn to write one great instruction and you've upgraded your chat sessions, your Cowork delegations, your Claude Code commands, and the system prompts of products you'll ship. Skills compound; surfaces multiply them.</p><p>The deeper pattern across surfaces is <strong>reach</strong>: what can Claude touch? Chat sees your words and files you hand it. Cowork reaches folders and connected apps. Code reaches your repository and terminal. Chrome reaches the live web. The API reaches whatever you wire it to. More reach = more leverage = more responsibility — which is why permission systems appear on every agentic surface, and why we treat them seriously from Lesson 5.2 onward.</p>"},
    { h: "The 10-second surface picker",
      b: "<ul><li>Thinking, writing, learning, one-off analysis → <strong>the app</strong>.</li><li>«Here are my files, come back with finished work» → <strong>Cowork</strong>.</li><li>Anything in a repository, terminal, or codebase → <strong>Claude Code</strong>.</li><li>The task lives across websites you'd click through → <strong>Chrome</strong>.</li><li>The deliverable IS a workbook → <strong>Excel</strong>.</li><li>Teammates need to see and join in → <strong>Slack / M365</strong>.</li><li>It must run 1,000×, on a schedule, or inside your product → <strong>API</strong>.</li></ul><p>Wrong-surface pain is real: pasting code file-by-file into chat (Claude Code exists), copying data cell-by-cell (Excel exists), doing the same report manually every Monday (Cowork's scheduled tasks exist). If a task feels clunky, you're probably on the wrong square of the map.</p>"}
  ],
  worked: { t: "Worked example — one freelancer, five surfaces, one Tuesday",
    html: "<div class='wstep'><p class='nar'><em>Meet Ria, freelance marketing consultant.</em> 9:00 — client sends 30 survey PDFs. She opens <strong>Cowork</strong>, points it at the folder: «extract every response into one spreadsheet, flag the angry ones.» It grinds while she makes coffee.</p></div><div class='wstep'><p class='nar'>9:40 — she drafts the strategy memo in the <strong>app</strong>, in a Project holding this client's brand voice and past work. 11:00 — she needs competitor pricing from six websites; <strong>Chrome</strong> walks them and builds the comparison. 12:00 — the client's messy budget workbook needs restructuring without breaking formulas: <strong>Excel</strong>, with citations to every changed cell.</p></div><div class='wstep'><p class='nar'>2:00 — her recurring Monday report? She's realised it's the same shape every week, so she's having <strong>Claude Code</strong> build a small script version she can trigger — first step toward the productized service she'll sell in Track 11. <em>Same brain all day; five fittings. That fluency is what this course builds.</em></p></div>"},
  lab: { where: "Claude app",
    html: "<p>Ask Claude to be your guide to its own ecosystem — and make it concrete to <em>your</em> life:</p>" + PB("prompt", "Here are 6 recurring tasks in my life: [LIST YOURS — e.g., weekly status report for my boss, tracking expenses, researching suppliers, replying to customer emails, updating a price sheet, planning content]. For each, tell me which Claude surface (chat app, Cowork, Claude Code, Chrome extension, Excel add-in, Slack, or API) fits best and why, and rank the 6 by how much time I'd realistically save per month. Be honest about which ones aren't worth automating.", "prompt"),
    expect: "A personalised map of your own workload — and usually one surprise («wait, that's automatable?»). Save this answer: it becomes your project list for Phases C and D." },
  mistakes: [
    "<b>Living only in chat.</b> The most common ceiling. Chat is the front door, not the house.",
    "<b>Assuming surfaces differ in intelligence.</b> Same models throughout — surfaces differ in reach (what Claude can touch), not brains.",
    "<b>Using an agentic surface for a 30-second question.</b> Overhead without payoff — quick questions belong in chat.",
    "<b>Ignoring permissions on agentic surfaces.</b> Reach without care is risk; every serious surface has permission controls, and pros actually read them (Lessons 5.2, 10.6)."
  ],
  quiz: [
    { q: "«Take this folder of 80 invoices and produce one clean expense spreadsheet by category» — best surface?",
      opts: ["Chat app, pasting invoices one by one", "Cowork — point it at the folder and describe the finished outcome", "Chrome extension", "Slack"],
      a: 1,
      why: ["Eighty manual pastes is exactly the clunky pain that signals wrong-surface.", "Correct — folders in, finished work out, multi-step in between: Cowork's home turf.", "Chrome is for tasks living on websites, not local folders.", "Slack is a team surface, not a file-crunching one."] },
    { q: "What's the real difference between Claude in the app and Claude via the API?",
      opts: ["The API model is smarter", "Same brains, different reach and packaging — the API is programmable for software you build; the app is the human interface", "The app is always more expensive", "They're unrelated products"],
      a: 1,
      why: ["Same model family both ways.", "Correct — surfaces are fittings around the same intelligence. The API's superpower is running ×1,000 inside your product.", "Pricing models just differ: flat subscription vs pay-per-token. Which is cheaper depends entirely on usage (Lesson 9.7).", "One ecosystem, one family of brains."] },
    { q: "A friend manually re-does the same 2-hour competitor-pricing check across 6 websites every Friday. Your best advice?",
      opts: ["Type faster", "That's web-bound repetitive work — Claude for Chrome can walk the sites, and a scheduled Cowork task could make it weekly-automatic", "Only the API can do this", "Claude can't touch the web"],
      a: 1,
      why: ["Speed of suffering is still suffering.", "Correct — browser reach for the site-walking, scheduling for the every-Friday part. This exact pattern appears in the money tracks as a sellable service.", "The API could — but heavier machinery than needed; the point of the map is matching effort to task.", "Between web search, Chrome, and Cowork's browser automation, Claude very much touches the web."] }
  ],
  prac: [
    { tag: "warm", q: "From memory, name the seven surfaces and one superpower each.",
      sol: "App (thinking together) · Cowork (delegated finished work) · Claude Code (repos & terminal) · Chrome (the live web) · Excel (workbooks) · Slack/M365 (team spaces) · API (products at scale). Missed any? Ten-second re-read — this map organises the entire course." },
    { tag: "transfer", q: "A small accounting firm asks where to start with Claude. They live in Excel and email, drown in client PDFs at tax time, and repeat the same monthly reports. Prescribe surfaces in order of adoption.",
      sol: "<b>A sane rollout:</b> 1) App + Projects for drafting client emails and answering tax questions (lowest friction, instant value). 2) Excel add-in — they live there; citations build trust. 3) Cowork for the PDF mountains and monthly report as a scheduled task. 4) Later, if reports are identical in shape: a Claude Code-built script. Order by friction-to-value, not by what's coolest." },
    { tag: "stretch", q: "Reach = leverage = risk. For Chrome and Cowork, name one great use and one thing you would deliberately NOT let it do unattended, and why.",
      sol: "<b>Chrome:</b> great — multi-site research compilation; not unattended — anything involving payments or logged-in destructive actions (a malicious page could try to manipulate the agent — prompt injection, Lesson 8.5/10.6). <b>Cowork:</b> great — reorganising a project folder with report generation; not unattended — bulk deletion or sending external emails without review. The habit: match autonomy to reversibility." }
  ],
  recap: "One brain, seven bodies: chat for thinking, Cowork for delegation, Code for repos, Chrome for the web, Excel for workbooks, Slack for teams, API for scale — and clunkiness means wrong surface.",
  bridge: "Surfaces cost money. Next: the plans — what's free, what Pro and Max actually buy you, and a clean way to decide what YOU should pay for.",
  deep: "<p><strong>Why is everyone shipping «surfaces» in 2026?</strong> The industry realised the model is only half the product — the other half is <em>context and actuation</em>: what the AI can see and touch. A model with your folder beats a smarter model without it. That's why Anthropic built Cowork, Chrome, Excel and the connector ecosystem, and why the Model Context Protocol (Track 8) became the standard plumbing. Strategic read: capability differences between top labs keep narrowing; <em>integration</em> — who sits closest to your real work — is where the war is fought. Your skill mirrors this: an operator who can wield all seven surfaces is worth multiples of a chat-only user with the same subscription.</p>"
};

/* ------------------------------------------------ 1.5 */
L["1.5"] = {
  sub: "Free, Pro, Max, Team, Enterprise — and the API's pay-per-use meter. What each actually buys, and a decision rule that doesn't waste your money.",
  breath: "Claude pricing is a ladder — Free to try, Pro (~$17–20/mo) for serious individual use with Cowork and Claude Code, Max ($100+/mo) for heavy daily leverage, Team/Enterprise for companies — plus the separate pay-per-token API; pay for the rung whose ceiling you actually hit.",
  asOf: true,
  hook: "<p>Here's a question that sounds financial but is really strategic: <em>what is an hour of your time worth, and how many hours a month can Claude give you back?</em> Answer that and the pricing page reads itself. This lesson walks the ladder rung by rung — with July 2026 numbers — and gives you the rule professionals use. (Prices shift; the logic doesn't. Current numbers always live at <strong>claude.com/pricing</strong>.)</p>",
  secs: [
    { h: "The ladder, rung by rung (July 2026)",
      b: "<table><tr><th>Plan</th><th>Price</th><th>What it really means</th></tr><tr><td><strong>Free</strong></td><td>$0</td><td>Real Claude, capped usage that resets in 5-hour windows. Web, desktop, mobile; files, web search, basic features. Perfect for learning — you can complete a large share of this course on it.</td></tr><tr><td><strong>Pro</strong></td><td>~$17/mo annual (~$20 monthly)</td><td>The serious-individual rung: at least 5× Free usage, unlimited Projects, Research mode, connectors, more model choice — and the agentic surfaces: <strong>Cowork and Claude Code</strong>. This is where most of this course's power unlocks.</td></tr><tr><td><strong>Max</strong></td><td>from $100/mo (5×) to a 20× tier</td><td>For people whose workday runs on Claude: 5–20× Pro usage, higher output limits, priority access, earliest features. Buy when you're hitting Pro's ceiling and the lost time costs more than the upgrade.</td></tr><tr><td><strong>Team</strong></td><td>~$20–25/seat (standard) · ~$100–125 (premium seats)</td><td>Companies: central billing, admin controls, collaboration; premium seats carry the heavy Cowork/Code allowances.</td></tr><tr><td><strong>Enterprise</strong></td><td>custom / seat + usage</td><td>SSO, audit logs, compliance controls, data-governance machinery.</td></tr></table><p>Two facts people miss: <strong>your subscription's usage is a token budget in disguise</strong> — heavy Cowork and Claude Code sessions consume it much faster than chat (they process far more tokens per task). And <strong>the API is a separate meter entirely</strong> (per-token, Lesson 1.3's prices) — subscriptions don't include API credits, and vice versa.</p>"},
    { h: "The decision rule",
      b: "<p>Work the ladder like an operator:</p><ul><li><strong>Start Free, but push it hard.</strong> Not «try a few questions» — attempt real work until you personally feel the usage ceiling. Now you know what the next rung buys: <em>your</em> bottleneck, not a feature list.</li><li><strong>Upgrade to Pro when Claude touches money or career.</strong> The arithmetic is absurd at almost any wage: if Pro saves two hours a month, it's paid for itself several times over. And Cowork + Claude Code aren't luxuries — they're where the leverage lives (Phases C–D).</li><li><strong>Max is a business decision, not a fan purchase.</strong> Buy the 5× tier when you're regularly rate-limited on Pro and waiting costs you billable time. The 20× tier is for Claude-all-day operators — by Track 11 you may be one.</li><li><strong>The API is for builders and volume</strong> — you pay per token, no session caps, and it powers things you ship to others. Many operators run both: a subscription for their hands-on work, API for their products. Track 9 does the full cost math.</li></ul><div class='callout gold'><b>The reframe that matters:</b> stop asking «is $20 expensive?» and ask «what does one reclaimed workday per month earn me?» In India as much as in the US, the subscription question is really a wage-arbitrage question — and for freelancers in Track 11, plan costs become a line item their <em>clients</em> effectively pay for.</div>"}
  ],
  worked: { t: "Worked example — three people, three right answers",
    html: "<div class='wstep'><p class='nar'><em>Student, ₹0 budget:</em> stays Free. Uses 5-hour reset windows deliberately (morning study block, evening block), keeps chats lean (Lesson 1.2 habits stretch a capped allowance surprisingly far). Right answer: <strong>Free, played skilfully.</strong></p></div><div class='wstep'><p class='nar'><em>Freelance designer, ₹60k/month income:</em> Claude drafts proposals, client emails, and project briefs — maybe 15 hours saved monthly. ₹1,700-ish for Pro vs 15 hours billable at ₹800/hr: the plan costs ~14% of one recovered hour. Right answer: <strong>Pro, yesterday.</strong> Upgrade trigger for Max: the day rate-limits interrupt paid work twice in one week.</p></div><div class='wstep'><p class='nar'><em>Two-founder startup shipping an AI feature:</em> founders' daily driving = Pro/Max seats; the product itself = <strong>API</strong> with a model-mix pipeline (Haiku volume, Sonnet quality — Lesson 1.3). Two meters, deliberately separate, each measured against what it earns. <em>That's the whole discipline: every rung must out-earn its price.</em></p></div>"},
  lab: { where: "claude.ai + pricing page",
    html: "<p>Do a 10-minute personal audit. Open <a href='https://claude.com/pricing' target='_blank' rel='noopener'>claude.com/pricing</a> in one tab (check today's real numbers against this lesson), then ask Claude:</p>" + PB("prompt", "Help me decide which Claude plan I should be on. My situation: [your work/study], [hours per week of writing/analysis/coding/admin], [what an hour of my time is worth, roughly], [current AI usage and where I hit limits, if ever]. Model the decision as: hours realistically saved per month × my hourly value vs plan cost. Give me a verdict, the single metric to watch, and the specific trigger that should make me upgrade (or downgrade) later.", "prompt"),
    expect: "A personal, numbers-based recommendation with an upgrade trigger — pricing decided like an operator, not a fan. Revisit after Track 5 (Cowork usually changes the math)." },
  mistakes: [
    "<b>Deciding from the feature table instead of felt limits.</b> Push Free until it squeaks; then you know exactly what you're buying.",
    "<b>Confusing subscription and API.</b> Two separate meters. Pro doesn't grant API credits; API keys don't raise your app limits.",
    "<b>Forgetting agentic surfaces burn allowance faster.</b> A Cowork afternoon can consume what a week of chat wouldn't — factor it in when Phase C hooks you.",
    "<b>Set-and-forget subscriptions.</b> Recheck quarterly: your usage grows through this course, and Anthropic reshuffles plans. Yesterday's right rung isn't automatically today's."
  ],
  quiz: [
    { q: "Which plan is the first to include the full agentic duo — Cowork and Claude Code — for an individual?",
      opts: ["Free", "Pro", "Only Max", "Only Enterprise"],
      a: 1,
      why: ["Free is real Claude but the agentic workhorses live behind the paid line.", "Correct — Pro is the rung where this course's biggest levers (Phases C and D) fully unlock, which is why it's the default recommendation for serious learners.", "Max raises the ceilings; the capabilities arrive at Pro.", "Team/Enterprise are about seats and governance, not the unlock point."] },
    { q: "A freelancer bills ₹800/hour and estimates Claude Pro saves 10 hours a month. The plan costs about ₹1,700/month. What's the honest framing?",
      opts: ["An expense to minimise — stay Free", "About ₹8,000 of recovered billable value for ₹1,700 — roughly a 4–5× return", "Worth it only if she uses every feature", "Impossible to reason about"],
      a: 1,
      why: ["Minimising the meter while losing 10 billable hours is stepping over rupees to save paise.", "Correct — and this exact arithmetic (time value vs plan cost) is the professional's pricing lens for every tool, not just Claude.", "Value comes from hours recovered, not feature-checklist completion. Two features used deeply can justify ten ignored.", "It's a two-line multiplication — the reframe makes it easy."] },
    { q: "Your app subscription just hit its session limit mid-task. Which statement is TRUE?",
      opts: ["Your API key is also now blocked", "Subscription and API are separate meters — API calls still work and bill per token", "Buying API credits raises your app limits", "Limits never reset"],
      a: 1,
      why: ["Separate systems, separate meters.", "Correct — many operators keep both precisely so a ceiling on one doesn't stop the day's work.", "It doesn't — they're independent products.", "App limits reset on rolling windows (hence the 5-hour rhythm Free users learn to surf)."] }
  ],
  prac: [
    { tag: "warm", q: "Sketch the ladder from memory: five plan rungs, rough prices, and the one-line meaning of each.",
      sol: "Free $0 (real but capped) · Pro ~$17–20 (serious individual; Cowork + Code) · Max $100+ (5–20× ceilings, priority) · Team ~$20–25/seat std, ~$100–125 premium (company plumbing) · Enterprise custom (governance). API = separate per-token meter." },
    { tag: "transfer", q: "Advise a 4-person marketing agency currently sharing one Pro login (against the rules and constantly rate-limited): what should they actually buy, and why?",
      sol: "<b>Team plan, 4 seats</b> — likely 2 premium seats (the two people doing heavy Cowork/report work) + 2 standard. They get legit multi-user access, admin controls, shared Projects, and no more tripping over one account's limits. Cost ~$240–300/mo vs their combined billable time: the arithmetic from this lesson closes the sale in one line." },
    { tag: "stretch", q: "You're launching a side-product on the API while personally living on Pro. Design your first month's budget guardrails so a bug can't surprise-bill you.",
      sol: "<b>Minimum sane setup:</b> set a hard monthly spend limit in the API console; alert thresholds at 50/80%; per-user rate caps in your app; Haiku-first model mix with escalation only on need (Lesson 1.3); and a kill-switch env flag your app checks. Then watch real cost-per-user for a week before any launch push. Track 9 turns this into a full playbook." }
  ],
  recap: "Pay for the rung whose ceiling you actually hit: Free to learn, Pro when Claude touches income, Max when waiting costs more than upgrading — and remember the API is a separate meter for things you build.",
  bridge: "You now know the machine, the models, the map, and the money. One habit remains — the one that separates professionals from casualties: knowing when Claude might be wrong, and catching it before it costs you.",
  deep: "<p><strong>Why do labs sell both subscriptions and per-token APIs?</strong> Subscriptions convert unpredictable inference costs into predictable revenue and fund the free tier that feeds adoption; APIs price marginal compute directly and scale with customer success. For you there's an arbitrage insight: subscription plans effectively sell tokens below API list price for heavy interactive users (flat fee, high usage), while the API wins for spiky, programmatic, or product workloads. That's why the two-meter setup — subscription for your hands, API for your products — is the standard operator configuration by the end of this course. One more 2026 wrinkle: usage-based «premium seats» on Team plans exist precisely because agentic workloads (Cowork/Code) consume order-of-magnitude more tokens than chat — companies budget seats by workload type now, a detail that wins you credibility in Track 11 client conversations.</p>"
};

/* ------------------------------------------------ 1.6 */
L["1.6"] = {
  sub: "Claude will sometimes be confidently wrong. Professionals aren't the people who never see hallucinations — they're the people hallucinations can't hurt.",
  breath: "Because Claude composes rather than looks up, it can produce fluent falsehoods — so pros sort outputs by stakes and checkability, force sources and uncertainty into the open, and verify anything that could cost money, reputation or safety.",
  hook: "<p>A lawyer once filed a brief containing court cases that didn't exist — an AI invented them, complete with convincing citations, and the lawyer didn't check. He became a global news story. Same year, thousands of professionals quietly shipped excellent AI-assisted work with zero incidents. The difference wasn't the model. It was a <strong>discipline</strong> — teachable in one lesson, practised for a career. This is that lesson, and it's the last piece of your foundation.</p>",
  secs: [
    { h: "Why fluent falsehood is the natural failure mode",
      b: "<p>Recall Lesson 1.1: Claude <em>composes</em> answers from patterns; it doesn't retrieve them from a fact vault. When the pattern is strong and the training data rich, composition lands on truth with high reliability. When you ask for something sparse, specific, or after its knowledge cutoff — an exact quote, a niche statistic, a 2026 price, an obscure paper — the machinery still produces <em>something shaped exactly like a right answer</em>. That's a <strong>hallucination</strong>: not lying (no intent), not a glitch (no error thrown) — just prediction doing its best without ground truth. Two corollaries every operator internalises:</p><ul><li><strong>Confidence is styling, not evidence.</strong> The tone of an answer tells you nothing about its truth.</li><li><strong>Risk concentrates predictably:</strong> precise facts, numbers, quotes, citations, names, anything recent, and anything at the edge of documented knowledge. Reasoning over material <em>you supplied</em> is far safer ground.</li></ul>"},
    { h: "The triage: sort before you verify",
      b: "<p>Verifying everything is as amateur as verifying nothing. Sort every output in two seconds by two questions — <em>what does being wrong cost?</em> and <em>can I check it?</em></p><ul><li><strong>Green — creative & subjective:</strong> brainstorms, drafts, rewrites, explanations of concepts you can sanity-check. Wrongness is cheap and visible. Use freely.</li><li><strong>Yellow — factual but low-stakes:</strong> background info, summaries of supplied documents, how-to guidance. Spot-check the load-bearing claims.</li><li><strong>Red — factual and consequential:</strong> anything you'll publish, send a client, spend money on, cite, or act on medically/legally/financially. <strong>Every load-bearing fact gets verified against a primary source.</strong> No exceptions, no matter how confident the prose.</li></ul>"},
    { h: "The five defenses",
      b: "<p>Habits that make hallucinations survivable — you'll deepen each in Track 3:</p><ul><li><strong>1. Give it an out.</strong> Add: «If you're not sure, say so — I'd rather have honest uncertainty than a guess.» Permission to admit ignorance measurably reduces invention.</li><li><strong>2. Make it search.</strong> For anything recent or specific: «Search the web and cite your sources.» Claude with live sources ≫ Claude from memory. Then click the important links — checking citations beats trusting them.</li><li><strong>3. Ground it in your documents.</strong> «Answer ONLY from the attached file; quote the relevant passage for each claim.» Supplied-text answers are checkable in seconds via the quotes.</li><li><strong>4. Ask for the confidence map.</strong> «Now mark each claim: certain / likely / should-verify.» Claude is decently calibrated about its own shaky ground — the map tells you where to aim your checking minutes.</li><li><strong>5. Second pass, fresh eyes.</strong> For red-zone work: open a NEW chat, paste the output, and ask Claude to fact-check it hostile-reviewer style. A fresh context isn't anchored to defend its earlier draft. (This «generator vs critic» split becomes an engineering pattern in Tracks 3 and 10.)</li></ul>"}
  ],
  worked: { t: "Worked example — the ₹40,000 catch",
    html: "<div class='wstep'><p class='nar'><em>The scene:</em> a consultant preps a market-entry deck. Claude's draft includes: «India's premium candle market grew 34% YoY (2025), led by three D2C brands…» Beautiful. Slide-ready. <em>Now the triage:</em> this is red zone — a precise, recent stat, going to a paying client.</p></div><div class='wstep'><p class='nar'><em>Defense 2:</em> she replies «Search the web for this figure and give me the primary source.» The search finds an industry report saying <strong>21%</strong> — and the '34%' appears nowhere. Composed, not retrieved. <em>Cost of the catch: 90 seconds. Cost of the miss: the client's trust and the ₹40,000 retainer behind it.</em></p></div><div class='wstep'><p class='nar'><em>The judgment note:</em> she doesn't conclude «Claude is unreliable» — the same draft's structure, positioning logic and prose were excellent. She concludes what pros conclude: <strong>generation is Claude's job; verification is mine; the division of labour IS the workflow.</strong></p></div>"},
  lab: { where: "claude.ai",
    html: "<p>Run a controlled hallucination hunt — safely, on your own field. In a fresh chat:</p>" + PB("prompt 1 — bait (no search)", "Without using web search: give me 5 specific, citable statistics about [YOUR industry/field] from the last 12 months, with sources.", "prompt") + "<p>Then, in the same chat:</p>" + PB("prompt 2 — audit", "Now switch roles: you are a hostile fact-checker. For each statistic above, rate your actual confidence (certain / likely / should-verify / likely-invented) and explain the honest basis for each rating. Then search the web and tell me which ones survive contact with real sources.", "prompt"),
    expect: "Some «statistics» from prompt 1 get downgraded or corrected in prompt 2 — you'll watch fluent confidence deflate into honest calibration, then firm up with real sources. After feeling this once, you'll never skip red-zone verification again." },
  mistakes: [
    "<b>Verifying nothing</b> — the lawyer path. One unchecked red-zone fact can undo a hundred good deliveries.",
    "<b>Verifying everything</b> — burning an hour checking a brainstorm. Triage exists so your checking minutes land where wrongness is expensive.",
    "<b>Treating citations as proof.</b> A citation is a claim too, until clicked. Check the two that carry the argument.",
    "<b>Asking «are you sure?» and accepting «yes».</b> Weak ritual. The strong versions force mechanism: sources, quotes, confidence labels, or a fresh-context audit.",
    "<b>Concluding «never trust AI» after one miss.</b> The lesson is division of labour, not abstinence — drafting 10× faster + verifying like a pro is the entire value proposition."
  ],
  quiz: [
    { q: "Why does Claude hallucinate at all?",
      opts: ["Bugs that Anthropic hasn't fixed yet", "It composes answers from patterns, so sparse or post-cutoff topics can yield fluent, well-shaped falsehoods", "It's trained to make things up when bored", "Only free users get hallucinations"],
      a: 1,
      why: ["It's inherent to how generation works, not a defect awaiting a patch — though search, citations and training keep shrinking it.", "Correct — same machinery that writes brilliant novel prose, pointed at ground it can't see. That's why risk concentrates in precise/recent/niche facts.", "There's no boredom and no intent — that's why 'lying' is the wrong word and 'verification' is the right response.", "Model behaviour doesn't change by plan tier."] },
    { q: "Which output demands full red-zone verification?",
      opts: ["Twenty name ideas for your podcast", "A rewrite of your email to sound warmer", "A medication-interaction summary you'll act on", "An explanation of how compound interest works"],
      a: 2,
      why: ["Creative output — wrongness is cheap and visible. Green.", "You can judge the rewrite by reading it. Green.", "Correct — health decisions are maximal stakes, and interaction details are exactly the precise-fact territory where composition can fail. Verify with authoritative sources and a professional.", "Standard well-documented concept you can sanity-check — yellow at most."] },
    { q: "The strongest anti-hallucination move for «summarise the attached contract's termination terms» is:",
      opts: ["Add PLEASE BE ACCURATE in capitals", "Ask it to answer only from the document and quote the exact clause for each claim", "Run it five times and pick the middle answer", "Use the most expensive model and trust it"],
      a: 1,
      why: ["Sincerity isn't a mechanism.", "Correct — grounding + quotes makes every claim checkable in seconds against text YOU hold. It's defense 3, and it turns verification from research into proofreading.", "Consensus of guesses can converge on the same wrong reading; quotes beat votes.", "Better models hallucinate less but 'trust' is still not a verification strategy for red-zone output (Lesson 1.3's escalation + this lesson's checking, together)."] },
    { q: "Claude marks a claim «should-verify» when you ask for a confidence map. What does that tell you?",
      opts: ["The claim is definitely false", "The model is decently calibrated about its shaky ground — aim your checking there first", "Confidence maps are decorative", "You should delete the whole answer"],
      a: 1,
      why: ["'Should-verify' means uncertain, not false — sometimes it checks out fine.", "Correct — defense 4 exists because self-reported uncertainty is informative enough to direct your scarce verification minutes efficiently.", "They measurably concentrate real errors — that's operational value, not decoration.", "Discarding good work because part is uncertain wastes the 10× drafting speed; verify the flagged parts instead."] }
  ],
  prac: [
    { tag: "warm", q: "Sort into green/yellow/red: (a) haiku about your cat, (b) summary of a PDF you attached, (c) the exact GST rate for your invoice, (d) five blog outlines, (e) a quote attributed to Gandhi for your presentation.",
      sol: "(a) green · (b) yellow — spot-check load-bearing points against the PDF · (c) <b>red</b> — money + precise + changeable: verify on the official portal · (d) green · (e) <b>red</b> — misattributed quotes are a famous failure class; verify or cut. If (e) surprised you: quotes are precise facts wearing decorative clothing." },
    { tag: "transfer", q: "Write your own personal «red-zone checklist» — the 5 categories of output YOU will always verify, given your actual work and life.",
      sol: "<b>Test of a good list:</b> each item names a category (not 'important stuff') and a verification source — e.g., «prices/specs I put in client quotes → supplier site», «legal/tax claims → official portal or my CA», «statistics in anything published → primary source», «code touching payments → test suite + review», «anything medical → doctor». Pin it where you work; this one artifact prevents the expensive class of AI mistake." },
    { tag: "stretch", q: "Design a two-chat workflow (generator + hostile critic) for producing a fact-heavy LinkedIn post, specifying exactly what each chat is asked to do and what passes between them.",
      sol: "<b>One clean design:</b> Chat A (generator): draft post; require web search + a source URL for each factual claim + a confidence map. You click the 2–3 load-bearing links. Chat B (fresh context, critic): paste ONLY the final draft — «hostile fact-checker: list every factual claim, rate risk, flag anything unsupported or overstated; suggest safer phrasing.» Fix, then ship. Fresh context prevents the critic from inheriting the generator's anchoring — the same separation-of-roles you'll later build into automated pipelines (Track 10)." }
  ],
  recap: "Triage by stakes and checkability; force sources, quotes and confidence into the open; verify every red-zone fact against a primary source — generation is Claude's job, verification is yours.",
  bridge: "Foundation complete: you know what Claude is, its physics, its brains, its bodies, its economics, and its failure mode. Phase B begins — prompting, the craft that multiplies everything else. First lesson: the anatomy of a great prompt.",
  deep: "<p><strong>Is hallucination getting solved?</strong> The rate has fallen dramatically generation over generation, and 2026-era systems increasingly know what they don't know — Anthropic trains explicitly for honest uncertainty, and surfaces like Research mode wire retrieval + citations into the product. But two structural limits remain. First, generation is open-ended: any system that can compose novel text can compose novel falsehoods; you can shrink the rate, not the possibility. Second, <em>calibration vs coverage</em> tension: a model that refuses whenever unsure becomes useless; one that always answers must sometimes guess. So the professional discipline in this lesson isn't a temporary workaround awaiting a patch — it's the permanent shape of working with generative systems, the same way «measure twice» never stopped being carpentry. The operators who internalise this are precisely the ones trusted with consequential work — which, as Tracks 11–13 will show, is where the money is.</p>"
};

})();
