/* Track 3 — Advanced Prompting (L2) */
(function(){
var L = window.LESSONS;

/* ------------------------------------------------ 3.1 */
L["3.1"] = {
  sub: "One prompt asking for five things gets five mediocre things. Chains get five excellent things — and they're the seed of every agent you'll ever build.",
  breath: "Prompt chaining means decomposing a big job into focused steps — each prompt does one thing well and feeds the next — trading one blurry mega-prompt for a pipeline of sharp ones.",
  hook: "<p>Ask one person to research a market, write a report, design its slides and proofread everything — simultaneously — and you get chaos. Hire them for each job in sequence and you get quality. Everyone knows this about humans and then forgets it the moment they face a message box, typing «research X and write a report and make it engaging and also…». This lesson installs the decomposition habit — and quietly teaches you the architecture of agents three tracks early.</p>",
  secs: [
    { h: "Why chains beat mega-prompts",
      b: "<p>Three compounding reasons:</p><ul><li><strong>Attention is a budget.</strong> A prompt juggling five goals splits focus five ways (1.2's physics). Each chain step gets Claude's entire capability pointed at one target.</li><li><strong>Errors stop propagating silently.</strong> In a mega-prompt, a bad assumption in the «research» flows invisibly into the «report». In a chain, YOU inspect between steps — the checkpoint is the point. One weak link gets fixed without redoing the rest.</li><li><strong>Steps become reusable parts.</strong> A great «summarise interviews» step gets reused in ten future chains (and becomes a template in 3.5). Mega-prompts are monoliths; chains are Lego.</li></ul><p>The professional smell test: <strong>if your prompt contains two unrelated verbs, it wants to be two prompts.</strong> «Analyse and rewrite» — chain it. «Extract, then compare, then recommend» — three links.</p>"},
    { h: "Designing a chain",
      b: "<p>Work backwards from the deliverable:</p><ul><li><strong>1. Name the final artifact</strong> (2.4 shape-first thinking): «a 2-page brief recommending one vendor, with a comparison table.»</li><li><strong>2. Ask what that step needs as input</strong> — a filled comparison table → which needs per-vendor extractions → which needs the raw documents. Your chain just designed itself in reverse: extract (×3 vendors) → compare → recommend.</li><li><strong>3. Define each link's output format</strong> so it snaps into the next link's input (2.4's tags shine here — a &lt;table&gt; out of step 2 is pasted into step 3's &lt;table&gt; slot).</li><li><strong>4. Place your checkpoints.</strong> Between which links will you actually look? Minimum: after the extraction (facts checkable against source — 1.6) and before anything client-facing.</li></ul><div class='callout tip'><b>Where chains live:</b> in chat, a chain is just consecutive messages — or separate chats when steps deserve clean contexts (a critic step ALWAYS deserves a fresh chat — 1.6's fresh-eyes principle). Later, the same designs run automatically: Cowork executes multi-step plans (Track 5), and the API version is literally called workflow chaining (Track 10). Same skill, rising altitude.</div>"},
    { h: "Three chain shapes to recognise",
      b: "<ul><li><strong>The refinery</strong> (linear): raw → structured → analysed → drafted → polished. Most documents want this.</li><li><strong>The map-reduce:</strong> same prompt over many items (summarise each of 30 reviews) → then one prompt over the results (find patterns across summaries). This is how long work beats context limits — each item gets a fresh, focused pass.</li><li><strong>The generator–critic:</strong> produce in one step, attack in another (fresh context), revise in a third. You met the idea in 1.6; as a chain it becomes standard practice for anything high-stakes.</li></ul>"}
  ],
  worked: { t: "Worked example — the hiring chain",
    html: "<div class='wstep'><p class='nar'><em>The job:</em> screen 12 CVs against a job description honestly. <em>Mega-prompt temptation:</em> «Here are 12 CVs, rank them and explain.» One giant blur — rankings arrive with confident reasoning I can't audit.</p></div><div class='wstep'><p class='nar'><em>Working backwards:</em> final artifact = ranked shortlist with evidence. That needs per-CV scorecards; scorecards need criteria. <em>Chain:</em> Link 1 — «From this job description, derive 6 scoring criteria with 1–5 anchors» (I review — MY checkpoint on what fairness means). Link 2 — map step, fresh prompt per CV: «Score this CV against &lt;criteria&gt;, citing the line supporting each score; UNKNOWN where the CV is silent» (2.2's never-guess). Link 3 — reduce: «Given 12 scorecards, rank; flag any candidate whose rank depends on an UNKNOWN.»</p></div><div class='wstep'><p class='nar'><em>What the chain bought:</em> auditability (every score has a quoted line), a caught error (one CV's «led team of 40» was a typo for 4 — visible at the Link-2 checkpoint), and reusability (the criteria step now screens every future role). <em>Cost: three prompt designs instead of one. Value: a defensible process instead of a vibe.</em></p></div>"},
  lab: { where: "claude.ai",
    html: "<p>Chain a real task you'd normally mega-prompt. Pick something with 3+ natural stages (e.g., turning messy notes into a polished plan). Run it as three separate messages:</p>" + PB("link 1 — structure", "Here are my raw notes in <notes>…</notes>. Extract into: <goals>, <constraints>, <open_questions>. Verbatim where possible, no interpretation yet.", "prompt") + PB("link 2 — analyse (after reviewing link 1)", "Using the structured output above, identify: the 3 biggest risks, the dependency order of the goals, and which open question matters most. Reasoning in <thinking>, conclusions in <analysis>.", "prompt") + PB("link 3 — produce", "Using <analysis>, write the final one-page plan: timeline, owner per item, and a 'decide by Friday' box for the top open question. No preamble.", "prompt"),
    expect: "Between links you'll catch at least one thing you'd have never seen inside a mega-prompt — a wrong extraction, a risk you disagree with. That catch IS the argument for chains." },
  mistakes: [
    "<b>Chains without checkpoints.</b> Firing all links without looking recreates the mega-prompt's blindness with extra steps. The inspection is the value.",
    "<b>Links that do two jobs.</b> If a link «analyses and drafts», split it — the smell test applies recursively.",
    "<b>Formats that don't snap together.</b> Link 2 expecting a table Link 1 didn't produce = manual reformatting between every step. Design the interfaces first (2.4).",
    "<b>Chaining trivial tasks.</b> A two-line email doesn't need a pipeline. Chains earn their overhead on multi-stage, high-stakes, or reusable work.",
    "<b>Running the critic in the same contaminated chat.</b> A critic that watched the draft being born inherits its assumptions — fresh chat, always."
  ],
  quiz: [
    { q: "The strongest reason chains beat mega-prompts is:",
      opts: ["Chains use fewer total tokens", "Each step gets full attention AND you get checkpoints where errors are caught before they propagate", "Mega-prompts are against policy", "Chains work without any prompt skill"],
      a: 1,
      why: ["Chains often cost MORE tokens — they pay in quality and auditability.", "Correct — focused capability per step plus human inspection between steps: the two failure modes of mega-prompts, both fixed.", "Mega-prompts are allowed; they're just worse for multi-stage work.", "Chains amplify prompt skill; each link is still a prompt you design (2.1–2.7 all apply per link)."] },
    { q: "You need to analyse 40 customer interviews. Which chain shape fits?",
      opts: ["One prompt with all 40 pasted in", "The refinery: polish each interview's grammar first", "Map-reduce: same extraction prompt per interview, then one synthesis prompt across the 40 outputs", "Generator–critic on interview #1 only"],
      a: 2,
      why: ["It might fit the window (1.2) but attention dilutes across 40 documents — per-item passes are sharper.", "The refinery is for progressive transformation of ONE artifact, and grammar isn't the task.", "Correct — map for focused per-item quality, reduce for cross-item patterns. The workhorse shape for volume.", "That analyses one interview well and ignores 39."] },
    { q: "Where must a checkpoint go in any client-facing chain?",
      opts: ["Nowhere — chains are self-checking", "Only at the very start", "After fact-heavy steps (checkable against source) and before anything leaves for the client", "Between every single link, always"],
      a: 2,
      why: ["Chains create checkpoint OPPORTUNITIES; a human (or later, an automated check — Track 10) must actually stand at them.", "The start has nothing to inspect yet.", "Correct — 1.6's triage decides where: verify where facts concentrate and where stakes exit the building.", "Over-checkpointing trivial links wastes the time chains saved; stakes-based placement is the discipline."] }
  ],
  prac: [
    { tag: "warm", q: "Apply the smell test: split «Research the top 5 CRM tools for a 10-person sales team, compare pricing, and write a recommendation email to my boss» into named links with formats.",
      sol: "<b>Link 1 (research, with web search):</b> per-tool fact sheet — pricing, limits, integrations, sources (×5). <b>Link 2 (compare):</b> one table from the 5 sheets, criteria weighted for a 10-person team. <b>Link 3 (recommend):</b> email format — verdict first, table attached, one risk acknowledged. Checkpoints after 1 (facts! sources!) and before sending." },
    { tag: "transfer", q: "Take your most repeated multi-stage task at work. Design its chain on paper: links, formats between them, checkpoint positions. Then run it once for real.",
      sol: "<b>Quality bar:</b> every link has one verb; every interface is a named format; checkpoints sit after facts and before exits. Save the design — in 3.5 it becomes a template set, and if you reach Track 5, it's a ready-made Cowork delegation («follow this chain»)." },
    { tag: "stretch", q: "A chain's Link 2 (analysis) keeps producing shallow output even though Link 1's extraction is clean. List three distinct diagnoses and their fixes — using tools from Tracks 2–3 so far.",
      sol: "<b>Diagnosis 1 — under-specified task:</b> «analyse» is a mood (2.2); fix: name the analysis moves (compare against criteria, quantify, rank risks). <b>Diagnosis 2 — missing thinking:</b> multi-constraint reasoning needs deliberation (2.5); fix: extended thinking or named steps. <b>Diagnosis 3 — capability ceiling:</b> if 1 and 2 fail, escalate the model for this link only (1.3) — chains let you spend premium tokens on ONE link instead of the whole pipeline. That per-link economics is a real production pattern." }
  ],
  recap: "Two unrelated verbs = two prompts: decompose backwards from the deliverable, design snap-together formats, stand at checkpoints after facts and before exits — refinery, map-reduce, generator–critic cover almost everything.",
  review: "From Lesson 2.7: the generator–critic chain is your fresh-eyes restart discipline, promoted from recovery move to standard architecture.",
  bridge: "Chains manage complexity across steps. Next: managing SCALE within one step — the craft of 200K-token contexts, where document placement and quote-first tricks decide everything.",
  deep: "<p><strong>Chains are baby agents.</strong> Strip the mystique from «AI agents» (Track 10) and you find: a loop that decomposes goals into steps, executes them, inspects results, and decides what's next. Designing chains by hand IS that loop with you as the orchestrator — which is why Anthropic's building-effective-agents guidance starts with exactly these workflow shapes (chaining, routing, parallelisation, orchestrator–workers, evaluator–optimizer) before any autonomy. The professional path mirrors it: master hand-run chains → let Cowork run them supervised (Track 5) → encode them as automated workflows on the API (Track 10). People who skip the hand-run stage build agents they can't debug, because they never learned where the checkpoints belong. You're learning it in the cheapest possible classroom: a chat window.</p>"
};

/* ------------------------------------------------ 3.2 */
L["3.2"] = {
  sub: "A 200K window is a superpower with a user manual. Placement, quote-first grounding, and needle-proofing — the craft of giant contexts.",
  breath: "For long-document work: put the big material at the top, instructions at the bottom, demand verbatim quotes before conclusions, and structure multi-document prompts with labelled tags — recall degrades gracefully, so engineer for it.",
  hook: "<p>Claude can hold a 500-page case file in mind at once — something no human colleague can do. And yet two users hand it the same file and get different grades of insight: one gets page-42 details woven into the answer; the other gets a competent skim. The difference is a handful of placement and grounding habits that took researchers years to measure and take you fifteen minutes to learn. Giant context is a superpower; this is the user manual.</p>",
  secs: [
    { h: "The physics of recall in long contexts",
      b: "<p>Within the window, everything is <em>visible</em> — but not everything is equally <em>salient</em>. Behaviours worth engineering around:</p><ul><li><strong>Edges beat middles.</strong> Material at the start and end of the context tends to get sharper attention than the deep middle («lost in the middle» in the research literature). Modern Claude models are strong at needle-retrieval, but salience still isn't flat — on hard synthesis tasks, position matters.</li><li><strong>Instructions compete with bulk.</strong> A one-line instruction floating above 300 pages is a whisper in a stadium. Instructions want to sit AFTER the material, close to where generation begins — Anthropic's own guidance: <strong>documents at the top, query at the bottom</strong> (this ordering also unlocks caching wins later — 9.6).</li><li><strong>Structure is a map.</strong> Tagged, labelled documents (&lt;doc id='contract_2024'&gt;…) let Claude address material the way an index lets a human — and let YOU say «compare doc contract_2024 with doc contract_2026».</li></ul>"},
    { h: "The long-context prompt pattern",
      b: "<p>Memorise one canonical shape:</p><ul><li><strong>Top:</strong> all documents, each fenced and labelled: &lt;documents&gt;&lt;doc id='…' date='…'&gt;text&lt;/doc&gt;…&lt;/documents&gt;</li><li><strong>Then:</strong> the role and standing rules (2.6).</li><li><strong>Bottom:</strong> the task, the format spec, and the grounding demand: <em>«Before answering, extract the passages relevant to the question into &lt;quotes&gt;, citing doc id. Base the answer ONLY on those quotes; if the documents don't contain the answer, say so.»</em></li></ul><p>That quotes-first demand is the single highest-value long-context habit. It forces retrieval before reasoning (a mini-chain inside one prompt — 3.1 thinking), makes every claim auditable in seconds (1.6), and measurably improves accuracy on long-document tasks because the model conditions its answer on re-surfaced text instead of a fading impression.</p>"},
    { h: "When NOT to stuff the window",
      b: "<p>Fit is not the bar; relevance is (1.2). The decision tree:</p><ul><li><strong>One question, findable in known sections?</strong> Send only those sections. Cheapest, sharpest.</li><li><strong>Synthesis across everything?</strong> (themes across 40 interviews, contradictions across contracts) — this is what giant windows are FOR; stuff away, with structure.</li><li><strong>Repeated questions against the same corpus?</strong> Two-stage it: one pass builds a structured index/brief (map-reduce, 3.1); later questions run against the index, dipping into full text only when the index points somewhere (the contract pattern from 1.2's worked example, now formalised).</li><li><strong>Corpus bigger than any window?</strong> That's retrieval territory — search first, read selected chunks (you'll meet RAG properly in Track 9's ecosystem; conceptually it's this bullet at industrial scale).</li></ul>"}
  ],
  worked: { t: "Worked example — the three-contract contradiction hunt",
    html: "<div class='wstep'><p class='nar'><em>The job:</em> a client has three vendor contracts (2019, 2022, 2024 renewals) and a suspicion: payment terms drifted worse over time. Total ~180 pages. <em>This is cross-document synthesis — a legitimate window-stuffing job.</em></p></div><div class='wstep'><p class='nar'><em>Assembly (canonical shape):</em> three fenced docs with ids and dates at top; role («contracts analyst; conservative; never infer beyond text»); bottom: «Task: trace how payment terms, late-fee clauses and termination rights changed across the three docs. FIRST: &lt;quotes&gt; — the exact clause text per topic per doc, with doc id. THEN: &lt;changes&gt; — a table topic × year. THEN: &lt;flags&gt; — changes that disadvantage the client, severity-rated. If a topic is absent from a doc, write ABSENT — do not fill gaps.»</p></div><div class='wstep'><p class='nar'><em>Why each choice:</em> quotes-first means the comparison table is built from re-surfaced verbatim text, not memory-of-having-read; ABSENT beats silent interpolation (2.2's edge-case law); the severity flags give the client an action list, not homework. <em>Checkpoint behaviour:</em> I spot-check two quotes against the PDFs (10 seconds each — they're cited by doc id) before trusting the table. The client gets the drift analysis in an hour; the associate who'd have done it manually gets their weekend.</p></div>"},
  lab: { where: "claude.ai",
    html: "<p>Test grounding on a document you know well (a contract, a policy, a long report — something where YOU can judge accuracy). Attach or paste it, then:</p>" + PB("prompt", "<doc id='mydoc'>\n[YOUR LONG DOCUMENT]\n</doc>\n\nAnswer this question about the document: [A QUESTION WHOSE ANSWER LIVES IN ONE SPECIFIC SECTION].\n\nProcess: first output <quotes> — the exact passages (verbatim, with any section numbers) that bear on the question. Then <answer> — based ONLY on those quotes. Then <confidence> — certain / likely / not-in-document.", "prompt") + "<p>Then ask a second question whose answer is genuinely NOT in the document, same format.</p>",
    expect: "Question 1: correct quotes, correct answer — verify the quotes are truly verbatim. Question 2: the not-in-document case should return empty quotes and an honest «not in document» instead of a plausible invention. If it invents, your grounding demand wasn't strict enough — tighten and rerun; feeling that difference is the lesson." },
  mistakes: [
    "<b>Instructions above, bulk below.</b> The whisper-in-a-stadium layout. Flip it: documents top, task bottom.",
    "<b>Unlabelled document soup.</b> Three pasted contracts with no fences = «the 2022 one» is ambiguous forever. Tag with ids and dates.",
    "<b>Conclusions without quotes on high-stakes material.</b> Unquoted long-document claims are unauditable — you've built a hallucination with a bibliography of vibes.",
    "<b>Stuffing for one findable fact.</b> Paying 180 pages of desk-rent for a page-3 answer (1.2).",
    "<b>Trusting «I read the whole thing» summaries for contradiction-hunting without a quotes pass.</b> Synthesis is where impression-based errors hide; quotes-first flushes them."
  ],
  quiz: [
    { q: "The canonical long-context layout is:",
      opts: ["Task first, documents after", "Documents (fenced, labelled) at top; role and rules; task + format + grounding demand at the bottom", "Alternate one instruction, one document page", "Order doesn't matter inside the window"],
      a: 1,
      why: ["That's the whisper-in-a-stadium layout — instructions drown.", "Correct — bulk up top, directives near generation, quotes demanded before conclusions. Also the cache-friendly ordering you'll monetise in 9.6.", "Interleaving destroys both structure and cacheability.", "Everything is visible; salience is NOT flat — placement is measurable craft."] },
    { q: "«Extract relevant passages into <quotes> before answering» primarily buys you:",
      opts: ["Longer answers", "Retrieval-before-reasoning: the answer conditions on re-surfaced verbatim text, and every claim becomes spot-checkable in seconds", "Lower token bills", "Nothing on modern models"],
      a: 1,
      why: ["Length isn't the point — grounding is.", "Correct — a mini-chain inside one prompt: find, then conclude. Accuracy up, audit cost down; 1.6's discipline industrialised.", "It slightly RAISES token use and massively raises trustworthiness — a trade professionals take every time.", "Modern models are better at retrieval, and quotes-first still measurably helps on synthesis — plus the audit value never expires."] },
    { q: "You'll ask ~30 questions against the same 400-page manual over a month. Best architecture?",
      opts: ["Paste all 400 pages with every question", "One pass builds a structured index/brief; questions run against it, dipping into full text only when pointed there", "Ask all 30 questions in one mega-prompt today", "Retype the manual by hand"],
      a: 1,
      why: ["30 × 400 pages of desk-rent for answers an index would route — the 1.2 contract example scaled up.", "Correct — the two-stage corpus pattern: compress once with a path back to source, query cheap thereafter.", "You don't know all 30 questions yet, and one mega-prompt splits attention 30 ways (3.1).", "Please no."] }
  ],
  prac: [
    { tag: "warm", q: "Rewrite this prompt into the canonical shape (just the skeleton): «Compare these three supplier quotes and tell me which is best. [quote A] [quote B] [quote C]»",
      sol: "<b>Shape:</b> &lt;quotes_docs&gt;&lt;doc id='A'&gt;…&lt;/doc&gt;&lt;doc id='B'&gt;…&lt;/doc&gt;&lt;doc id='C'&gt;…&lt;/doc&gt;&lt;/quotes_docs&gt; → role: procurement analyst for [context] → bottom: «FIRST &lt;extract&gt;: price, delivery, warranty, hidden fees per doc (verbatim, ABSENT if missing). THEN comparison table. THEN recommendation for [your priorities], flagging any decision that rests on an ABSENT.»" },
    { tag: "transfer", q: "Take the longest real document in your life right now. Run the two-question grounding lab on it, then build its reusable «index brief» for future questions.",
      sol: "<b>Index-brief prompt:</b> «Build a structured index of this document I can use to answer future questions without re-reading: per section — 2-line summary, key numbers/dates verbatim, and section reference. Under 800 tokens.» Save the output. You now own the two-stage pattern on a document that matters to you — total cost, maybe ten minutes." },
    { tag: "stretch", q: "A colleague reports: «I asked for contradictions across our five policy docs and Claude found three — but one 'contradiction' was actually two clauses about different employee categories.» Diagnose and armour the prompt.",
      sol: "<b>Diagnosis:</b> synthesis-without-scope-tracking — surface-similar clauses compared without their applicability conditions (classic long-context impression error). <b>Armour:</b> quotes-first WITH scope: «for each candidate contradiction, quote both clauses AND each clause's applicability conditions (who/when it covers); only flag as contradictory if scopes overlap — otherwise label SCOPE-DISTINCT.» You've turned a judgment failure into an explicit check — the 2.2 edge-case law applied to analysis itself." }
  ],
  recap: "Documents top, task bottom, everything fenced and labelled; demand quotes before conclusions and ABSENT over interpolation; stuff the window for synthesis, index the corpus for repeated queries.",
  review: "From Lesson 1.2: «fit is not the bar; relevance is» — this lesson is that sentence grown into a full architecture.",
  bridge: "You can steer giant inputs. Next: precision-controlling outputs — prefilling, extraction contracts, and the tricks that make Claude's answers snap into exactly the shape your next tool expects.",
  deep: "<p><strong>How did million-token contexts become real?</strong> Attention's naive cost grows quadratically with length — doubling context quadruples compute — so the era of 4K windows wasn't stinginess, it was physics. The march to 200K and then 1M (Claude's 2026 flagships) came from attention-efficiency research, better positional encodings, and training regimes that teach models to USE far-apart information, not merely fit it. Benchmarks evolved the same way: from «needle in a haystack» (find one planted sentence — essentially solved) to multi-needle reasoning and cross-document synthesis, where placement and grounding still measurably matter — which is exactly why this lesson's habits survive model upgrades. One economic note: long context competes with retrieval (RAG), and 2026 practice blends them — windows this big mean «just include the whole thing» is often simpler and BETTER for medium corpora, while true retrieval owns the terabyte scale. Knowing which side of that line your task sits on is a billable judgment call — literally: it's a Track 11 consulting conversation.</p>"
};

/* ------------------------------------------------ 3.3 */
L["3.3"] = {
  sub: "Prefilling, extraction contracts, and answer-shaping: how to make Claude's output start exactly where you want and land exactly where your tools need.",
  breath: "You can shape the very first token of Claude's answer — by instruction in chat («begin directly with…») or literal prefill on the API — and combine it with strict extraction contracts to get machine-grade output from a language model.",
  hook: "<p>Every answer Claude gives is steered token by token — and the most underrated fact in the craft is that the FIRST tokens steer hardest. Control how the answer begins and you control much of what it becomes. There's a chat-grade version of this power, an API-grade version, and a whole discipline of «extraction contracts» built on top. This lesson is where prompting starts feeling like engineering.</p>",
  secs: [
    { h: "First tokens rule everything after them",
      b: "<p>Generation is autoregressive: each token conditions on everything before it (1.1, 2.5). So the opening of the answer isn't decoration — it's the rails. If the answer begins «Great question! There are several ways to think about this…», you've bought a hedge-and-ramble trajectory. If it begins with a table header, you get a table. Steering moves, in rising strength:</p><ul><li><strong>Ban the preamble</strong> (2.4): «No preamble. Begin directly with the verdict.»</li><li><strong>Dictate the opening:</strong> «Begin your response with exactly: VERDICT: » — the model must continue from a committed frame.</li><li><strong>Literal prefill (API — Lesson 9.2):</strong> on the API you can write the beginning of the assistant's turn yourself — start it with «{» and JSON becomes overwhelmingly likely; start with «VERDICT:» and no pleasantries can exist. Chat gives you ~90% of this via instruction; the API makes it mechanical.</li></ul>"},
    { h: "Extraction contracts: the strict version of format specs",
      b: "<p>When output feeds a spreadsheet, script, or downstream prompt (3.1 chains!), «mostly right format» = broken. An <strong>extraction contract</strong> is a format spec with the screws tightened:</p><ul><li><strong>Exact schema by example</strong> (2.3+2.4): show the precise keys/columns, with one filled example row.</li><li><strong>Type discipline:</strong> «dates as YYYY-MM-DD; amounts as numbers without currency symbols; missing → null (never guess, never omit the key).»</li><li><strong>Totality rule:</strong> «one output row per input item, even for rejects (mark status: SKIPPED + reason)» — silent drops are the deadliest extraction bug.</li><li><strong>No-other-text rule:</strong> the output IS the artifact — no explanation before, no summary after.</li><li><strong>Self-check clause:</strong> «before finishing, verify: row count equals input count; all dates parse; then output only the data.» Cheap, surprisingly effective.</li></ul><p>On the API, structured outputs make schema-compliance a guarantee (9.5) — but the CONTRACT thinking (types, totality, null-honesty) stays yours; a guaranteed-valid schema can still contain guessed values if you never wrote the never-guess clause.</p>"},
    { h: "Answer-shaping patterns worth stealing",
      b: "<ul><li><strong>The committed-verdict pattern:</strong> «First line: APPROVE / REJECT / NEEDS-INFO. Then justification.» Forces the decision before the rationale — no more essays that never conclude. (For hard reasoning, combine with 2.5: think in &lt;thinking&gt;, THEN commit.)</li><li><strong>The differential pattern:</strong> «Output only what CHANGED from the previous version, as a list of edits.» Perfect for revision loops (2.7) — and it's how you review a 30-page revision in one minute.</li><li><strong>The traffic-light pattern:</strong> force every item into green/yellow/red with one-line reasons — decisions love discrete states (you saw it in 1.6's triage; now you're the one imposing it).</li><li><strong>The fill-the-blanks pattern:</strong> paste a template with ____ slots and «fill only the blanks; change nothing else». The strongest format control available in pure chat — the document IS the contract.</li></ul>"}
  ],
  worked: { t: "Worked example — the expense pipeline that never lies silently",
    html: "<div class='wstep'><p class='nar'><em>The job:</em> 90 photographed receipts → clean expense sheet. The naive prompt («extract the expenses») returns beautifully formatted rows — and quietly skips two illegible receipts and «helpfully» estimates one smudged total. Three silent failures in a financial document. <em>Unacceptable — time for a contract.</em></p></div><div class='wstep'><p class='nar'><em>The contract:</em> schema by example (date YYYY-MM-DD, vendor, amount as plain number, category from fixed list, status); totality rule («one row per receipt — status OK or UNREADABLE with reason; row count MUST equal receipt count»); null-honesty («any unreadable field → null, NEVER estimate — a wrong amount is worse than a missing one»); no-other-text; self-check clause (count match, dates parse, amounts numeric).</p></div><div class='wstep'><p class='nar'><em>The result:</em> 90 rows — 87 OK, 3 UNREADABLE with reasons («total obscured by fold»). The 3 go to a human, which is exactly right: <em>the pipeline's job isn't to know everything; it's to never pretend.</em> This contract, unchanged, becomes an API batch job in Track 9 and a sellable bookkeeping automation in Track 11 — extraction contracts are a product skill wearing a prompting costume.</p></div>"},
  lab: { where: "claude.ai",
    html: "<p>Build and stress-test a contract. Gather 5 messy real inputs of one kind (receipts, emails, ads, listings — anything). Write your contract:</p>" + PB("prompt — the contract", "Extract from each item in <items> into this exact schema, one line per item:\n{\"id\": 1, \"name\": \"…\", \"amount\": 123.45, \"date\": \"2026-07-21\", \"status\": \"OK\"}\nRules: amounts as plain numbers; dates YYYY-MM-DD; any unreadable/missing field = null, never guess; unusable item → status \"SKIPPED\" with a \"reason\" field; output must have exactly one line per input item; no text before or after the data. Before finishing, silently verify line count = item count and all dates parse.\n\n<items>\n[YOUR 5 ITEMS — MAKE ITEM 4 DELIBERATELY BROKEN/IRRELEVANT]\n</items>", "prompt"),
    expect: "Five lines exactly — with item 4 SKIPPED + reason instead of silently dropped or creatively 'fixed'. If you got prose around the data or a guessed value, tighten the violated clause and rerun: contracts are debugged, not written." },
  mistakes: [
    "<b>Formatting hopes instead of contracts.</b> «As JSON please» without schema, types, totality and null rules = valid-looking output with invented keys and silent drops.",
    "<b>Letting helpfulness fill gaps.</b> Unconstrained models would rather estimate than admit blanks — write the null-honesty clause or inherit the guesses.",
    "<b>No totality rule.</b> The deadliest bug is the missing row you didn't notice. Count in = count out, statuses for rejects, always.",
    "<b>Preamble on machine output.</b> One friendly sentence before the JSON breaks the parser. No-other-text is a real clause, not styling.",
    "<b>Testing contracts on clean inputs only.</b> Contracts exist FOR the broken item 4. If your test set has no garbage, your contract is untested."
  ],
  quiz: [
    { q: "Why does controlling the answer's FIRST tokens matter so much?",
      opts: ["First tokens are cheaper", "Generation is autoregressive — the opening becomes the rails everything after runs on", "Users only read openings", "It doesn't; endings matter more"],
      a: 1,
      why: ["Same price per token, wildly different leverage.", "Correct — commit the frame (a verdict, a brace, a header) and the continuation follows it. Prefill is this fact weaponised.", "True of humans, but the mechanism here is conditioning, not attention spans.", "Openings condition everything downstream; endings condition nothing."] },
    { q: "An extraction ran over 200 items and returned 197 beautiful rows. The contract clause that was missing:",
      opts: ["A politeness clause", "The totality rule — one output row per input, rejects marked SKIPPED with reasons, counts must match", "A longer role description", "More examples of clean inputs"],
      a: 1,
      why: ["Courtesy doesn't count rows.", "Correct — silent drops are invisible precisely because everything present looks perfect. Count-match turns absence into an error you can see.", "Roles shape voice, not completeness.", "Clean examples teach the happy path; the missing 3 were the unhappy path."] },
    { q: "«Any field you cannot read = null — never estimate» exists because:",
      opts: ["Nulls are prettier", "Trained helpfulness biases models toward plausible filling; in data work a confident wrong value is worse than an honest hole", "It saves tokens", "Regulations require the word null"],
      a: 1,
      why: ["Aesthetics are irrelevant; auditability is everything.", "Correct — this is 1.6's truth discipline compiled into a schema: holes get human review, guesses get discovered in the audit. Choose holes.", "Negligible token difference.", "No regulation — just the difference between a pipeline you can trust and one you can't."] }
  ],
  prac: [
    { tag: "warm", q: "Write the committed-verdict pattern for reviewing guest blog submissions: decision states, opening line format, and what follows.",
      sol: "<b>Example:</b> «Line 1, exactly: DECISION: ACCEPT | REVISE | REJECT. Line 2: one-sentence reason. Then: for REVISE, the 3 required changes as an ordered list; for REJECT, the single disqualifying issue; for ACCEPT, the one edit that would most improve it. Nothing else.» Decision-first, bounded rationale, state-specific follow-ups — no essays that never conclude." },
    { tag: "transfer", q: "Find data trapped in an inconvenient format in your real life (bank SMS pile, order confirmations, listings). Write a full extraction contract, run it on 10 real items including at least one broken one, and audit with the totality check.",
      sol: "<b>Audit bar:</b> row count matches, every broken item has a status+reason, zero guessed values (spot-check 3 rows against sources — 1.6). If it passes: you now own a reusable micro-pipeline; note what it replaces (manual typing) and what that's worth monthly — you'll want that number in Track 11." },
    { tag: "stretch", q: "Your contract works in chat, and in Track 9 you'll move it to the API where structured outputs GUARANTEE the schema. List what problems disappear with that guarantee, and what problems remain yours forever.",
      sol: "<b>Disappear:</b> malformed JSON, invented keys, prose-around-data, type drift (schema-level validity becomes mechanical). <b>Remain yours:</b> null-honesty (a valid schema can hold a guessed amount), totality semantics (the model could still merge two receipts into one valid row), category judgment, and the self-check habit. The guarantee removes syntax risk; SEMANTIC truth remains a prompting-and-verification craft — which is why contract thinking outlives every API feature." }
  ],
  recap: "First tokens are rails — commit them; extraction is a contract — schema by example, types, totality, null-honesty, no-other-text, self-check; and test contracts on garbage, because garbage is the job.",
  review: "From Lesson 2.3: schema-by-example is few-shot prompting's most industrial costume — one filled row is worth a page of field descriptions.",
  bridge: "You can now make outputs precise. Next, make them TRUE: the full anti-hallucination arsenal — grounding, citations, honest-uncertainty engineering, and verification loops you can actually run.",
  deep: "<p><strong>Prefill: the API's secret steering wheel.</strong> When you reach Lesson 9.2 you'll meet the literal version: in the Messages API, you provide the beginning of the assistant's response, and generation continues from YOUR tokens — start with «{» for JSON-mode-by-force, with a canned analysis header to skip preambles forever, or with a partial answer to constrain framing. Two deep facts: (1) prefill influence is strongest at low distances — it dominates the next dozens of tokens and fades over hundreds, so prefill sets FRAME, contracts maintain DISCIPLINE; (2) prefill is also a classic jailbreak vector (forcing a compliant-sounding opening), which is why safety training specifically hardens against adversarial prefills — a preview of Track 10's theme that every steering mechanism is also an attack surface. And one ecosystem note: 2026's structured-outputs features are, mechanically, «grammar-constrained decoding» — the model literally cannot emit schema-breaking tokens. Constraint at the decoder level, contract at the semantic level: both layers exist because they solve different halves of trust.</p>"
};

/* ------------------------------------------------ 3.4 */
L["3.4"] = {
  sub: "From habits to engineering: the complete anti-hallucination stack — grounding, citation demands, honest-uncertainty design, and verification loops.",
  breath: "Truth is engineered in layers: constrain the task to supplied material, demand citations and confidence labels, give explicit permission to say I-don't-know, verify with fresh-context critics — and match the stack's weight to the stakes.",
  hook: "<p>In Lesson 1.6 you learned the discipline: triage, verify, never trust confidence. That was you protecting yourself. This lesson is the engineering version — building prompts and pipelines where errors get CAUGHT BY DESIGN, because from Track 5 onward, Claude increasingly works while you're not watching, and «I'll eyeball it» stops scaling. Truth has to move from your vigilance into the system itself.</p>",
  secs: [
    { h: "Layer 1 — shrink the surface where invention can happen",
      b: "<ul><li><strong>Closed-book vs open-book:</strong> the single biggest lever. «Answer ONLY from &lt;doc&gt;» converts an unbounded recall task into a bounded reading task — hallucination surface collapses (3.2's grounding, now understood as a truth tool, not just an accuracy tool).</li><li><strong>Search-then-answer for the open world:</strong> anything recent, priced, versioned, or niche gets «search the web first; cite sources» (1.6 defense 2 — now a standing rule in your system prompts, not a per-chat rescue).</li><li><strong>Structured nulls beat prose gaps:</strong> extraction contracts' null-honesty (3.3) IS anti-hallucination — schema design and truth design are the same design.</li><li><strong>Decompose high-invention tasks</strong> (3.1): «write a report with statistics» invites invented statistics; chain it — gather stats (with sources) → verify checkpoint → write from verified list. The checkpoint is a truth valve.</li></ul>"},
    { h: "Layer 2 — make uncertainty speakable, then legible",
      b: "<ul><li><strong>The permission clause, upgraded:</strong> «If you don't know or the material doesn't say: state that plainly. An honest gap is a GOOD answer.» Works because trained helpfulness treats non-answers as failures unless you re-price them.</li><li><strong>Confidence labels as output schema:</strong> every claim tagged certain / likely / should-verify (1.6 defense 4) — but now REQUIRED BY FORMAT, so skipping the label breaks the contract (3.3's trick pointed at truth).</li><li><strong>Source-per-claim:</strong> «each factual sentence ends with [source: doc-id / URL / 'model knowledge']». That last option matters: forcing Claude to LABEL claims that come from its own training (vs your documents) makes the risky category visible — model-knowledge claims are where your verification minutes go.</li><li><strong>Numbers get provenance:</strong> standing rule — «every number: exact quote of where it came from, or label it an estimate WITH the estimation basis.» Invented-number incidents drop to near zero under this one rule.</li></ul>"},
    { h: "Layer 3 — adversarial verification loops",
      b: "<p>For work that ships, add a hostile pass — the generator–critic chain (3.1) with teeth:</p><ul><li><strong>The extraction audit:</strong> fresh chat, paste output + sources: «Verify every claim against the sources. Output: claim | supported/unsupported/contradicted | the quote or the gap.» Mechanical, fast, brutal.</li><li><strong>The assumption hunter:</strong> «List every assumption this analysis rests on that is NOT stated in the source material, ranked by how much the conclusion changes if the assumption is wrong.» Finds the invisible load-bearing guesses.</li><li><strong>The citation checker:</strong> for search-based work — «visit each cited source; does it actually say what the answer claims it says?» (Citations can be real links to pages that don't support the claim — the subtlest failure class.)</li><li><strong>Stack-weight by stakes</strong> (1.6's triage, now a dial): green work = layer 1 only; yellow = +labels; red = full stack + human on the flagged items. Over-engineering a brainstorm and under-engineering a client deliverable are the same mistake in opposite directions.</li></ul>"}
  ],
  worked: { t: "Worked example — armouring a market-research report",
    html: "<div class='wstep'><p class='nar'><em>The job (echoing 1.6's near-miss, now engineered):</em> a paid market-entry report. <em>Layer 1:</em> chain the work — Link 1 gathers every market claim via web search into a fact table: claim | source URL | exact supporting quote | date. I click the 4 load-bearing links (checkpoint). Link 2 writes the report FROM THE TABLE ONLY: «no factual claim may appear that isn't in <facts>; every number carries its [source].»</p></div><div class='wstep'><p class='nar'><em>Layer 2:</em> the report format REQUIRES a confidence appendix: each key claim labelled, model-knowledge claims flagged separately (there should be almost none — and if one sneaks in, the label catches it). <em>Layer 3:</em> fresh chat runs the citation checker on the final draft — it flags one: a real article that discusses the market but never states the growth figure attributed to it. Link 1 sourced it sloppily; I fix the fact table, regenerate the paragraph.</p></div><div class='wstep'><p class='nar'><em>The economics:</em> the full stack added ~25 minutes to a report worth ₹40,000. The flagged citation would have been the client's due-diligence discovery instead of mine. <em>That's the whole pitch: truth engineering is margin protection.</em> When this pipeline goes automated in Track 10, every one of these layers becomes a node in the workflow — nothing new to invent, because you built the judgment here.</p></div>"},
  lab: { where: "claude.ai",
    html: "<p>Armour a real factual task end to end. Pick something you'd actually use (a comparison, a buying decision, a market question):</p>" + PB("prompt — armoured research", "Research: [YOUR QUESTION]. Use web search.\nOutput STAGE 1 only — a fact table: claim | source URL | exact supporting quote (verbatim) | date. Include only claims a quote directly supports. If sources conflict, include both rows and mark CONFLICT. No narrative yet.", "prompt") + "<p>Click the 2–3 links that matter. Then:</p>" + PB("prompt — grounded synthesis", "STAGE 2: Using ONLY the verified fact table above, write the answer/recommendation. Every factual sentence ends with its [source]. Anything you add from general knowledge must be labelled [model knowledge]. End with a confidence appendix: each key claim → certain / likely / should-verify.", "prompt"),
    expect: "A conclusion where every load-bearing claim has a clickable trail, and [model knowledge] labels expose exactly where the model went beyond your table (often zero places — which itself is the system working). Compare the feeling of shipping THIS vs a one-prompt answer." },
  mistakes: [
    "<b>One-layer thinking.</b> Grounding without labels, or labels without verification — each layer catches what the previous one leaks; stakes decide how many you stack.",
    "<b>Citations accepted as decoration.</b> A real URL ≠ a supporting URL. The citation checker exists for the article that discusses the topic but never says the claimed thing.",
    "<b>Punishing honesty in practice.</b> If your follow-up to «the document doesn't say» is irritation and «just answer», you've retrained the session toward guessing. Reward the gap; then go find the answer properly.",
    "<b>Running the critic in the generator's chat.</b> Still the classic. Fresh context or it's theatre (2.7, 3.1 — some rules bear repeating because the failure keeps happening).",
    "<b>Full stack on everything.</b> A brainstorm doesn't need a citation audit; a client number always does. The dial is the skill."
  ],
  quiz: [
    { q: "Why does «answer only from the attached document» reduce hallucination so dramatically?",
      opts: ["It makes Claude read slower", "It converts unbounded recall into bounded reading — the space where invention can occur collapses to the document's edges", "Attachments disable creativity", "It doesn't; it's placebo"],
      a: 1,
      why: ["Speed isn't the mechanism.", "Correct — closed-book tasks have a checkable ground truth in-context; most invention happens where the model must reach beyond what's in front of it.", "Creativity remains available — it's just not being asked to fill factual gaps.", "It's among the most reliable effects in applied prompting."] },
    { q: "The [model knowledge] label — marking claims that came from training rather than your sources — exists because:",
      opts: ["Model knowledge is always wrong", "It makes the RISKY CATEGORY visible: those are the claims your verification minutes should target", "It's legally required", "It pads the word count"],
      a: 1,
      why: ["Model knowledge is often right — it's just unverifiable-by-quote, which is different.", "Correct — provenance labelling doesn't fix errors; it AIMS your scarce checking effort where quotes can't protect you. Triage, industrialised.", "No law — just engineering hygiene.", "It's one bracket per claim; the value is targeting, not volume."] },
    { q: "The citation checker catches which specific failure?",
      opts: ["Fake URLs only", "Real sources that don't actually support the claim attributed to them", "Spelling mistakes in citations", "Paywalled links"],
      a: 1,
      why: ["Fake URLs are the crude version; modern search-grounded work mostly avoids them.", "Correct — the subtle class: a genuine article about the market, cited for a growth figure it never states. Only visiting the source catches it — which is why the checker visits.", "Cosmetic.", "Paywalls are an access problem, not a truth problem."] },
    { q: "Matching stack weight to stakes means:",
      opts: ["Full verification on everything, always", "No verification — modern models are safe", "Layer 1 for drafts, +labels for factual work, full stack + human review for anything that ships with your name on it", "Verification only on Fridays"],
      a: 2,
      why: ["Auditing brainstorms burns the time the tools saved — over-engineering is a real failure mode.", "1.6's structural argument: generation can always compose falsehood; the rate fell, the possibility didn't.", "Correct — the dial. Same triage as 1.6, now expressed as WHICH LAYERS TO BUILD rather than how nervous to feel.", "Stakes don't check calendars."] }
  ],
  prac: [
    { tag: "warm", q: "Write the three standing truth-rules you'd put in YOUR system prompt (2.6), given your actual work.",
      sol: "<b>Pattern to match:</b> one grounding rule («claims about my documents: quote or don't claim»), one provenance rule («every number: source or labelled estimate»), one honesty rule («gaps stated plainly — never filled»). If your three don't cover numbers, documents and gaps, revise: those are the big three invention sites." },
    { tag: "transfer", q: "Take something factual you produced with AI recently and RETROACTIVELY audit it: run the extraction audit and citation checker on it in a fresh chat. Report what survived.",
      sol: "<b>Typical honest result:</b> most claims supported, one or two unsupported-but-true-ish, occasionally one genuinely wrong. Whatever you find, you've now FELT the gap between «looked right» and «verified» on your own work — the exact gap clients pay Track 11 operators to close professionally." },
    { tag: "stretch", q: "Design the truth architecture for an automated weekly competitor-news digest that will email itself to your team (you'll build such things in Tracks 5 and 10): which layers run automatically, what gets flagged for humans, and what does the email's footer honestly say?",
      sol: "<b>One sound design:</b> search-grounded gathering with source-per-claim (layer 1) → automated citation-existence check + confidence labels (layer 2) → items marked should-verify or CONFLICT quarantined into a «needs human eyes» section rather than silently dropped or confidently included (layer 3 as routing). Footer: «Auto-compiled from cited sources; items in the review section are unverified.» The deep principle: automation doesn't remove the human — it CONCENTRATES human attention on the flagged 5%. That principle is the backbone of every trustworthy agent you'll ever ship." }
  ],
  recap: "Engineer truth in layers — shrink the invention surface, make uncertainty speakable and provenance visible, verify adversarially in fresh contexts — and weight the stack by stakes, because both over- and under-engineering are failures.",
  review: "From Lesson 1.6: the five defenses were habits; today they became architecture. Same triage, higher altitude — this is the course's pattern, and it happens once more when agents arrive.",
  bridge: "Your prompts are precise and true. Now make them PERMANENT: templates and variables — the shift from writing prompts to owning prompt assets.",
  deep: "<p><strong>Why can't the labs just train hallucination away?</strong> They keep shrinking it — retrieval-grounded training, honesty-rewarding RL, calibration work (Anthropic publishes on exactly this) — but three structural forces persist. (1) <em>Coverage-honesty tension:</em> a model that answers only when certain is uselessly silent; one that always answers must extrapolate; where you set that dial is a product decision, and YOUR prompts re-set it per task (that's what the permission clause really does). (2) <em>Training-data truth is majority-vote:</em> the internet contains confident wrongness at scale; a prediction engine inherits its distribution unless grounded against something better — your documents, live search, your fact tables. (3) <em>Verification asymmetry:</em> generating a claim costs tokens; verifying it can cost a web fetch, a database, a human — so systems that are cheap to run are structurally cheaper to make fluent than to make true. Every layer in this lesson is one of those forces, answered. And the market knows it: «AI outputs you can actually trust» is, in 2026, a differentiator people pay for — ask anyone selling into law, finance, or medicine. You now know how it's built.</p>"
};

/* ------------------------------------------------ 3.5 */
L["3.5"] = {
  sub: "Stop writing prompts. Start owning them. Templates with variables turn your ten best prompts into a personal toolchest that compounds for years.",
  breath: "A prompt template is a proven prompt with variable slots — write once, fill the slots forever — and a maintained library of them is the cheapest professional asset you will ever build.",
  hook: "<p>A master carpenter doesn't re-invent the dovetail joint each morning — the joint is known; only the wood changes. Yet most AI users re-improvise their best prompts from memory, slightly worse each time, forever. The fix costs one hour and pays for a career: templatise your winners. This is also — quietly — the lesson where you start building things OTHER people can use, which is the seed of every productised service in Track 11.</p>",
  secs: [
    { h: "Anatomy of a template",
      b: "<p>A template = frozen craft + open slots. The frozen part carries everything Tracks 2–3 taught: role, structure, format contract, truth rules, edge-case law. The slots carry what changes per use:</p>" + PB("template — meeting minutes (example)", "You are a precise minute-taker for {TEAM_NAME}.\nFrom the transcript in <transcript>, produce:\n1. DECISIONS — each as: decision | owner | date agreed\n2. ACTIONS — each as: task | owner | deadline ({DEFAULT_DEADLINE} if unstated)\n3. OPEN — unresolved items with the blocking question\nRules: names exactly as spoken; anything ambiguous → OPEN, never guess an owner; no summary prose.\n<transcript>{TRANSCRIPT}</transcript>", "prompt") + "<p>Conventions that keep templates sane:</p><ul><li><strong>{SHOUTING_SNAKE} slots</strong> — visually unmissable, searchable, and self-documenting when named well ({AUDIENCE}, not {X}).</li><li><strong>Slot notes:</strong> one line per slot at the top of your saved copy — what goes in, with a good example. Future-you is a stranger (2.2's colleague test applies to your own artifacts).</li><li><strong>Version and date it.</strong> v3 beats «final_final2». When a template fails on a new case, the fix goes INTO the template (2.7's post-mortem, aimed at assets), and the version bumps.</li></ul>"},
    { h: "The library: ten winners beat a hundred hoards",
      b: "<p>Where templates live, in rising leverage:</p><ul><li><strong>Any notes app</strong> — fine on day one. Searchable beats organised.</li><li><strong>Claude Projects (4.2):</strong> a «Prompt Library» project whose knowledge contains your templates — ask «run my minutes template on this» and it fills the slots itself.</li><li><strong>Skills (4.8):</strong> the endgame — a template plus its instructions packaged so Claude applies it automatically when relevant. Your library stops being a place you visit and becomes behaviour Claude has.</li></ul><p>Curation law: a library you don't prune becomes a junk drawer. Keep the ~10 you actually reuse; archive the rest. The test for admission: <strong>used three times, worked three times.</strong></p>"},
    { h: "Meta-templates: prompts that write prompts",
      b: "<p>The compounding trick — a template whose OUTPUT is a template:</p>" + PB("meta-template — the templatiser", "Here is a prompt that worked well for me, and the output it produced:\n<prompt>{THE_WINNING_PROMPT}</prompt>\n<output>{WHY_IT_WAS_GOOD — paste or describe}</output>\nConvert it into a reusable template: (1) identify what should become variable slots, named clearly; (2) tighten the frozen parts using: explicit format contract, edge-case rules, and truth rules where facts are involved; (3) output the template plus a one-line usage note per slot; (4) list 2 situations where this template would FAIL, so I know its edges.", "prompt") + "<p>That last clause — «where would this fail» — is the professional touch: every tool has edges, and knowing them is what separates a library from a superstition collection.</p>"}
  ],
  worked: { t: "Worked example — the proposal template, from win to asset",
    html: "<div class='wstep'><p class='nar'><em>The moment:</em> my 2.7 iteration produced a proposal that won a client. Most people celebrate and move on. The operator move: <em>the SESSION was disposable; the PROMPT is the asset.</em> I run the templatiser on the final post-mortem prompt.</p></div><div class='wstep'><p class='nar'><em>What freezes:</em> the structure that worked (pain → approach → proof → price → next step), the tone rules («direct, zero filler»), the truth rule («case-study numbers only from {MY_RESULTS} — never invent»), the length caps. <em>What becomes slots:</em> {CLIENT_CONTEXT}, {SERVICE}, {MY_RESULTS}, {PRICE_STRUCTURE}. The templatiser also flags its edges: «fails for RFP-style formal tenders; fails when no prior results exist» — so I know when NOT to reach for it.</p></div><div class='wstep'><p class='nar'><em>Six months later:</em> proposal time is 20 minutes, v5 carries five clients' worth of learned fixes, and — Track 11 preview — the template itself has become part of what I SELL: «proposal system setup» for other freelancers. An artifact born from one good Tuesday. <em>Sessions evaporate; templates compound.</em></p></div>"},
  lab: { where: "claude.ai",
    html: "<p>Build your first two library entries right now. Take (1) the best prompt from your 2.7 post-mortem lab, and (2) any prompt you've reused from memory more than twice. Run each through the templatiser meta-prompt above (fill its slots with your material). Then test-drive one:</p>" + PB("prompt — test drive", "Here is my template:\n<template>\n[PASTE THE GENERATED TEMPLATE]\n</template>\nFill it for this case: [A REAL CURRENT CASE — give the slot values]. Then note: did any slot feel missing or awkward? Suggest one improvement to the template itself.", "prompt"),
    expect: "Two dated, versioned templates with slot notes and known edges — the first entries of a library that compounds. The test-drive usually surfaces one missing slot immediately: that's v2, and you just practised template maintenance." },
  mistakes: [
    "<b>Hoarding over curating.</b> Forty saved prompts you never reopen ≠ a library. Ten proven, pruned, versioned winners = a toolchest.",
    "<b>Slots named {X} and {STUFF}.</b> Six weeks later you won't know what goes where. Names + one-line notes, always.",
    "<b>Freezing too little.</b> A template that's mostly slots is a form, not an asset — the frozen craft (contracts, edge rules, truth rules) is where the value lives.",
    "<b>Freezing too much.</b> Client name hard-coded in the «template» — you saved a document, not a tool. If you'd edit it per use, it's a slot.",
    "<b>Fixing failures in the session instead of the template.</b> Patching output while the template stays broken means paying the same bug forever. Fix upstream, bump the version."
  ],
  quiz: [
    { q: "What belongs in the FROZEN part of a template vs the slots?",
      opts: ["Everything frozen — consistency above all", "Frozen: proven structure, format contracts, edge-case and truth rules. Slots: what genuinely changes per use — context, materials, parameters", "Everything slots — flexibility above all", "Whatever's shortest"],
      a: 1,
      why: ["Freeze the client's name and you've saved a document, not a tool.", "Correct — craft freezes, variables flow. The frozen part is Tracks 2–3 crystallised; the slots are Tuesday's specifics.", "All-slots is a blank form — the value WAS the frozen craft.", "Length is irrelevant; the freeze/flow boundary is the design decision."] },
    { q: "The admission test for your core library is:",
      opts: ["It sounded clever when written", "Used three times, worked three times", "It's over 500 words", "A friend liked it"],
      a: 1,
      why: ["Cleverness at write-time predicts little.", "Correct — reuse × reliability is the only test that matters; everything else is a hoard with good intentions.", "Great templates are often short; frozen craft is dense, not long.", "Your workflow is the only judge with jurisdiction."] },
    { q: "A template fails on a new kind of input. The operator response is:",
      opts: ["Abandon the template", "Patch this session's output and move on", "Fix the template itself (usually one new rule or slot), bump the version, note the edge", "Never use that input type again"],
      a: 2,
      why: ["One edge case rarely invalidates frozen craft.", "The classic leak: session patched, asset still broken, bug paid again next month.", "Correct — post-mortem energy flows to the ASSET (2.7's principle, aimed at your library). Templates are living documents with version numbers.", "Avoiding inputs to protect a tool is backwards."] }
  ],
  prac: [
    { tag: "warm", q: "Name the 5 templates YOUR work most obviously wants (look at your actual last two weeks), one line each on what freezes.",
      sol: "<b>Common winners to compare against:</b> status update (format + omissions freeze), meeting minutes (contract + never-guess-owners), client/boss email (voice + structure), document summariser (quotes-first + length caps), research brief (fact-table + provenance rules). Yours should map to what you REPEAT, not what sounds impressive." },
    { tag: "transfer", q: "Run the full cycle on one more real winner this week: post-mortem (2.7) → templatiser → slot notes → version header → one test drive → v2. Time yourself.",
      sol: "<b>Typical honest timing:</b> 25–40 minutes end to end. Now estimate uses-per-month × minutes-saved-per-use. Most people's first real template repays its build cost inside two weeks — write that number down; it's your first taste of the asset-thinking that Track 11 monetises." },
    { tag: "stretch", q: "Design the «library governance» for a 3-person team sharing templates: how do versions, edits, and quality control work so the shared library doesn't rot?",
      sol: "<b>One workable governance:</b> shared Project (4.2) holds the library; each template has an owner; anyone can propose a change but the owner merges and bumps versions; admission needs the 3×3 test verified by someone OTHER than the author; quarterly prune where anything unused is archived (not deleted). Sound familiar? It's code-review culture applied to prompts — and teams that do this are, in effect, running an internal prompt-engineering practice. Companies pay consultants to set exactly this up (Track 11, service idea #7)." }
  ],
  recap: "Freeze the craft, slot the variables, admit only 3×3 winners, fix failures upstream with version bumps — sessions evaporate, templates compound.",
  review: "From Lesson 2.7: the post-mortem's rewritten prompt was always destined here — iteration produces the ore; templates are the smelted metal.",
  bridge: "You own assets. Now prove they work: evals — the engineer's answer to «is prompt B actually better than prompt A?» — the least glamorous and most professional lesson in the track.",
  deep: "<p><strong>Templates are proto-software.</strong> Look at what you built: parameterised, versioned, documented, edge-cased artifacts that transform inputs to outputs — that's software engineering's shape, arrived at through prose. The industry noticed: prompt templates with variables are first-class objects in every serious LLM framework, product teams manage them in registries with rollout controls and A/B tests, and «prompt ops» is a real 2026 job function. The Claude-native ladder you'll climb: template in your notes → template in a Project's knowledge → Skill (4.8) that auto-applies → system prompt of an API product (9.2) → and at each altitude, the discipline you learned here (freeze/slot boundaries, versioning, edge documentation) is exactly what separates maintainable systems from prompt spaghetti. One more compounding fact: templates are TEACHABLE assets — they encode your judgment in a form a teammate (or a buyer) can wield without you. Assets that work without you are, of course, the definition of leverage — Track 12 will have opinions about this.</p>"
};

/* ------------------------------------------------ 3.6 */
L["3.6"] = {
  sub: "«It seems better» is not a measurement. Evals turn prompt tweaking from vibes into engineering — and they're lighter-weight than you fear.",
  breath: "An eval is a small fixed test set — real inputs plus what good output looks like — run against any prompt change, so improvements are measured, regressions are caught, and arguments end with data.",
  hook: "<p>You changed the prompt. The next answer looked better. Was it? Better on that one input, or better in general? Would yesterday's inputs still pass? Every software engineer recognises this problem — it's why tests exist — and in 2026 the discipline has fully arrived in prompting: Anthropic's own guidance treats <em>empirical evaluation</em> as the core of serious prompt work. The good news: a useful eval is twenty inputs in a spreadsheet, not a research lab. This lesson builds yours.</p>",
  secs: [
    { h: "The minimum viable eval",
      b: "<p>Three components, one afternoon:</p><ul><li><strong>A test set:</strong> 15–30 REAL inputs for your task — including the ugly ones (3.3's law: garbage is the job). Cover: typical cases, known-tricky cases, and at least two «should refuse / should say unknown» cases (truth behaviour is testable behaviour — 3.4).</li><li><strong>Expected outcomes:</strong> per input, what does success look like? Three grades of rigour: <em>exact</em> (extraction tasks: the correct JSON), <em>criteria</em> (open tasks: «mentions the deadline, under 100 words, no invented numbers»), <em>reference</em> (a gold example to compare against).</li><li><strong>A scoring pass:</strong> run the prompt on all inputs, score each pass/fail against expectations, get a number: 22/25. That number is your baseline — and the entire point: <strong>changes are judged by the number moving, not by how the latest answer felt.</strong></li></ul>"},
    { h: "Claude as the grader",
      b: "<p>Scoring 25 outputs by hand is fine once and tedious forever. The standard move: a second prompt grades the first's outputs — the <strong>LLM-as-judge</strong> pattern (your generator–critic chain from 3.1, formalised):</p>" + PB("judge template (adapt freely)", "You are grading outputs against criteria. For the input in <input>, the output in <output>, and the criteria in <criteria>: score each criterion PASS/FAIL with a one-line reason, then overall PASS only if all criteria pass. Be strict — when in doubt, FAIL with the doubt stated. No other text.", "prompt") + "<p>Judge rules of thumb: give it CRITERIA, not taste («under 100 words» beats «concise»); keep the judge prompt frozen while you iterate the task prompt (never move both walls at once); spot-check ~5 judge verdicts by hand the first time (grade the grader before trusting it); and for high-stakes evals, a stronger model judges a cheaper model's work (1.3's mix, again).</p>"},
    { h: "The eval workflow that changes your behaviour",
      b: "<ul><li><strong>Before «improving» anything:</strong> run the baseline. You cannot improve what you haven't measured — half of clever prompt tweaks turn out to move nothing.</li><li><strong>One change, one run</strong> (2.1's discipline, now instrumented): change the role OR add an example OR tighten a rule — rerun — did the number move? Which ITEMS flipped? Item-level diffs teach more than the total: «the two refusal cases started failing» is a diagnosis; «24→22» is just weather.</li><li><strong>Regressions are the headline.</strong> The tweak that fixes case 7 and silently breaks cases 2 and 9 is how prompts rot. Evals exist to make silent breakage loud.</li><li><strong>Freeze winners into templates</strong> (3.5) WITH their eval — the template's version history becomes «v4: 24/25, up from 21».</li><li><strong>Grow the set from production:</strong> every real-world failure you meet becomes a new eval case. Your test set slowly becomes a museum of every way the task has ever gone wrong — which is exactly what makes it valuable.</li></ul>"}
  ],
  worked: { t: "Worked example — settling the example-count argument with data",
    html: "<div class='wstep'><p class='nar'><em>The dispute:</em> my invoice-extraction template (3.3's contract) — would a 4th few-shot example help, or is it wasted tokens (2.3's economics question)? Opinions are free; let's buy a fact.</p></div><div class='wstep'><p class='nar'><em>The eval:</em> 24 real supplier messages — 15 typical, 5 multi-item, 2 garbage (should SKIP), 2 with unreadable amounts (should null, not guess). Expected outputs written once (~40 minutes, the real cost). Judge: strict criteria-checker with the totality and null-honesty rules as explicit criteria. <em>Baseline, 3 examples: 20/24 — both failures-to-null among the misses. Diagnosis before iteration: the misses cluster on null-honesty.</em></p></div><div class='wstep'><p class='nar'><em>The experiment:</em> variant A adds a 4th example (an unreadable-amount case, nulled — 2.3's show-the-edge-case principle). Variant B instead strengthens the null RULE with no new example. Run both: A = 24/24. B = 22/24. <em>Verdict bought:</em> the demonstration beats the description (2.3 vindicated, measured), the 4th example earns its tokens, template goes to v3 with its eval score in the header. Total exercise: 90 minutes. The argument it ended: permanent.</p></div>"},
  lab: { where: "claude.ai (+ any spreadsheet)",
    html: "<p>Build a real mini-eval for a template from 3.5. Collect 15 real inputs (include 2 ugly ones and 1 should-refuse). Write expectations. Then run your template on all 15 (paste inputs in batches), and grade with a judge in a FRESH chat:</p>" + PB("prompt — the judge", "Grade these input/output pairs against the criteria.\n<criteria>\n[YOUR CRITERIA — e.g., all fields present; dates YYYY-MM-DD; unreadable→null never guessed; one row per input; no extra text]\n</criteria>\n<pairs>\n[INPUT 1] → [OUTPUT 1]\n[INPUT 2] → [OUTPUT 2] …\n</pairs>\nFor each pair: PASS/FAIL per criterion (one-line reasons), overall PASS/FAIL. Then the total score and the LIST of failing items with their shared pattern, if any. Be strict.", "prompt") + "<p>Record the score in your template's header. Make ONE improvement, rerun, compare item-level.</p>",
    expect: "A baseline number, a failure pattern (there almost always is one), and the visceral experience of a tweak measured instead of vibed. If your one change moved nothing — congratulations, you just saved yourself from believing in it forever." },
  mistakes: [
    "<b>Eval sets of only clean inputs.</b> You're testing the happy path of a task whose whole difficulty is the unhappy path.",
    "<b>Moving prompt and judge together.</b> If both walls move, no measurement occurred. Freeze the judge while iterating the task.",
    "<b>Worshipping the total.</b> 22/25 → 23/25 while two previously-passing truth cases broke is a REGRESSION wearing an improvement's clothes. Read item-level diffs.",
    "<b>Trusting the judge blind.</b> Spot-check its verdicts once — a lenient judge inflates everything silently.",
    "<b>Building evals for everything.</b> Evals earn their cost on REPEATED, high-stakes, or shipping tasks. Your one-off haiku does not need a test suite."
  ],
  quiz: [
    { q: "The core thing an eval buys that «the last answer looked better» cannot:",
      opts: ["Longer answers", "Judgment across the whole input distribution — including catching what the change silently broke", "Cheaper tokens", "Faster generation"],
      a: 1,
      why: ["Irrelevant.", "Correct — one-sample impressions can't see regressions or generalisation; a fixed set + a number can. That's the entire discipline in one sentence.", "Evals cost tokens; they pay in decisions.", "Speed is unaffected — confidence is what accelerates."] },
    { q: "Why must the judge prompt stay FROZEN while you iterate the task prompt?",
      opts: ["Judges are expensive to edit", "If both change, score movement is unattributable — you moved two walls and learned nothing", "Judges can't be improved", "Anthropic requires it"],
      a: 1,
      why: ["Editing is free; attribution is the issue.", "Correct — single-variable discipline (2.1, 2.7) applied to measurement itself. Improve the judge SEPARATELY, then re-baseline.", "Judges improve too — just not mid-experiment.", "It's methodology, not policy."] },
    { q: "Your tweak took the total from 20/24 to 22/24, but the two should-refuse cases flipped to FAIL. Verdict?",
      opts: ["Ship it — the number went up", "Regression in the most safety-relevant behaviour, hidden inside a net gain — diagnose before shipping", "Delete the refusal cases from the set", "Evals are broken"],
      a: 1,
      why: ["The total is weather; the items are climate.", "Correct — truth/refusal behaviour breaking is exactly the silent rot evals exist to catch. Item-level reading is the professional habit.", "Deleting the cases that fail is… a career strategy, not an engineering one.", "The eval just did its precise job: made silent breakage loud."] }
  ],
  prac: [
    { tag: "warm", q: "For your minutes-template (or any 3.5 template): write the 6 judge criteria you'd freeze, including at least one truth criterion and one totality criterion.",
      sol: "<b>Example set:</b> (1) all three sections present; (2) every action has owner+deadline; (3) ambiguous owners → OPEN, never guessed [truth]; (4) decision count matches transcript decisions [totality]; (5) names verbatim; (6) zero prose outside sections. Criteria, not taste — each one checkable by a strict reader." },
    { tag: "transfer", q: "Grow your lab eval from 15 to 25 cases using the production rule: harvest real failures (from your actual usage this month) as new cases. Rerun and re-baseline.",
      sol: "<b>What you should notice:</b> the harvested cases are HARDER than your invented ones — reality writes better tests than imagination. This is why mature eval sets are museums of past failures, and why they appreciate in value with age while the prompts they guard keep improving." },
    { tag: "stretch", q: "A client asks you to «make the support-bot better». Using this track's full toolkit, describe your first week — before you change a single prompt.",
      sol: "<b>The operator's week one:</b> collect 30 real conversations (typical, tricky, failed); define success criteria WITH the client (what does 'better' mean — resolution? tone? escalation accuracy?); build the eval + judge; baseline the current bot; present the item-level failure patterns as the diagnosis. THEN propose changes — each to be measured against the baseline. You've just described a paid engagement structure (discovery → baseline → iterate → prove), and the deliverable that closes it is a NUMBER moving. Track 11 will price this; you already know how to do it." }
  ],
  recap: "Fifteen real inputs, written expectations, a frozen strict judge, one change per run, item-level diffs over totals — measured beats vibed, and every production failure becomes a test case.",
  review: "From Lesson 2.3: «examples beat descriptions» was a claim; today you saw it MEASURED (24/24 vs 22/24). That's the track's arc: craft → engineering.",
  bridge: "The finale: 25 battle-tested patterns — the whole track compressed into a working library you can raid forever. Bring your template file.",
  deep: "<p><strong>Evals are the industry's center of gravity now.</strong> Model labs live and die by them (every release note you read is an eval table); serious AI products maintain eval suites the way software maintains CI — run on every prompt change, every model upgrade, every framework bump. The 2026 tooling reflects it: Anthropic's platform ships eval tooling, and model upgrades are announced with migration guides that say, in effect, «rerun your evals». Three frontier notes: (1) <em>LLM-as-judge has known biases</em> — position bias (favouring the first answer shown), length bias (favouring longer), self-bias (favouring outputs in its own style); mitigations include randomised ordering, explicit criteria (as taught), and pairwise rather than absolute scoring for close calls. (2) <em>Eval sets leak:</em> if you tune long enough against a fixed set you overfit to it — refresh with production harvests (as taught). (3) The deepest point: an eval is a SPECIFICATION — writing down what «good» means, precisely enough to check, is harder and more valuable than any prompt tweak it guards. Teams that can't write the eval usually can't agree what the product should do; the eval argument is the requirements argument, surfaced early. You'll feel this again, hard, when agents arrive in Track 10 — where evals stop being optional entirely.</p>"
};

/* ------------------------------------------------ 3.7 */
L["3.7"] = {
  sub: "The whole track, compressed into 25 patterns you can raid — each one a named move with the prompt to run and the reason it works.",
  breath: "Twenty-five reusable prompt patterns across five families — clarity, structure, reasoning, truth, and iteration — each distilled from Tracks 2–3 into a form you can deploy in thirty seconds.",
  hook: "<p>Chess players don't calculate every position from scratch — they know the named patterns: forks, pins, skewers. This lesson is your pattern book. Every entry earned its place in Tracks 2–3; here they stand in one room, tagged and ready. Skim it now, raid it forever — and notice, as you read, that you can explain WHY each one works. That's the difference between you-today and you-two-tracks-ago: the patterns aren't magic anymore. They're physics you've already learned.</p>",
  secs: [
    { h: "Family 1 — Clarity (the 2.1–2.2 moves)",
      b: "<table><tr><th>#</th><th>Pattern</th><th>The move</th></tr><tr><td>1</td><td><strong>The Full Skeleton</strong></td><td>Role + Context + Task + Constraints + Format + Example — deploy for anything you'll actually use. (2.1)</td></tr><tr><td>2</td><td><strong>The Deliverable Swap</strong></td><td>Replace the topic with the artifact: «about our policy» → «a 150-word customer-facing paragraph explaining…». (2.2)</td></tr><tr><td>3</td><td><strong>Numbers-for-Adjectives</strong></td><td>Every vague adjective becomes a bound: short→under 100 words; a few→exactly 5; better→cut 30%, keep all facts. (2.2)</td></tr><tr><td>4</td><td><strong>The Edge-Case Law</strong></td><td>Legislate the mess before it happens: «mixed→classify by complaint; spam→SPAM; unclear→UNCLEAR, never guess.» (2.2)</td></tr><tr><td>5</td><td><strong>The Purpose Line</strong></td><td>One sentence of WHY: «this is for the CEO who has 60 seconds» — buys a hundred correct micro-decisions. (2.2)</td></tr></table>"},
    { h: "Family 2 — Structure (the 2.3–2.4 moves)",
      b: "<table><tr><th>#</th><th>Pattern</th><th>The move</th></tr><tr><td>6</td><td><strong>Few-Shot Coverage</strong></td><td>Three examples: one typical, one tricky, one edge — content varies, structure identical. (2.3)</td></tr><tr><td>7</td><td><strong>Schema by Example</strong></td><td>One filled sample row beats a page of field descriptions: {\"name\":\"…\",\"amount\":123.45}. (2.3+2.4)</td></tr><tr><td>8</td><td><strong>The Fence</strong></td><td>All pasted material inside labelled tags — &lt;email&gt;, &lt;policy&gt;, &lt;doc id='x'&gt; — instructions refer to tags by name. (2.4)</td></tr><tr><td>9</td><td><strong>Labelled Output</strong></td><td>«Reasoning in &lt;thinking&gt;, result in &lt;answer&gt;» — humans read one, scripts cut the other. (2.4)</td></tr><tr><td>10</td><td><strong>No-Preamble</strong></td><td>«No preamble, no closing summary — begin directly with [the first element].» The most-wanted instruction nobody writes. (2.4)</td></tr><tr><td>11</td><td><strong>Fill-the-Blanks</strong></td><td>Paste a template with ____ slots: «fill only the blanks, change nothing else.» Strongest pure-chat format control. (3.3)</td></tr></table>"},
    { h: "Family 3 — Reasoning (the 2.5 + 3.1–3.2 moves)",
      b: "<table><tr><th>#</th><th>Pattern</th><th>The move</th></tr><tr><td>12</td><td><strong>Named Steps</strong></td><td>Lend your checklist: «First facts. Then applicable rules. Then apply each. Then verdict.» (2.5)</td></tr><tr><td>13</td><td><strong>Think-Then-Commit</strong></td><td>Deliberation in &lt;thinking&gt;, then a committed first line: VERDICT: APPROVE/REJECT/NEEDS-INFO. (2.5+3.3)</td></tr><tr><td>14</td><td><strong>The Chain Split</strong></td><td>Two unrelated verbs = two prompts. Extract→compare→recommend, checkpoints between. (3.1)</td></tr><tr><td>15</td><td><strong>Map-Reduce</strong></td><td>Same focused prompt per item ×N, then one synthesis across the outputs. Volume's best friend. (3.1)</td></tr><tr><td>16</td><td><strong>Docs-Top-Task-Bottom</strong></td><td>The canonical long-context layout: fenced documents up top, role, then task+format at the bottom. (3.2)</td></tr><tr><td>17</td><td><strong>Quotes-First</strong></td><td>«Extract relevant passages into &lt;quotes&gt; (with ids), then answer ONLY from them.» Retrieval before reasoning. (3.2)</td></tr><tr><td>18</td><td><strong>The Panel</strong></td><td>«Answer as a growth marketer, a CFO, and a burned-out customer. Then reconcile.» Casting as analysis. (2.6)</td></tr></table>"},
    { h: "Family 4 — Truth (the 1.6 + 3.4 moves)",
      b: "<table><tr><th>#</th><th>Pattern</th><th>The move</th></tr><tr><td>19</td><td><strong>The Honest Out</strong></td><td>«If you don't know or the material doesn't say — say so plainly. An honest gap is a good answer.» (1.6/3.4)</td></tr><tr><td>20</td><td><strong>Provenance Tags</strong></td><td>Every factual sentence ends [source: doc-id / URL / model knowledge] — the last label aims your verification. (3.4)</td></tr><tr><td>21</td><td><strong>The Fact Table First</strong></td><td>Stage 1: claim | source | verbatim quote | date. Human checkpoint. Stage 2: write ONLY from the table. (3.4)</td></tr><tr><td>22</td><td><strong>The Hostile Critic</strong></td><td>Fresh chat: «verify every claim against sources: supported / unsupported / contradicted, with the quote or the gap.» (3.4)</td></tr></table>"},
    { h: "Family 5 — Iteration & Assets (the 2.7 + 3.5–3.6 moves)",
      b: "<table><tr><th>#</th><th>Pattern</th><th>The move</th></tr><tr><td>23</td><td><strong>Keep-Change-Because</strong></td><td>«Keep the table and tone. Change the intro to lead with the deadline — because readers skim.» Feedback that steers. (2.7)</td></tr><tr><td>24</td><td><strong>The Post-Mortem</strong></td><td>«What in my prompt led you there? Rewrite it so a fresh chat would produce what I wanted in one shot.» Every failure becomes an asset. (2.7)</td></tr><tr><td>25</td><td><strong>Ask-Me-First</strong></td><td>«Before starting, ask me up to 3 questions that would most improve the result.» The colleague-test, delegated. (2.7)</td></tr></table><div class='callout gold'><b>How to actually use this page:</b> don't memorise — RAID. Bookmark it (or print the Track 3 cheat sheet). When a session disappoints, come here, find the family the failure lives in (clarity? structure? reasoning? truth? iteration?), deploy the pattern. After ten raids you'll notice you stopped needing the page — the patterns moved into your hands. That's the track completing its job.</div>"}
  ],
  worked: { t: "Worked example — one nasty task, five patterns stacked",
    html: "<div class='wstep'><p class='nar'><em>The task:</em> «Our biggest client sent a 9-page angry email thread. Draft the response, and get it right.» Watch the patterns stack: <strong>#8 Fence</strong> the thread in &lt;thread&gt;. <strong>#17 Quotes-First:</strong> «extract every specific complaint and commitment made by either side into &lt;quotes&gt; with dates.» Checkpoint — I read the quotes (90 seconds, catches that one 'promise' was actually conditional).</p></div><div class='wstep'><p class='nar'><em>Then</em> <strong>#12 Named Steps</strong> for the analysis: «facts → what we owe → what we don't → risk if they walk.» <strong>#13 Think-Then-Commit:</strong> deliberation in &lt;thinking&gt;, then STANCE: APOLOGISE-AND-FIX / HOLD-WITH-GOODWILL / ESCALATE. <strong>#1 Full Skeleton</strong> for the draft itself (role: senior account lead; constraints: no new commitments beyond X; format: under 250 words).</p></div><div class='wstep'><p class='nar'><em>Finally</em> <strong>#22 Hostile Critic</strong> in a fresh chat: «find every sentence that could be quoted against us and every commitment this email creates.» It flags one phrase implying a discount. Fixed. Sent. <em>Five patterns, twenty minutes, zero new inventions — just the book, played. That's what mastery of this track looks like from the outside: calm.</em></p></div>"},
  lab: { where: "claude.ai",
    html: "<p>The graduation exercise. Pick the most consequential prompt-task in your real life this week. Before running it, write down — on paper — which 4+ patterns you'll stack and why. Run the stack. Then grade yourself:</p>" + PB("prompt — self-grade", "Here's the task I ran and how (patterns used: [LIST]). Here's what I got: [OUTCOME]. Review my pattern choices like a prompting coach: which pattern did the heaviest lifting, which was unnecessary, which SHOULD I have used from this list but didn't: fence, quotes-first, named steps, think-then-commit, edge-case law, fact-table-first, hostile critic, ask-me-first? Be specific.", "prompt"),
    expect: "A coached review of your own play — most people discover one pattern they consistently under-use (usually ask-me-first or the hostile critic). That's your growth edge; use it deliberately for a week and it joins your hands." },
  mistakes: [
    "<b>Memorising instead of raiding.</b> The page exists so you don't have to hold 25 things — hold five families and look up the moves.",
    "<b>Pattern-stacking trivial tasks.</b> Five patterns on a two-line email is ceremony. Stakes decide stack depth — the lesson of the whole course so far.",
    "<b>Deploying patterns without their reasons.</b> Each move works FOR a reason (conditioning, attention, grounding) — use one where its reason doesn't apply and it's superstition again.",
    "<b>Never graduating.</b> If you're still consulting the page for the Fence after a month, you're reading, not practising. Patterns are meant to move into your hands."
  ],
  quiz: [
    { q: "A colleague's research summary keeps stating plausible numbers with no trail. Which two patterns fix the workflow?",
      opts: ["#3 Numbers-for-Adjectives + #10 No-Preamble", "#21 Fact-Table-First + #20 Provenance Tags", "#18 The Panel + #25 Ask-Me-First", "#6 Few-Shot + #11 Fill-the-Blanks"],
      a: 1,
      why: ["Those are clarity/format moves — the failure is truth-shaped.", "Correct — gather claims with quotes and sources first (human checkpoint), then write only from the table with per-claim provenance. Family 4 exists for exactly this.", "Perspective and questions don't create evidence trails.", "Structure moves; the problem is grounding."] },
    { q: "You want one prompt to both analyse a dataset's issues AND draft the client email about them. The pattern book says:",
      opts: ["#14 Chain Split — two unrelated verbs, two prompts, checkpoint between", "#7 Schema by Example", "#19 The Honest Out", "Do it in one prompt but ask nicely"],
      a: 0,
      why: ["Correct — analysis and client-drafting are different tasks with different formats and stakes; the checkpoint between them is where you catch analysis errors before they reach the client.", "Schema helps the analysis output, but doesn't address the two-jobs problem.", "Truth pattern — orthogonal to the decomposition issue.", "Niceness doesn't merge attention budgets (3.1)."] },
    { q: "The deepest reason this pattern book works — the thread through all 25 — is:",
      opts: ["The patterns use impressive vocabulary", "Each pattern shapes WHERE the model's prediction machinery spends its attention and conditioning — they're applied physics, not incantations", "Claude recognises the pattern names", "Longer prompts are always better"],
      a: 1,
      why: ["Vocabulary is packaging.", "Correct — fences shape attention boundaries, quotes-first shapes conditioning order, committed verdicts shape the autoregressive rails, evals measure it all. You learned the physics in 1.1–1.2; the patterns are its engineering.", "The names are for YOUR memory — the model responds to the moves, not their titles.", "Several patterns (No-Preamble, Numbers-for-Adjectives) make prompts SHORTER."] }
  ],
  prac: [
    { tag: "warm", q: "From memory, name one pattern per family and the reason it works.",
      sol: "<b>Example answers:</b> Clarity — Edge-Case Law (legislates before mess). Structure — Fence (unambiguous boundaries). Reasoning — Quotes-First (conditioning on re-surfaced text). Truth — Hostile Critic (fresh context, no anchoring). Iteration — Post-Mortem (failure→asset). Any correct pairing passes — the reason mattering more than the name." },
    { tag: "transfer", q: "Audit your template library (3.5) against the book: which patterns does each template already embody, and which ONE pattern would most upgrade each?",
      sol: "<b>Typical findings:</b> most personal templates are strong on Family 1–2 (clarity, structure) and thin on Family 4 (truth) — few carry provenance or honest-out clauses. If that's you, patch the truth patterns in and bump versions. Your library just absorbed the whole track." },
    { tag: "stretch", q: "Write pattern #26 — a move YOU have discovered in your own practice that this book doesn't contain, in the book's format: name, the move, why it works.",
      sol: "<b>Grading your #26:</b> it must have (1) a name that evokes the move, (2) a deployable one-line instruction, (3) a WHY grounded in the mechanics you've learned (conditioning, attention, grounding, iteration). If you genuinely have one — and by now many learners do — you've crossed the line from user of patterns to author of them. That's L2 complete, and it's also the exact skill Track 11 clients pay for: people who can NAME what they do." }
  ],
  recap: "Twenty-five moves, five families, one physics: raid the book when sessions disappoint, stack by stakes, and let the patterns migrate from the page into your hands.",
  review: "From the whole of Tracks 2–3: every pattern here is a lesson you already learned — this page is just the armoury arranged for speed.",
  bridge: "Phase B complete: you have the craft. Phase C begins — the Claude app itself, where Projects, memory, files, artifacts, Research and Skills turn your craft into a daily operating system.",
  deep: "<p><strong>On pattern languages.</strong> The idea of a «pattern book» comes from architecture (Christopher Alexander's A Pattern Language, 1977) via software (the Gang of Four's Design Patterns, 1994): recurring problems earn named, reusable solutions, and the NAMES become how practitioners think and talk. Prompting reached this stage around 2023–2025 — chain-of-thought, few-shot, RAG, LLM-as-judge are now load-bearing vocabulary across the industry, and Anthropic's docs are themselves a pattern book in disguise. Why names matter more than they seem: a named pattern is compressible thought — «fence it and go quotes-first» transmits in four words what took two lessons to teach, which is how teams coordinate and how expertise gets SOLD (a Track 11 preview: consultants are, functionally, people with better pattern vocabularies and the judgment of when each applies). Your #26 exercise was the real graduation: pattern USERS follow books; pattern AUTHORS extend them. The next tracks hand your patterns to systems that run them — Projects and Skills first (Track 4), then agents that execute them ten thousand times (Track 10).</p>"
};

})();
