/* Track 5 — Cowork: Your AI Coworker (L2) */
(function(){
var L = window.LESSONS;

/* ------------------------------------------------ 5.1 */
L["5.1"] = {
  sub: "Cowork is the shift from answering to finishing: describe an outcome, step away, come back to completed work. Understanding the shift is understanding the decade.",
  breath: "Cowork is Anthropic's agentic workspace — Claude plans and executes multi-step tasks (files, documents, research, browsing) in sessions that keep running on Anthropic's servers even when you close your laptop, with you steering through permissions.",
  asOf: true,
  hook: "<p>Every tool so far shared one property: you stayed in the loop for every step. Ask, read, ask again — a brilliant colleague who only works while you watch. Cowork breaks the property. You describe the OUTCOME — «turn this folder of 40 interview transcripts into a themed findings report» — and Claude works: planning, reading, organising, drafting, checking, for minutes or longer, while you do something else. It's the difference between a helpdesk and a coworker. This track teaches you to be a great manager of one.</p>",
  secs: [
    { h: "What actually changed",
      b: "<p>Three mechanical shifts, each with consequences:</p><ul><li><strong>Multi-step autonomy.</strong> Cowork decomposes your outcome into steps and executes them — reading files, creating documents, revising, verifying — without a prompt per step. Your 3.1 chains, running themselves; your prompts graduate from «do this step» to «here is done».</li><li><strong>Real reach.</strong> Through the desktop app, Cowork reads and writes YOUR folders (the ones you grant). Outputs land as actual files — spreadsheets with formulas, formatted documents, organised directories — not chat text you copy out. It can also drive the browser and use your connectors (4.7).</li><li><strong>Sessions that outlive your attention.</strong> Cowork runs remotely on Anthropic's servers: close the laptop, the work continues; check from your phone; return to finished output. Delegation with an actual clock-off.</li></ul><p>Where it lives: Pro plans and up; desktop app is the full experience (local folders); web and mobile let you start and steer sessions anywhere.</p>"},
    { h: "The management mindset (your job changed)",
      b: "<p>With a coworker, your leverage moves from doing to <strong>specifying and reviewing</strong>:</p><ul><li><strong>Outcome specs beat step lists.</strong> «A folder called Clean/ with one merged PDF per client, named Client_YYYY.pdf, plus an index.xlsx of what went where» — the 2.2 deliverable-naming rule, now aimed at file systems.</li><li><strong>Acceptance criteria are your new prompt skill:</strong> how will the coworker know it's done and RIGHT? «Every source file accounted for in the index; nothing deleted, only copied» — 3.3's totality law, escaped from schemas into the real world.</li><li><strong>Checkpoints still belong to you</strong> (3.1): Cowork shows its plan and progress; you steer mid-flight or review at the end. Delegation ≠ abdication — the 1.6 triage decides how closely you watch which tasks.</li><li><strong>Usage is the meter to respect:</strong> agentic sessions burn far more allowance than chat (many steps × many tokens — 1.5's warning made real). Delegate what's WORTH a coworker's afternoon.</li></ul>"},
    { h: "What to delegate first (and what not yet)",
      b: "<ul><li><strong>Great first delegations:</strong> folder cleanups and reorganisations; extract-and-compile jobs (many files → one structured output); format conversions at scale; research-and-synthesise with files; first drafts of document sets. High tedium, clear success criteria, low blast radius.</li><li><strong>Not yet (until 5.2's permissions and 10.6's judgment):</strong> anything that deletes, sends, posts, or pays without review; tasks whose success you can't specify; work on files with no backup. The coworker is capable; the MANAGER earns trust gradually — in both directions.</li></ul>"}
  ],
  worked: { t: "Worked example — the first delegation, managed properly",
    html: "<div class='wstep'><p class='nar'><em>The task Nisha picks (deliberately low-risk, high-tedium):</em> a Downloads folder with 300+ files of chaos. <em>The outcome spec:</em> «Organise Downloads into subfolders by type and year (Documents/2025, Images/2024…). Rules: MOVE, never delete; anything ambiguous goes to Review/; produce a summary.md listing every move. Don't touch anything named 'tax'.»</p></div><div class='wstep'><p class='nar'><em>Note the manager's craft:</em> outcome + rules + an ambiguity dump (Review/ is the never-guess law from 2.2 wearing a folder costume) + a do-not-touch fence + an audit artifact (summary.md = her verification path, 1.6). She watches the plan appear, approves, makes tea.</p></div><div class='wstep'><p class='nar'><em>Twelve minutes later:</em> 300 files sorted, 14 in Review/ (correctly — weird extensions, ambiguous dates), the tax files untouched, and a summary she skims in 90 seconds. <em>Her verdict, worth quoting: «It didn't just do it. It did it the way a careful person would — because I specified what careful meant.»</em> That's the whole track in one sentence.</p></div>"},
  lab: { where: "Claude desktop app — Cowork (Pro+)",
    html: "<p>Run YOUR first delegation on a real, low-stakes mess (Downloads, Desktop, a project folder). Grant Cowork access to just that folder, then:</p>" + PB("prompt — first delegation", "Organise this folder. Outcome: subfolders by [YOUR SCHEME — type/year/project]; every file MOVED (never deleted); anything you're unsure about goes to a Review/ folder instead of being guessed; nothing outside this folder touched. Finish with a summary.md listing every file's old → new path, plus a count check: files before = files after. Show me your plan before you start.", "prompt"),
    expect: "A visible plan, a period of autonomous work you can watch or ignore, and a result you audit via summary.md's count check in under two minutes. The count check matching is your first taste of ACCEPTANCE CRITERIA doing their job." },
  mistakes: [
    "<b>Delegating outcomes you can't specify.</b> «Sort out my files somehow» gets you somebody-else's-logic. If you can't state done-and-right, you're not ready to delegate it.",
    "<b>Step-by-step micromanaging.</b> Prompting each move defeats the point — specify the outcome and rules, then let it work. (You'll unlearn chat reflexes here.)",
    "<b>First delegation = highest stakes.</b> Starting with client deliverables or irreplaceable files. Earn mutual trust on tedium first.",
    "<b>No audit artifact.</b> Without the summary.md / index / count-check, verification means re-doing the work by eye. Build the receipt INTO the spec.",
    "<b>Ignoring the usage meter.</b> An afternoon of agentic sessions can consume days of chat allowance — delegate deliberately, batch related work into one session."
  ],
  quiz: [
    { q: "The essential shift Cowork represents:",
      opts: ["A smarter model", "From answering (you drive each step) to finishing (Claude executes multi-step outcomes autonomously, with your steering)", "Cheaper tokens", "Offline mode"],
      a: 1,
      why: ["Same model family (1.4's law, again).", "Correct — chat answers; Cowork completes. Your role moves to specifying and reviewing.", "The opposite — agentic work consumes MORE usage; it pays in outcomes.", "It runs on Anthropic's servers — that's how sessions outlive your laptop lid."] },
    { q: "«Anything ambiguous goes to Review/ instead of being guessed» is:",
      opts: ["Unnecessary caution", "The never-guess edge-case law (2.2/3.3) applied to file operations — ambiguity gets quarantined for human eyes", "A way to slow Cowork down", "Only for beginners"],
      a: 1,
      why: ["It's the difference between a careful coworker and a confident mess-maker.", "Correct — the same principle that made your extraction contracts trustworthy makes your delegations trustworthy. Principles travel; surfaces change.", "It barely affects speed and transforms safety.", "It's how professionals spec delegation at every level — including to humans."] },
    { q: "Your first Cowork delegations should be:",
      opts: ["Your most important client deliverable", "High-tedium, clearly-specifiable, low-blast-radius tasks — trust is earned in both directions", "Something impossible, to test limits", "Deleting old files permanently"],
      a: 1,
      why: ["Stakes-first is backwards — you haven't calibrated what it does well yet.", "Correct — folder cleanups and extract-compile jobs teach you its strengths while nothing important is exposed. Then climb.", "You'll learn more from calibration than from stress-testing.", "Delete-authority is exactly what you DON'T grant early (or automate lightly, ever)."] }
  ],
  prac: [
    { tag: "warm", q: "Write the outcome spec (not steps) for: «deal with the 200 photos from the family event across three phones».",
      sol: "<b>Example spec:</b> «One folder Event_2026/ containing: all photos deduplicated (keep highest resolution), renamed evt_NNN by timestamp, blurry/accidental shots moved to Rejects/ (not deleted), a best_30/ subfolder of the strongest shots, and a summary.md with counts (in = kept + rejects). Never delete anything.» Outcome + rules + quarantine + receipt." },
    { tag: "transfer", q: "List the 5 highest-tedium recurring tasks in your work. Mark each: specifiable? blast radius? Then rank as delegation candidates and run #1 this week.",
      sol: "<b>The ranking logic:</b> specifiability × tedium ÷ blast-radius. Typical winners: report assembly, file organisation, data compilation, format conversion. Whatever wins — its outcome spec is your homework, and its saved-minutes number joins the 4.8 ledger." },
    { tag: "stretch", q: "A friend says: «If Cowork does the work, what's left of MY value?» Give the manager's answer — specifically, the three human contributions that grew MORE valuable.",
      sol: "<b>The three:</b> (1) SPECIFICATION — knowing what done-and-right means is now the scarce skill (badly-specified delegation produces confident garbage at scale); (2) JUDGMENT — the checkpoints, the triage, the «this needs a call not an email» calls; (3) ACCOUNTABILITY — clients pay a person who stands behind the output. Notice these are exactly what Tracks 2–4 trained. The uncomfortable-but-liberating truth: Cowork devalues doing and revalues managing — and this course has been quietly teaching you management all along." }
  ],
  recap: "Cowork finishes instead of answering: specify outcomes with rules, quarantines and receipts; review at checkpoints; start with tedious low-stakes work; respect the usage meter — you're a manager now.",
  review: "From Lesson 1.4: the surface map said Cowork's superpower is delegation — three tracks later you have the specification skills that make delegation safe.",
  bridge: "Next: the mechanics — granting folders, the three permission modes, and the task loop that lets you steer a working agent without hovering.",
  deep: "<p><strong>Why «agentic knowledge work» arrived in 2026 and not 2023.</strong> Three curves had to cross. Capability: models needed to sustain coherent multi-step plans over long horizons without drifting (the 2025–26 generation's signature improvement). Safety architecture: autonomy at file-system reach required permission systems, sandboxing, action review, and injection defenses mature enough to ship to consumers (Anthropic's safety-first posture explains both why Cowork exists and why it arrived when it did). Economics: agentic sessions consume order-of-magnitude more tokens than chat — viable only once inference costs fell far enough (1.3's cheaper-every-year trend, load-bearing). The strategic read for YOUR career: the chat era rewarded prompt-writers; the agentic era rewards outcome-specifiers and verification-designers — skills with much deeper moats, because they're management skills that happen to point at machines. Everything Cowork does in this track, the API's agents do programmatically in Track 10; learn the management here, where the UI holds your hand.</p>"
};

/* ------------------------------------------------ 5.2 */
L["5.2"] = {
  sub: "Folders, the three permission modes, and the task loop — Cowork's control surfaces, and how a professional sets each dial.",
  breath: "You grant Cowork specific folders (nothing else), choose a permission mode per task — Manual (approve each action), Auto (autonomous with safety checks), or Skip (no checks) — and steer through a live task loop of plan, progress, and interventions.",
  asOf: true,
  hook: "<p>Handing a new employee the office keys is not one decision — it's a dozen: which rooms, which hours, which approvals, which spend limit. Cowork compresses those into three control surfaces: WHAT it can touch (folders and connectors), HOW MUCH it decides alone (permission modes), and WHERE you intervene (the task loop). Most users click through these on defaults. Operators set them per task, deliberately — and that difference is the entire gap between «AI horror story» and «AI success story».</p>",
  secs: [
    { h: "Reach: folders, connectors, and the fence",
      b: "<ul><li><strong>Explicit folder grants.</strong> Cowork touches only directories you've connected — the fence from 4.7, applied to your disk. Operator habit: <strong>per-project grants</strong>, not «my whole home directory» — matching reach to task (minimum-necessary, the recurring law).</li><li><strong>Session vs local:</strong> sessions run in an isolated environment on Anthropic's servers; local folders bridge through the desktop app (keep it open when the task needs your disk or browser). Cloud-side work continues laptop-closed.</li><li><strong>Folder-specific instructions:</strong> you can attach standing instructions to a folder («never touch _originals/») — a CLAUDE.md-shaped idea you'll meet fully in 7.3; here it's a permission expressed as prose.</li><li><strong>Connectors and the browser</strong> ride along: a Cowork task can read your granted Drive, drive Chrome (6.1's powers, delegated). Same grants, same ladder-of-trust thinking (4.7).</li></ul>"},
    { h: "The three modes: match autonomy to reversibility",
      b: "<table><tr><th>Mode</th><th>Behaviour</th><th>Use when…</th></tr><tr><td><strong>Manual</strong></td><td>Pauses for your approval before actions</td><td>New task types; anything touching originals; your calibration week</td></tr><tr><td><strong>Auto</strong></td><td>Proceeds autonomously; built-in safety checks block clearly unsafe actions; deletions still require you</td><td>The daily default once a task type is proven — speed with a net</td></tr><tr><td><strong>Skip</strong></td><td>No approvals, no automatic checking</td><td>Rarely: fully-reversible sandboxes, copies-only work, where you've decided review costs exceed risks</td></tr></table><p>The selection principle you've been building since 1.4: <strong>autonomy scales with reversibility.</strong> Copy-and-organise in a duplicated folder? Auto, happily. Anything that sends, deletes, or edits sole-copies? Manual — or restructure the task so it CAN'T (work on copies; output to new folders; quarantine ambiguity). The best permission decision is often a task-design decision. Note Auto burns more usage than Manual (more autonomous exploration) — one more reason mode choice is a real decision.</p>"},
    { h: "The task loop: managing without hovering",
      b: "<ul><li><strong>The plan is your first checkpoint.</strong> Cowork proposes its approach before grinding — read it. Thirty seconds here catches mis-specifications before they compound (cheaper than any recovery).</li><li><strong>Progress is glanceable, interruptible:</strong> you can watch, or check in periodically, or steer mid-task («skip the 2019 files», «that naming is wrong — use YYYY-MM») — the keep/change/because craft (2.7) works on running work.</li><li><strong>Parallel sessions:</strong> multiple Cowork tasks can run simultaneously — the moment you genuinely feel like a manager with a small team. Manage like one: don't launch five unproven task types at once.</li><li><strong>The review ritual:</strong> every session ends with your audit of the receipt artifact you specified (5.1). Green? Raise that task type's autonomy next time. Surprises? Tighten the spec — and log what you learned (the 2.7 post-mortem, delegation edition).</li></ul>"}
  ],
  worked: { t: "Worked example — one task, three dials, deliberately set",
    html: "<div class='wstep'><p class='nar'><em>The task:</em> Imran's 5 years of bank statements (PDFs, one messy folder) → per-year folders + a master index spreadsheet. <em>Dial 1, reach:</em> he creates Statements_Work/, COPIES the originals in, grants Cowork that folder only. The originals never meet the agent — reversibility purchased upfront, two minutes.</p></div><div class='wstep'><p class='nar'><em>Dial 2, mode:</em> first time on this task type → Manual. The plan appears: parse dates from filenames and content, organise by year, build index.xlsx. He approves batch one, watches ten files land correctly, then — calibration achieved — switches to Auto for the rest. <em>Mode isn't a personality trait; it's a per-task, per-phase decision.</em></p></div><div class='wstep'><p class='nar'><em>Dial 3, the loop:</em> mid-run he spots 2021 statements splitting into two folders (bank renamed itself mid-year) — one steering message fixes the rule. Review ritual: index.xlsx says 60 files in, 60 accounted, 3 in Review/ (password-protected PDFs — correctly quarantined, not guessed at). <em>Next quarter, this exact task runs on Auto from minute one — and in 5.5, on a schedule without him.</em> Trust, climbed one rung at a time.</p></div>"},
  lab: { where: "Claude desktop app — Cowork",
    html: "<p>Practice the dials on a copies-only task. Duplicate any document-heavy folder, grant ONLY the copy, then:</p>" + PB("prompt — dials drill", "Task: reorganise this folder by [YOUR SCHEME] and build an index.xlsx (filename, date, category, new location). Rules: this folder only; move never delete; unsure → Review/; finish with a count check in the index. Start by showing me your plan and your first 5 intended actions — I'll approve those, and if they're right I'll tell you to continue autonomously.", "prompt") + "<p>Approve the first actions in Manual, then explicitly grant autonomy for the rest. Mid-run, send one steering correction (any refinement you notice). End with the review ritual.</p>",
    expect: "You'll have operated all three dials in one session: scoped reach (the copy), mode transition (Manual→Auto on evidence), and mid-flight steering. That sequence IS professional Cowork usage — everything else is scale." },
  mistakes: [
    "<b>Whole-disk grants for one-folder tasks.</b> Reach should embarrass nobody if the session log went public. Scope per task.",
    "<b>One mode forever.</b> Manual-always wastes the point; Auto-always on unproven task types outsources calibration you haven't done. The mode is a decision, made per task.",
    "<b>Skipping the plan read.</b> The 30-second checkpoint that catches mis-specs before they multiply across 300 files. Never skip on new task types.",
    "<b>Working on sole copies.</b> The cheapest safety in computing is a duplicated folder. Buy it every time stakes exist.",
    "<b>No mode-upgrade path.</b> Running proven weekly tasks in Manual forever = paying review tax on earned trust. Calibrate, then climb."
  ],
  quiz: [
    { q: "The principle governing mode choice:",
      opts: ["Always maximum autonomy — that's the point", "Always Manual — safety first", "Autonomy scales with reversibility — and the best permission decision is often redesigning the task to BE reversible", "Alphabetical order"],
      a: 2,
      why: ["Unproven task types on full autonomy is how horror stories start.", "Manual-forever pays permanent tax on earned trust and abandons Cowork's point.", "Correct — copies-only work earns Auto; sole-copy edits demand Manual or a redesign. Reversibility is the axis, and you can ENGINEER it.", "No."] },
    { q: "Cowork can touch:",
      opts: ["Everything on your computer", "Only folders you've explicitly connected (plus granted connectors) — the fence is real and yours to draw", "Only cloud files", "Nothing — it's simulation"],
      a: 1,
      why: ["The fence exists precisely so this isn't true.", "Correct — explicit, scoped, revocable grants: 4.7's model applied to your disk. «Couldn't find it» often means «wasn't granted» (the recurring diagnostic).", "Local folders bridge through the desktop app — that's half the value.", "The files it writes are entirely real; hence the fences."] },
    { q: "Reading the proposed plan before approving matters most because:",
      opts: ["It's polite", "Mis-specifications caught at the plan stage cost 30 seconds; caught after execution they cost the whole cleanup", "Plans are legally binding", "It doesn't matter"],
      a: 1,
      why: ["Machines don't need courtesy (2.2) — YOU need the checkpoint.", "Correct — the plan is your spec reflected back; disagreements there are cheap. It's 3.1's checkpoint discipline at delegation scale.", "No, but treating them as a contract-to-review is the right instinct.", "One skipped plan-read on a 300-file task will change your mind permanently."] }
  ],
  prac: [
    { tag: "warm", q: "Assign modes with one-line justifications: (a) organising a copies-only photo folder, (b) renaming files inside your ONLY copy of client deliverables, (c) weekly report assembly you've run 10 times clean, (d) a brand-new «clean up my email drafts» experiment.",
      sol: "(a) Auto — fully reversible (b) Manual — or better, redesign: copy first, then Auto (c) Auto — trust earned by evidence (d) Manual — calibration week for a new task type touching real content. If you answered (b) with «just Manual», half-credit: the redesign is the pro move." },
    { tag: "transfer", q: "Write the «delegation card» for your #1 candidate task from 5.1: folder scope, mode + when it upgrades, the receipt artifact, and your review ritual. Then run it.",
      sol: "<b>Card format worth keeping:</b> TASK / SCOPE (exact folders) / MODE (start → upgrade trigger) / RECEIPT (what proves done-and-right) / REVIEW (what you check, how long it takes). Five lines. A stack of these cards is literally an operations manual for your AI coworker — and yes, that stack is sellable expertise (11.2 will name it)." },
    { tag: "stretch", q: "Design the permission policy for a 2-person design studio adopting Cowork: what's Auto-eligible, what stays Manual-always, what's banned from delegation entirely, and how does a task type EARN promotion?",
      sol: "<b>One sound policy:</b> Auto-eligible — internal organisation, format conversion, draft generation, all on copies. Manual-always — anything client-visible before send, edits to sole-copy assets, bulk communications. Banned — deletions (humans only), payments, anything under NDA whose contract wasn't checked (11.7 preview). Promotion — 3 clean Manual runs with matching receipts → Auto, logged in a shared doc. You've just written an AI-operations policy; companies pay consultants real money for this exact document (Track 11, service #4)." }
  ],
  recap: "Three dials, set per task: reach (minimum folders, copies where possible), mode (autonomy scales with reversibility, upgraded on evidence), and the loop (read the plan, steer mid-flight, audit the receipt).",
  review: "From Lesson 4.7: the connector trust-ladder and the Cowork mode-ladder are the same ladder — grant, verify, climb. One mental model, every surface.",
  bridge: "Controls mastered. Now the payload: file automation — the extract-transform-organise patterns that turn folder chaos into structured assets, at delegation scale.",
  deep: "<p><strong>What the modes really are: a human-in-the-loop dial.</strong> AI-safety literature frames oversight as a spectrum — human-in-the-loop (approve each action), human-on-the-loop (monitor, intervene on exception), human-out-of-the-loop (audit after) — and Cowork's Manual/Auto/Skip maps onto it almost exactly. Two design details worth admiring, because you'll copy them when building your own agents (Track 10): <em>asymmetric caution</em> — even Auto mode keeps destructive actions (deletes) behind human confirmation, encoding «reversibility decides» into the product itself; and <em>legible intervention</em> — the plan-then-execute structure exists so a human can disagree at the cheapest possible moment. The deeper 2026 point: permission design is becoming a professional literacy. The EU AI Act's oversight requirements, enterprise AI policies, agent-safety frameworks — all are versions of the question you practised today: «how much may the machine decide alone, about what, with which undo?» You now answer it with a principle instead of a shrug — which, when a client asks it about THEIR operations, is a billable conversation.</p>"
};

/* ------------------------------------------------ 5.3 */
L["5.3"] = {
  sub: "The bread-and-butter of delegation: extract, transform, organise — folder-scale patterns that turn document chaos into structured, usable assets.",
  breath: "Most valuable Cowork work is one of three patterns — extract (many files → one structured dataset), transform (every file → new format/shape), organise (chaos → system) — each specified with contracts, quarantines and receipts.",
  hook: "<p>Ask any office worker where their hours actually go and you'll hear the same verbs: pulling numbers out of PDFs, converting this into that, finding things, filing things. Not thinking — MOVING INFORMATION BETWEEN CONTAINERS. It's the least human-worthy work in the building, and it's precisely what Cowork devours. This lesson gives you the three patterns that cover ~80% of it, with the specification craft that makes each one trustworthy. This is also — not coincidentally — the most immediately sellable skill in the course so far.</p>",
  secs: [
    { h: "Pattern 1 — EXTRACT: many files, one dataset",
      b: "<p><strong>Shape:</strong> a folder of documents (invoices, CVs, contracts, reports) → one structured output (spreadsheet, index, database-ready file).</p><ul><li><strong>The spec is your 3.3 contract, folder-sized:</strong> schema by example, types, null-honesty («unreadable → null, never estimate»), totality («one row per source file, SKIPPED rows included; row count = file count»), and source-binding — <strong>every row carries its source filename</strong>, so any value is one click from its origin (3.2's quotes-first, filesystem edition).</li><li><strong>Scale changes verification, not principles:</strong> you can't eyeball 400 rows — so the spec includes machine-checkable receipts (count checks, totals that should reconcile) plus a random spot-check ritual (pick 5 rows, open their sources — 1.6 sampling).</li><li><strong>Classic jobs:</strong> invoices→expense sheet; CVs→candidate matrix; contracts→terms register; survey PDFs→response table; receipts→tax prep.</li></ul>"},
    { h: "Pattern 2 — TRANSFORM: every file, new shape",
      b: "<p><strong>Shape:</strong> N inputs → N outputs, each converted, reformatted, cleaned or re-voiced.</p><ul><li><strong>The map discipline (3.1):</strong> one clear per-file rule, applied uniformly — «each meeting transcript → a one-page minutes doc using my minutes skill (4.8!)», «each product photo folder → renamed and web-resized copies», «each old proposal → the new template».</li><li><strong>Outputs beside, never over:</strong> transformed files land in Out/ mirroring the input structure; originals untouched. Reversibility by architecture (5.2), zero willpower required.</li><li><strong>Skills shine here:</strong> if the transformation is one you do often, the per-file rule should BE a skill — Cowork applies it ×200 with your edge-cases and truth rules riding along automatically. The 4.8 staircase, paying compound interest.</li></ul>"},
    { h: "Pattern 3 — ORGANISE: chaos into system",
      b: "<p><strong>Shape:</strong> an unstructured pile → a designed structure (you met it in 5.1's first delegation; here's the full craft).</p><ul><li><strong>Design the taxonomy BEFORE the run</strong> — or better, make taxonomy-design step one: «propose a folder scheme for this mess based on what's actually in it; I'll approve before you move anything.» (Plan-checkpoint discipline, 5.2, applied to information architecture.)</li><li><strong>The three non-negotiables:</strong> move-don't-delete, Review/ quarantine for ambiguity, and the old→new receipt log. You know why by now — they're the same three every pattern needs, because they're the same three ANY trustworthy process needs: reversibility, honesty about uncertainty, auditability.</li><li><strong>Maintenance mode:</strong> once organised, the same spec re-run weekly keeps it organised — which is 5.5's scheduled tasks knocking on the door.</li></ul>"}
  ],
  worked: { t: "Worked example — 18 months of client documents, three patterns in one run",
    html: "<div class='wstep'><p class='nar'><em>The mess:</em> a consultant's Clients/ folder — 900 files, six clients, no system: proposals, invoices, deliverables, notes, all soup. <em>The delegation, staged like an operator:</em> Stage 1 (ORGANISE): «propose a taxonomy from the actual contents» — Cowork suggests Client/{Proposals,Invoices,Deliverables,Notes}/YYYY. She adjusts one thing, approves. Files flow; 22 land in Review/ (multi-client documents — genuinely ambiguous, correctly quarantined).</p></div><div class='wstep'><p class='nar'><em>Stage 2 (EXTRACT), same session:</em> «from the Invoices/ folders, build master_invoices.xlsx: client, number, date, amount, status — schema per this example row; unreadable → null; every row carries source filename; total per client at the bottom.» The reconciliation receipt: her accounting software's totals should match — two clients don't. Spot-check via source filenames: three invoices existed only as email attachments, never saved. <em>The extraction just audited her filing — nobody asked it to; receipts do that.</em></p></div><div class='wstep'><p class='nar'><em>Stage 3 (TRANSFORM):</em> «every Proposals/ file older than the new template → regenerate cover page in the current template, output to Refreshed/, originals untouched.» <em>Ninety minutes of session time, maybe six minutes of her attention at checkpoints. The manual estimate for the same work: two full days — which is the number she'll quote when she sells this exact service in Track 11.</em></p></div>"},
  lab: { where: "Claude desktop app — Cowork",
    html: "<p>Run a real EXTRACT on your own paper trail (receipts folder, statements, invoices — copies, per 5.2):</p>" + PB("prompt — folder extraction", "From every document in this folder, extract into expenses.xlsx with EXACTLY these columns: source_file, date (YYYY-MM-DD), vendor, amount (number only), category (one of: [YOUR LIST]), status (OK / UNREADABLE / NOT_AN_EXPENSE).\nRules: one row per file — no file skipped silently; anything unreadable → null in that field, never estimated; status NOT_AN_EXPENSE for irrelevant files (with the filename kept so I can see what it was).\nReceipts: bottom of sheet = row count vs file count, and total amount. Then list 5 random rows for me to spot-check against their sources.", "prompt"),
    expect: "A dataset with airtight accounting: counts match, nulls where reality was unreadable, and your 5-row spot-check passing. If the spot-check catches an error — even better: you just experienced why receipts and sampling are in the spec, on data that's yours." },
  mistakes: [
    "<b>Extraction without source-binding.</b> Rows with no source_file column = claims with no citations (3.2/3.4) — unverifiable at exactly the scale where verification matters most.",
    "<b>Transforms that overwrite.</b> In-place conversion of originals is the classic self-inflicted wound. Out/ folders exist; use them by default.",
    "<b>Taxonomy improvised mid-run.</b> Letting structure emerge file-by-file yields drift (2021's logic ≠ file 700's logic). Design or approve the scheme first.",
    "<b>Eyeball-verification at scale.</b> 400 rows don't get proofread; they get count-checks, reconciliation totals, and random sampling. Build receipts machines can check.",
    "<b>One-off specs for recurring messes.</b> If the folder re-chaosifies monthly, the spec belongs in a template (3.5) → skill (4.8) → schedule (5.5). Climb the staircase."
  ],
  quiz: [
    { q: "Every row of a folder-scale extraction must carry its source filename because:",
      opts: ["Filenames are decorative", "It's the citation system — any value is one click from its origin, making spot-checks and dispute-resolution instant at scales eyes can't cover", "Spreadsheets require it", "It uses more columns"],
      a: 1,
      why: ["Nothing in a contract is decorative.", "Correct — source-binding is 3.4's provenance discipline at filesystem scale. The consultant's missing-invoices discovery happened BECAUSE of it.", "No format requires it; trustworthiness does.", "One column, purchased with infinite auditability."] },
    { q: "The right verification for a 400-row extraction:",
      opts: ["Read every row", "Trust it — the model is good now", "Machine-checkable receipts (count match, reconciling totals) plus a random 5-row spot-check against sources", "Ask Claude if it's sure"],
      a: 2,
      why: ["Two hours of eyeball work IS the tedium you delegated away.", "1.6 never retires; it re-tools.", "Correct — verification scales by changing FORM: deterministic checks for totality, sampling for accuracy. Same principles, industrial instruments.", "Still the weak ritual (1.6), at any scale."] },
    { q: "«Propose the folder scheme from the contents; I approve before anything moves» is valuable because:",
      opts: ["It doubles the work", "Information architecture is a DESIGN decision — the plan-checkpoint catches a bad taxonomy when it costs one message, not after 900 files embody it", "Cowork can't move files without it", "Approval is legally required"],
      a: 1,
      why: ["It adds one checkpoint and removes whole categories of rework.", "Correct — 5.2's plan-read, aimed at structure. Drifting taxonomy is the organise-pattern's signature failure, and it's fully preventable.", "It can — this is craft, not requirement.", "No — just wisdom."] }
  ],
  prac: [
    { tag: "warm", q: "Classify these as extract / transform / organise (some are compounds): (a) «all our old blog posts → new CMS format», (b) «every warranty document I own → one register with expiry dates», (c) «this shared drive is unusable», (d) «CVs → matrix, then folders by role».",
      sol: "(a) transform (b) extract (c) organise (d) <b>compound: extract then organise</b> — and compounds staged in one session (like the consultant) are where Cowork shines brightest. Recognising the pattern instantly = specifying it instantly." },
    { tag: "transfer", q: "Design the full three-stage delegation (organise → extract → transform) for the messiest folder in your life, with all three non-negotiables and receipts per stage. Run at least stage one.",
      sol: "<b>The bar:</b> each stage has its own receipt (move-log; count+reconciliation; Out/ manifest), quarantine rules, and a checkpoint between stages. If your three stages could run as one session with two approvals — you've written a professional delegation. That document is the deliverable; the clean folder is the receipt." },
    { tag: "stretch", q: "Price the consultant's job (900 files, 3 patterns) as a service: what would you charge a small firm for it, what does it cost you to deliver, and what's the recurring upsell?",
      sol: "<b>Credible numbers (2026 market — 11.1 has sources):</b> one-time «document chaos → system + registers» for a small firm: ₹15–40k (US$500–2,000 equivalent) depending on volume/sensitivity — your delivery cost: a few hours of specification + checkpoints + verification, mostly while sessions run. Recurring upsell: monthly maintenance run + updated registers at ₹5–10k/month (a scheduled task you review — 5.5). Margin comes from specification skill, not labour — which is why Tracks 2–5 ARE the money training, and Track 11 just adds the packaging." }
  ],
  recap: "Extract with contracts and source-binding, transform to Out/ folders with uniform per-file rules, organise with pre-approved taxonomies — and verify at scale with receipts machines can check plus samples humans do.",
  review: "From Lesson 3.3: the extraction contract you wrote for one WhatsApp message just processed 400 files unchanged — principles written small run large. That's why the course taught them small first.",
  bridge: "Files mastered. Next: the office suite — Cowork producing the documents, spreadsheets and presentations themselves, formulas and formatting included.",
  deep: "<p><strong>Why «information logistics» is the killer app.</strong> Studies of knowledge-work time-use keep finding the same embarrassing split: the majority of white-collar hours go to gathering, reformatting, filing and re-finding information — not analysis, not creation, not judgment. That's why the three patterns punch so far above their apparent sophistication: they attack the DENOMINATOR of office work. Two structural notes for your operator brain. First, <em>the patterns are closed under composition</em> — extract feeds transform feeds organise feeds extract (the consultant's run) — which is why a small pattern vocabulary covers such a large territory (the same reason Unix pipes conquered computing: small tools, composable). Second, <em>verification design is the actual product.</em> Anyone can ask an AI to «sort my files»; the receipts, quarantines, reconciliations and sampling rituals are what make the output TRUSTABLE, and trust is what businesses buy. When Track 11 prices these services, notice the invoice line-items are all specification and verification — the session time is nearly free. The economy is quietly repricing exactly the skills this track drilled.</p>"
};

/* ------------------------------------------------ 5.4 */
L["5.4"] = {
  sub: "Documents with structure, spreadsheets with working formulas, presentations with design — Cowork as the office suite operator, and you as the editor who signs off.",
  breath: "Cowork produces real office artifacts — formatted Word docs, Excel sheets with live formulas, PowerPoint decks — from outcome specs; your craft is the brief (audience, structure, source-grounding) and the sign-off ritual.",
  asOf: true,
  hook: "<p>The report that eats your Sunday. The deck rebuilt at midnight. The workbook where one formula broke and nobody knows which. Office artifacts are where knowledge work becomes visible — and where its hours vanish. Cowork writes these natively now: not text ABOUT a spreadsheet, but the .xlsx itself, formulas live; not slide suggestions, but the .pptx. What remains scarce is what was always scarce: knowing what the artifact is FOR, and standing behind what it says. That's the job description of an editor — welcome to your promotion.</p>",
  secs: [
    { h: "Documents: brief like a chief of staff",
      b: "<ul><li><strong>The spec stack you already own, aimed at .docx:</strong> audience + purpose (2.2's rule 5 — «for the CFO, to unlock budget» changes everything), structure contract (2.4 — sections, lengths, what leads), voice (2.6/4.8 — your style skill fires here), and grounding («every figure from the attached sources, cited; gaps stated, not filled» — 3.4, forever).</li><li><strong>Multi-document jobs are Cowork's edge:</strong> «from these 12 project files, produce the quarterly review doc» — reading across sources and synthesising into ONE formatted artifact is exactly what delegation does that chat-pasting can't.</li><li><strong>Iterate on the file, in place:</strong> revisions are conversational («section 3 tighter; move risks before budget») and can be made directly to the document — 2.7's verbs, operating on real files.</li></ul>"},
    { h: "Spreadsheets: formulas, not frozen numbers",
      b: "<ul><li><strong>Demand LIVE formulas.</strong> The amateur output is a sheet of pasted values; the professional spec says «projections as formulas referencing the assumptions block, so changing an assumption recalculates everything.» A model, not a snapshot.</li><li><strong>The assumptions block is non-negotiable:</strong> every input the client might question — growth %, costs, rates — in one labelled area, referenced everywhere else. This is 3.4's provenance discipline expressed in spreadsheet architecture (and it's what makes the artifact survive its first hostile meeting).</li><li><strong>Verification, spreadsheet edition:</strong> reconciliation rows («total must equal sum of parts»), a sanity tab, and YOUR spot-check of 3 formulas by clicking into them (4.4's law: numbers come from computation — here, verify the computation wiring itself).</li></ul>"},
    { h: "Decks: argument first, slides second",
      b: "<ul><li><strong>Spec the argument, not the decoration:</strong> «10 slides for [audience]: 1 the pain quantified, 2–3 the evidence, 4 the proposal, 5 economics, … each slide = one claim + its support; appendix for detail» — a deck is a document with a rhythm (2.4's shape-first thinking at presentation scale).</li><li><strong>Source-bound content:</strong> deck numbers inherit the same grounding rules as everything else — a beautiful slide with an invented figure is a career incident wearing good design.</li><li><strong>The sign-off ritual (all three artifact types):</strong> before anything leaves — read as the AUDIENCE (does slide 4 answer their objection?), spot-check the load-bearing numbers to sources, and run the hostile-critic pass (3.4) on anything high-stakes: «what would the toughest person in that room attack?»</li></ul>"}
  ],
  worked: { t: "Worked example — board pack Friday, editor's edition",
    html: "<div class='wstep'><p class='nar'><em>The job:</em> Dev's monthly investor update — doc + metrics workbook + 8-slide deck, previously his entire Friday. <em>The delegation (one session, three artifacts):</em> sources granted (metrics exports, last month's pack, the decisions log). Doc spec: structure contract from last month's format, «deltas highlighted, misses stated plainly with cause — no spin», voice skill applied.</p></div><div class='wstep'><p class='nar'><em>Workbook spec:</em> assumptions block (burn, growth, hiring plan) → formula-driven runway model; reconciliation row against the bank export; variance tab auto-comparing plan vs actual. <em>Deck spec:</em> the argument («we're on plan, one metric needs attention, here's the fix») mapped to 8 slides, numbers pulled ONLY from the workbook — single source of truth across artifacts, so nothing can disagree with itself.</p></div><div class='wstep'><p class='nar'><em>The editor's hour:</em> Dev reads as an investor (rewrites one slide title that buried the lede), clicks three formulas (wiring sound), runs the hostile critic on the miss-explanation (it flags a phrase that sounded like blame-shifting — reworded). <em>Friday became ninety minutes: sixty of session time he mostly ignored, thirty of editorial judgment only he could supply. The pack got BETTER — consistency across artifacts is machine-grade now. That's the trade: hours down, standards up.</em></p></div>"},
  lab: { where: "Claude desktop app — Cowork",
    html: "<p>Delegate a real office artifact you owe someone (report, budget sheet, small deck). Use the full spec stack:</p>" + PB("prompt — office artifact delegation", "Produce [ARTIFACT + FORMAT] for [AUDIENCE] whose purpose is [THE DECISION/EFFECT].\nStructure: [SECTIONS/SLIDES/TABS + what each contains, lengths].\nVoice: [YOUR RULES or 'apply my style skill'].\nGrounding: all figures from the attached/granted sources, cited by source name; gaps stated plainly, never filled.\nFor spreadsheets: assumptions block + live formulas referencing it + a reconciliation check row.\nFinish with: (1) the artifact, (2) a 'load-bearing numbers' list — the 3 figures I should verify to sources before sending, with their source names.", "prompt") + "<p>Then perform the sign-off ritual: audience-read, verify those 3 numbers, hostile-critic if it's going somewhere consequential.</p>",
    expect: "A genuinely sendable artifact — after YOUR editor's pass. The self-reported load-bearing-numbers list is the pro touch: the artifact arrives carrying its own verification checklist (3.4's flag-for-verification, now standard practice)." },
  mistakes: [
    "<b>Values where formulas belong.</b> A snapshot sheet dies at the first «what if we grow slower?». Demand the model, not the printout.",
    "<b>No assumptions block.</b> Inputs scattered through formulas = a workbook nobody can question or update — including you, next month.",
    "<b>Specifying decoration, not argument.</b> «Make it look professional» produces themes; «each slide one claim + support, appendix for detail» produces persuasion.",
    "<b>Skipping the audience-read.</b> The artifact serves the ROOM; sixty seconds reading as them catches what all your other checks can't.",
    "<b>Sending without the load-bearing check.</b> Three numbers to sources, every time — the entire 1.6→3.4 arc, compressed into the last two minutes before Send."
  ],
  quiz: [
    { q: "«Live formulas referencing an assumptions block» beats pasted values because:",
      opts: ["It looks fancier", "The artifact becomes a MODEL — questionable inputs are visible in one place and changing one recalculates everything — instead of a dead snapshot", "Formulas are shorter", "Pasted values are forbidden"],
      a: 1,
      why: ["Fanciness is not the axis.", "Correct — it's provenance (3.4) as architecture: the sheet can be interrogated, updated, and defended in a meeting. Snapshots can only be believed or not.", "Length is irrelevant.", "Snapshots are fine for archives — just not for artifacts that must answer questions."] },
    { q: "The deck's numbers should come only from the workbook because:",
      opts: ["Decks can't contain numbers otherwise", "A single source of truth makes cross-artifact contradictions impossible — the pack cannot disagree with itself", "It's faster to type", "Investors prefer Excel"],
      a: 1,
      why: ["They can — that's the danger.", "Correct — multi-artifact consistency is a machine-grade strength IF you architect one source of truth. Independently-sourced numbers drift; drift in a board pack is credibility damage.", "Speed isn't the point; integrity is.", "They prefer packs that reconcile."] },
    { q: "The sign-off ritual's three moves:",
      opts: ["Spellcheck, print, pray", "Read as the audience; verify the load-bearing numbers to sources; hostile-critic anything high-stakes", "Send, then check", "Ask Claude «is this good?»"],
      a: 1,
      why: ["Two of those aren't verification.", "Correct — judgment (the room), truth (the numbers), adversarial review (the attack). Everything the course taught, in the last ten minutes before Send.", "Backwards by definition.", "The weak ritual's final form. Structured criticism, fresh context, always (3.4)."] }
  ],
  prac: [
    { tag: "warm", q: "Write the spreadsheet spec (not the sheet) for a freelancer's income model: what's in the assumptions block, what's formula-driven, what reconciles.",
      sol: "<b>Example:</b> assumptions — clients count, avg project fee, projects/client/year, expense %, tax %. Formula-driven — monthly revenue, expenses, tax, net, cumulative savings; a what-if column driven by assumption deltas. Reconciliation — annual net = sum of months; a check cell flagging any month where formulas broke. If your spec has zero named assumptions, rewrite — that block IS the model's honesty." },
    { tag: "transfer", q: "Take the recurring office artifact you personally dread most. Build its full delegation spec, run it, complete the sign-off ritual, and log minutes-before vs minutes-now.",
      sol: "<b>The log line matters:</b> «Monthly report: was 4 hrs, now 35 min (25 editorial).» Three of these lines is a portfolio case study (13.3) and a pricing anchor (11.4). The dread converting to a number is the course working." },
    { tag: "stretch", q: "Your manager fears «AI-written reports will all sound the same and someone will publish a wrong number.» Design the team policy that answers both fears with mechanisms, not reassurance.",
      sol: "<b>One sound policy:</b> voice — team style skill (4.8) + per-author review pass keeps signal; truth — mandatory grounding clauses in every spec, load-bearing-numbers checklists attached to every artifact, and sign-off logged (who verified what); drift-check — monthly, one artifact gets the full hostile-critic audit. Note the shape: the fears are legitimate, and the answer is PROCESS you can show, not promises. Presenting exactly this policy is how AI adoption gets approved in real companies — and being the person who wrote it is how careers get promoted (13.1 will note who's hiring for it)." }
  ],
  recap: "Brief the argument, ground every figure, demand formulas over snapshots with one assumptions block, keep one source of truth across artifacts — then earn the byline: audience-read, load-bearing check, hostile critic.",
  review: "From Lesson 4.4: «numbers come from computation» was about reading files; today it wired the files you SHIP. Same law, other direction.",
  bridge: "Everything so far ran when you asked. Next: work that runs when the CLOCK asks — scheduled tasks, and the strange pleasure of reports that exist before you wake.",
  deep: "<p><strong>The office suite as agent territory — why this was the frontier that fell in 2026.</strong> Documents, sheets and decks are STRUCTURED artifacts with internal consistency constraints (formulas must compute, sections must flow, slides must sequence) — harder for generative systems than prose, which is why «real .xlsx with live formulas» lagged «write me an essay» by years. The unlock was agentic iteration: modern systems build, CHECK (does the formula evaluate? does the total reconcile?), and repair before presenting — a verification loop inside the generation, which is the same evaluator-optimizer pattern you'll build in Track 10. Two operator insights fall out. First, <em>artifacts with checkable structure are SAFER delegation targets than prose</em> — a broken formula announces itself; a subtly wrong paragraph doesn't — so lean delegation harder into structured outputs. Second, <em>the editor role is not transitional.</em> The bottleneck moved from production to judgment, and judgment doesn't automate the same way: knowing what the room needs, which number is load-bearing, what the toughest reader will attack — that's accumulated context about HUMANS, and it's why the byline still means something. Charge for the byline (Track 11 will), not the typing.</p>"
};

/* ------------------------------------------------ 5.5 */
L["5.5"] = {
  sub: "Scheduled tasks: delegation meets the calendar. Work that runs at 6am without you — and the design discipline that keeps unattended automation honest.",
  breath: "Cowork tasks can run on schedules — daily briefs, weekly reports, monthly maintenance — turning your proven delegations into standing automation; unattended work demands stricter specs: conservative permissions, quarantines, receipts, and a review habit.",
  asOf: true,
  hook: "<p>There is a particular feeling — every operator remembers their first time — of opening your laptop at 8am and finding the report already there. Correct. Formatted. Waiting. Nobody did it while you slept; SOMETHING did, following rules you wrote. Scheduled tasks are where Claude stops being a tool you pick up and becomes infrastructure you rely on — and infrastructure has different engineering standards than tools. This lesson installs both: the magic, and the standards.</p>",
  secs: [
    { h: "What schedules unlock",
      b: "<ul><li><strong>The morning brief, automated:</strong> your 4.7 sweep (inbox, calendar, priorities) running before you wake — arriving as a finished note, not a prompt you remember to send.</li><li><strong>Recurring reports:</strong> the weekly status, the Monday metrics summary, the monthly client update draft — 5.4's specs on a timer.</li><li><strong>Maintenance runs:</strong> 5.3's organise-pattern re-applied weekly — the Downloads folder that simply never re-chaosifies.</li><li><strong>Watchers:</strong> «every morning, check [sources] for [conditions]; only alert me if triggered» — competitor price moves, new filings, keyword mentions. Quiet until it matters.</li></ul><p>The promotion rule: <strong>only proven delegations get scheduled.</strong> A task earns its schedule the way it earned Auto mode (5.2) — clean manual runs first, receipts verified. Scheduling an unproven spec is automating a question mark.</p>"},
    { h: "Unattended = stricter, by design",
      b: "<p>Nobody's watching, so the spec compensates:</p><ul><li><strong>Conservative permissions:</strong> scheduled tasks read, compile, draft, and file — they don't send, delete, or commit irreversible acts. Outputs land as DRAFTS for your review (the human hinge from 4.7, now structural).</li><li><strong>Self-describing receipts, every run:</strong> each execution produces its summary — what it did, what it found, what it quarantined, what failed. An unattended task without a run-log is unauditable by construction.</li><li><strong>Failure honesty:</strong> the spec says what to do when inputs are missing or weird — «if the export file is absent, write NOTHING and flag it; never fabricate from stale data» (3.4's honesty layer, cron edition — staleness is the scheduled task's signature hallucination).</li><li><strong>Drift review, weekly:</strong> five minutes skimming run-logs. Automation rots silently — sources change format, folders move, assumptions age. The review habit is the maintenance contract you sign with yourself.</li></ul>"},
    { h: "Designing a schedule portfolio",
      b: "<ul><li><strong>Start with two:</strong> one BRIEF (information TO you — morning sweep) and one MAINTENANCE (order FOR you — folder hygiene). Different failure modes, both low-stakes, fast trust-building.</li><li><strong>Name them like infrastructure:</strong> «Daily brief 06:30», «Weekly folder maintenance — Sun 22:00» — a legible portfolio you can review, prune, and (Track 11) hand to clients as a deliverable.</li><li><strong>Cost-awareness:</strong> every scheduled run spends usage (1.5/5.1's meter) — a daily heavy research run is a real line item. Match cadence to genuine need: does the competitor scan earn its daily slot, or is weekly honest?</li><li><strong>The compounding shape:</strong> your best schedules are your best delegations, which were your best specs, which were your best prompts. The whole course's staircase — prompt → template → skill → delegation → schedule — completes here: craft, running on rails, while you sleep.</li></ul>"}
  ],
  worked: { t: "Worked example — the Monday report that writes itself (honestly)",
    html: "<div class='wstep'><p class='nar'><em>The candidate:</em> Kavya's weekly client-status report — delegated manually five times (5.4 spec), receipts clean five times. Promoted to schedule: Mondays 06:00. <em>The unattended hardening:</em> permissions read-only on the sources + write-only to Drafts/; «if any client folder has no new files this week, say 'no activity' — never pad»; «if the metrics export is missing, produce NO numbers section and flag it at the top»; every run ends with a run-log (sources read, sections built, anomalies).</p></div><div class='wstep'><p class='nar'><em>Monday, 08:15:</em> she reviews the draft over coffee — edits two sentences, sends. Twenty minutes, was three hours. <em>Week 7, the system proves itself:</em> the draft opens with a flag — «metrics export missing; numbers section omitted.» The client's export job had silently broken. <em>The automation's best moment was refusing to work</em> — because the spec made refusal the honest path (imagine instead: a confident report built on last week's stale numbers, sent).</p></div><div class='wstep'><p class='nar'><em>Her drift review (Fridays, 5 min):</em> skim the run-logs, once a month spot-check one report's numbers to sources (sampling — 5.3). In Track 11, this exact artifact — «proven weekly report automation, hardened for unattended runs, with review ritual» — becomes a productised service she installs for clients at ₹8k/month each. <em>The schedule portfolio IS a business; she just doesn't know it yet.</em></p></div>"},
  lab: { where: "Claude — Cowork scheduled tasks (also in Claude Code desktop)",
    html: "<p>Promote your best proven delegation to a schedule. If none is proven yet, use the starter: a morning brief.</p>" + PB("prompt — scheduled morning brief", "Create a scheduled task: every weekday at [TIME], compile my morning brief as a draft note titled 'Brief YYYY-MM-DD'. Contents: (1) today's calendar with one-line prep notes from related docs/threads; (2) unreplied emails from real humans >24h, one line each; (3) [YOUR THIRD SECTION — news watch / metrics check / folder status]. Rules: read-only on all sources; if a source is unavailable, say so in the brief rather than guessing; end every brief with a one-line run-log (sources read, anything skipped). Never send anything anywhere — the draft is for me.", "prompt") + "<p>Let it run three mornings. Verify day one against reality (calibration — 4.7); skim run-logs daily.</p>",
    expect: "Three mornings of arriving-before-you work, one calibration check passed, and — if any source hiccups — an honest flag instead of confident staleness. You now operate infrastructure. Review it like you mean it." },
  mistakes: [
    "<b>Scheduling the unproven.</b> Automation amplifies whatever it runs — including flaws. Manual runs earn the timer.",
    "<b>Unattended send/delete authority.</b> The one rule that prevents the famous horror stories: scheduled tasks draft and file; humans dispatch and destroy.",
    "<b>No run-log.</b> Silent automation is unauditable automation. Every run reports itself, or it doesn't run.",
    "<b>Stale-data fabrication.</b> The missing-input case unspecified = the automation quietly reporting last week as this week. Specify honest failure.",
    "<b>Set-and-forget forever.</b> Drift is real: sources move, formats change, needs evolve. The weekly 5-minute log-skim is part of the automation — schedule THAT too."
  ],
  quiz: [
    { q: "A task qualifies for scheduling when:",
      opts: ["You're excited about it", "It has clean proven manual runs with verified receipts — schedules are a promotion, not a birthplace", "It's completely new", "It involves sending emails automatically"],
      a: 1,
      why: ["Excitement schedules question marks.", "Correct — same evidence ladder as Auto mode (5.2): prove, then promote. Automation amplifies whatever quality exists.", "New tasks start in Manual, attended.", "Auto-send is precisely what unattended tasks DON'T get."] },
    { q: "«If the export is missing, omit the numbers section and flag it» exists because:",
      opts: ["Exports never go missing", "The scheduled task's signature failure is confident staleness — building this week's report from last week's data; honest refusal must be specified as the fallback", "Flags look professional", "It saves tokens"],
      a: 1,
      why: ["They go missing constantly — that's why the clause exists.", "Correct — 3.4's honesty engineering, cron edition. Kavya's week-7 save was this exact clause firing.", "It's integrity, not decoration.", "Marginal — the value is truth, not economy."] },
    { q: "The drift review (weekly log-skim + monthly spot-check) is:",
      opts: ["Optional once things work", "The maintenance contract of automation — sources and formats change silently, and rot is invisible without receipts being read", "A sign of distrust in AI", "Only for enterprises"],
      a: 1,
      why: ["'Working' is a snapshot; drift is a process.", "Correct — infrastructure standards: monitoring is part of the system, not a comment on it. Five minutes buys you the right to rely on it.", "It's the same trust-with-verification you'd give any process — human teams get reviewed too.", "One person's morning brief deserves the same honesty as a bank's pipeline — the stakes differ; the principle doesn't."] }
  ],
  prac: [
    { tag: "warm", q: "Design (on paper) your two starter schedules — one brief, one maintenance: name, cadence, sources, the honest-failure clause, and the receipt.",
      sol: "<b>Check each against the four:</b> read/draft-only permissions? run-log specified? missing-input behaviour stated? cadence matched to real need (not enthusiasm)? If all four — you've designed unattended automation to a professional standard, before running any." },
    { tag: "transfer", q: "Run the lab's brief for a full week, then write the honest week-one report: what it got right, what drifted, what you changed, what it's worth in minutes.",
      sol: "<b>The report's shape:</b> accuracy observations (calibration), one spec improvement made (there's always one — usually the third section's scope), and the minutes number for the ledger (4.8/5.3's running total). A week of receipts reviewed = you're no longer experimenting; you're operating." },
    { tag: "stretch", q: "Design the «automation portfolio» page you'd show a prospective client: your 4–6 running schedules, each with its safeguards — and the pitch line that turns it into a service.",
      sol: "<b>The page:</b> name / cadence / what it produces / safeguards (permissions, honest-failure, receipts) / minutes it saves. <b>The pitch line:</b> «I design, harden, and maintain unattended AI workflows — here are mine, running for months. I install yours in a week: ₹X setup + ₹Y/month including the drift reviews.» The portfolio IS the credential — screenshots of receipts beat any certificate (13.3 will say the same about all portfolio artifacts). Kavya's ₹8k/month per client wasn't hypothetical; this page is how it's sold." }
  ],
  recap: "Prove, then schedule; read-and-draft permissions only; every run logs itself; missing inputs fail honestly; and the weekly drift review is part of the automation — craft on rails, standards raised.",
  review: "From Lesson 5.2: the evidence ladder (Manual → Auto → scheduled) is one continuous climb — each rung purchased with verified receipts from the rung below.",
  bridge: "Final Cowork lesson: the power patterns — Cowork Projects, standing instructions, and sub-agents — the pieces that turn individual delegations into an organised operation.",
  deep: "<p><strong>Cron for cognition — and why reliability engineering just became a life skill.</strong> Scheduled computation is ancient (cron, 1975); what's new is scheduling JUDGMENT-ADJACENT work — summarise, assess, flag, draft — where failure modes are subtle (staleness, drift, plausible-but-wrong) rather than loud (crash). That's why this lesson imported reliability engineering's furniture: run-logs (observability), honest-failure clauses (graceful degradation), drift reviews (monitoring), read-only defaults (least privilege). The professional world is converging on the same standards — 2026 enterprise AI policies increasingly REQUIRE audit logs and human dispatch gates for unattended agents, which means your personally-earned habits are also compliance literacy. One frame worth keeping: an unattended AI task is a tiny EMPLOYEE with perfect attendance, zero judgment beyond its spec, and no shame about fabricating — so the spec must supply the judgment and the honesty. You've spent five tracks learning to write exactly such specs. Next track's sub-agents make it an org chart; Track 10 makes it an engineering discipline; Track 11 makes it an invoice.</p>"
};

/* ------------------------------------------------ 5.6 */
L["5.6"] = {
  sub: "Projects, standing instructions, and sub-agents: the pieces that turn a pile of clever delegations into an organised, compounding operation.",
  breath: "Cowork scales through structure — Projects give delegations rooms with files and standing instructions, folder rules encode house law, and sub-agents parallelise big jobs — your one-person operation, organised like a firm.",
  asOf: true,
  hook: "<p>A talented freelancer with chaotic systems loses to an average one with great systems — every industry knows this. The same law now applies to your AI operation. You have delegations (5.1–5.4), schedules (5.5), skills (4.8): the TALENT is assembled. This lesson is the SYSTEMS: rooms so context compounds, standing law so quality is default, and sub-agents so big jobs parallelise. The difference between «I use Cowork» and «I run an operation on Cowork» is exactly these structures — and it's also, precisely, what you'll sell in five tracks' time.</p>",
  secs: [
    { h: "Cowork Projects: rooms for your operation",
      b: "<ul><li><strong>The 4.2 idea, upgraded with hands:</strong> a Cowork Project bundles related tasks with shared files, instructions and memory — but here the room's occupant DOES things. The «Client Zenith» project holds their folders, voice rules, and delivery specs; every session inside starts briefed AND equipped.</li><li><strong>Project memory makes sessions compound:</strong> decisions and context persist across sessions within a project (the 4.3 layer, scoped to the room) — «continue the migration from where Tuesday's session stopped» actually works.</li><li><strong>One project per ongoing OPERATION</strong> — per client, per recurring pipeline (the Monday-report machine), per life-domain. Same admission test as 4.2: five-plus sessions sharing context. Disposable errands stay roomless.</li></ul>"},
    { h: "Standing instructions: house law, written once",
      b: "<ul><li><strong>Global instructions</strong> (all Cowork work) carry your constitution: «move never delete; ambiguity → Review/; every task ends with a receipt; drafts never sends.» Your 5.1–5.5 hard-won rules, promoted from per-prompt to ALWAYS.</li><li><strong>Folder instructions</strong> carry local law: «_originals/ is read-only»; «this client's files never leave this folder tree.» Location-scoped rules that fire regardless of which task wanders in — you'll recognise the pattern as CLAUDE.md thinking (7.3) arriving early.</li><li><strong>The layering discipline</strong> (2.6's altitudes, completed): global law → project law → folder law → task spec. Each layer holds what's true at ITS scope — and when you correct the same thing twice at task level, it graduates upward (the 2.7/4.2 promotion habit, now with four floors).</li></ul>"},
    { h: "Sub-agents: the big-job multiplier",
      b: "<ul><li><strong>What they are:</strong> for large tasks, Cowork can split work into parallel workstreams — sub-agents each handling a slice (one per client folder; one per document batch), coordinated toward your outcome. Your 3.1 map-reduce, executing itself.</li><li><strong>Why you care beyond speed:</strong> sub-agents keep slices ISOLATED — each works its own context without cross-contamination (the clean-desk principle, 1.2, applied organisationally), then results merge. Big messy jobs stay coherent.</li><li><strong>Your management surface stays the same:</strong> outcome spec, quarantines, receipts — but add a MERGE check: «after parallel processing, verify the combined output's totals reconcile against per-slice receipts.» Parallel work's signature bug is seams; the spec inspects the seams.</li><li><strong>Where this goes:</strong> orchestrated sub-agents are the beating heart of Track 10's architectures (orchestrator–workers, literally). Cowork gives you the managed version; you're learning multi-agent design with guardrails included.</li></ul>"}
  ],
  worked: { t: "Worked example — the operation, assembled",
    html: "<div class='wstep'><p class='nar'><em>Six weeks after her first delegation, Kavya's setup:</em> GLOBAL LAW — the constitution (never delete; Review/ quarantines; receipts always; drafts never sends). THREE ROOMS — «Client Meridian», «Client Osier», «Agency Ops» — each with folders, voice rules, delivery specs, and project memory carrying running context. TWO SCHEDULES per client room (Monday report; Friday folder maintenance) + the personal morning brief in Ops.</p></div><div class='wstep'><p class='nar'><em>The big-job test:</em> Meridian dumps 14 months of scattered campaign data — «make sense of it by Thursday.» One outcome spec in the Meridian room; Cowork splits by month across sub-agents, each extracting to the shared schema (3.3's contract as the coordination mechanism — EVERY sub-agent obeys the same schema, which is WHY the merge works), then merges with a reconciliation pass her spec demanded: per-month row counts vs combined total. One seam error caught by the check (a month double-counted in overlap) — fixed before she ever saw wrong data.</p></div><div class='wstep'><p class='nar'><em>The point of the story:</em> Thursday's deliverable took her 40 minutes of attention — spec, two checkpoints, sign-off ritual (5.4). A year ago: a week of evenings. But notice what actually did the work: not the model — <strong>the STRUCTURE.</strong> Rooms briefed it, law constrained it, schemas coordinated it, receipts verified it. <em>Talent is rented from Anthropic by everyone at the same price; systems are yours. Track 11 sells the systems.</em></p></div>"},
  lab: { where: "Claude desktop app — Cowork",
    html: "<p>Assemble YOUR operation's skeleton (30 minutes): (1) Write your global standing instructions — your constitution from everything Tracks 5.1–5.5 taught you. (2) Create your first Cowork Project for your #1 ongoing context; give it folder grants + project instructions. (3) Inside it, run one real task that uses the room's context without you re-explaining. Draft the constitution with help:</p>" + PB("prompt — constitution draft", "Draft my global Cowork standing instructions from these principles I've adopted: move-never-delete; ambiguity quarantined to Review/ folders, never guessed; every task ends with a receipt (what was done, counts, anything skipped); scheduled/unattended tasks are read-and-draft only — nothing sent or deleted without me; missing inputs = honest flags, never stale fabrication; [ADD YOUR OWN from your delegation cards]. Make it tight (under 150 words), imperative, unambiguous.", "prompt"),
    expect: "A constitution installed, one room live, one task running briefed-by-structure. From now on every session starts from your accumulated law instead of from zero — feel the difference on the very next delegation." },
  mistakes: [
    "<b>All talent, no structure.</b> Fifty clever one-off delegations with no rooms, law, or receipts — impressive, unscalable, and unsellable. Structure is the moat.",
    "<b>Law at the wrong altitude.</b> Client-specific rules in global instructions (leak risk), universal rules re-typed per task (waste). Each rule at its widest-true scope.",
    "<b>Rooms without maintenance.</b> Project files and instructions rot like 4.2 shelves — the drift review (5.5) covers rooms too.",
    "<b>Parallel jobs without seam checks.</b> Sub-agent merges are where double-counts and gaps hide; reconciliation across slices is part of any parallel spec.",
    "<b>Building the operation and never USING the leverage.</b> The point of systems is taking on bigger things — bigger clients, bigger jobs, eventually paying ones. Structure is for spending."
  ],
  quiz: [
    { q: "The four altitudes of standing law, widest to narrowest:",
      opts: ["Task → folder → project → global", "Global instructions → project instructions → folder rules → task spec", "There's only one place for rules", "Alphabetical"],
      a: 1,
      why: ["Reversed.", "Correct — each rule lives at its widest-true scope, and repeated task-level corrections graduate upward. The 2.6 layering, fully built out.", "Four layers exist precisely so rules can live at the right scope.", "Still no."] },
    { q: "Sub-agents' deeper value beyond speed:",
      opts: ["They're free", "Isolation — each slice works a clean context, avoiding cross-contamination, with a merge step your spec must verify", "They never err", "They replace specifications"],
      a: 1,
      why: ["They consume usage like all agentic work (the meter, always).", "Correct — clean desks per slice (1.2, organisational edition) plus seam-checking at merge. Coherence at scale is the prize.", "They inherit the spec's quality — which is why the schema-as-coordination trick matters.", "They multiply specifications' reach; sloppy specs parallelise into sloppy results, faster."] },
    { q: "«Talent is rented; systems are yours» means:",
      opts: ["Models are useless", "Everyone rents the same models at the same price — your compounding advantage is the structure: rooms, law, schemas, receipts, schedules", "Never pay for subscriptions", "Systems replace skill"],
      a: 1,
      why: ["The talent is spectacular — and identically available to your competitors.", "Correct — the differentiator (and the sellable asset, Track 11) is the operation built AROUND the model. This is the track's thesis and arguably the course's.", "Subscriptions rent the talent; still worth it (1.5's math).", "Systems ENCODE skill — yours, accumulated. That's why they're worth money."] }
  ],
  prac: [
    { tag: "warm", q: "Audit your current setup against the operation checklist: constitution written? rooms for ongoing contexts? schedules with receipts? Which piece is missing and costs you most?",
      sol: "<b>Most common answer:</b> the constitution — people run good per-task specs and re-type the same rules forever. Thirty minutes fixes it permanently. Second most common: no receipts on the oldest automations (they predate your standards — retrofit them)." },
    { tag: "transfer", q: "Take a genuinely big job you've been avoiding (100+ files, months of data, a multi-part deliverable). Spec it for sub-agent execution: the shared schema, the split logic, and the seam checks. Run it.",
      sol: "<b>The spec's three tests:</b> could each slice run alone with only the schema? (isolation) — does the split have no overlaps/gaps by construction? (coverage) — does the merge reconcile per-slice receipts? (seams). Pass all three and the job you avoided becomes an afternoon of checkpoints. That feeling — big things becoming specifiable — is the track's graduation." },
    { tag: "stretch", q: "Write the one-page «operations manual» for your AI-assisted practice as if onboarding a junior partner: the law, the rooms, the schedules, the verification rituals, and what humans never delegate.",
      sol: "<b>The manual's sections:</b> Constitution (global law) · Rooms (per-client structure + what lives where) · Standing automations (the 5.5 portfolio page) · Verification (receipts, sampling, sign-off rituals, drift reviews) · Red lines (deletes, sends, payments, sole-copies — humans only). If a stranger could run your operation from this page, you've built something REAL: it onboards collaborators, reassures clients (11.7), survives your vacations, and — notice — it's the document a buyer would ask for if you ever sold the practice. One page. That's systems." }
  ],
  recap: "Rooms for compounding context, law layered at four altitudes, sub-agents with schema-coordination and seam checks — talent is rented, systems are yours, and the operation is the asset.",
  review: "From Lesson 4.2: Projects gave chats rooms; today rooms got hands, memory, law and staff. The same idea, grown into an operation.",
  bridge: "Track 5 complete — you manage an AI operation. Track 6 shortens the distance to your other tools: Claude inside Chrome, Excel, Slack — and the judgment of which surface wins for which job.",
  deep: "<p><strong>Your operation is an organisation — the same theory applies.</strong> Coase asked in 1937 why firms exist at all; the answer — coordination costs — explains your last six lessons better than any AI paper. Rooms are departments (context specialisation), standing law is policy (decisions made once, applied always), schemas are interfaces (how departments hand off work), receipts are accounting (trust through verification), sub-agents are teams (parallel capacity), schedules are operations (work decoupled from attention). You've built a firm of one human and N agents — and firm theory predicts what you'll feel next: the binding constraint shifts from CAPACITY (solved: agents are elastic) to SPECIFICATION AND VERIFICATION BANDWIDTH — your ability to define done-and-right and to audit it. That's why the course drilled those two skills relentlessly before handing you an org chart. It also predicts the market: as everyone gains elastic capacity, the price of raw production falls while the price of trustworthy specification rises — visible already in 2026 freelance rates (11.1's data: «AI automation» commodity gigs race to the bottom; «AI operations design» commands multiples). You're on the right side of that trade. Three tracks of builder skills next — then we go collect.</p>"
};

})();
